sources/lib/api/lint.sh
sources/lib/datalab/lint.sh
sources/lint.sh

pylint is crashing on our code so using flake8 for now (it gives more
output anyway).
Issue #1 !

Add lint scripts.

---

sources/lib/api/tests/bq_api_tests.py
sources/lib/datalab/gcp/datalab/_bigquery.py

Add --verbose option to %bigquery sample

---

sources/lib/api/gcp/bigquery/_api.py
sources/lib/api/gcp/bigquery/_query.py
sources/lib/api/gcp/bigquery/_udf.py
sources/lib/api/gcp/data/__init__.py
sources/lib/api/gcp/data/_sql_module.py
sources/lib/api/gcp/data/_sql_statement.py
sources/lib/api/gcp/storage/_item.py
sources/lib/api/tests/bq_api_tests.py
sources/lib/api/tests/bq_query_tests.py
sources/lib/api/tests/bq_udf_tests.py
sources/lib/api/tests/sql_tests.py
sources/lib/datalab/gcp/datalab/_bigquery.py
sources/lib/datalab/tests/bigquery_tests.py

Add the ability to call UDFs directly in the SQL without having to compose them via Python code into a FunctionCall first, as well as reference code in GCS.
Issue #606

UDF Support: Direct calls and GCS hosted code

---

sources/lib/datalab/gcp/datalab/_bigquery.py
sources/lib/datalab/gcp/datalab/_html.py

This is useful for notebooks viewed in non-execution environments like
github. We will render the data in the div initially and the charts code
will overwrite that with a new rendering if that code executes.

Include a static rendering of table data in the table viewer.

---

sources/lib/api/gcp/bigquery/_table.py

Fix the handling of to_dataframe when the table is empty.

---

containers/datalab/Dockerfile.in

Played with some sample TF code and it works well. :)

include tensorflow

---

content/datalab/tutorials/BigQuery/Importing and Exporting Data.ipynb
sources/lib/api/gcp/bigquery/_query.py
sources/lib/api/gcp/bigquery/_view.py

merge conflicts when merging federated table support.

Fix storage sample notebook, and a few regressions that crept in from

---

content/datalab/Readme.ipynb
content/datalab/tutorials/BigQuery/UDF Testing in the Notebook.ipynb

And fixed a typo in a sample while at it.

Updated readme notebook to include new samples

---

content/datalab/Readme.ipynb

Fix links in Readme notebook.

---

sources/web/datalab/static/datalab.js

Remove the 'Running' text from uunexecuted cells upon an error.

---

sources/lib/api/gcp/bigquery/_query_job.py

Get job status with correct project.

---

sources/lib/api/gcp/data/_sql_statement.py
sources/lib/datalab/gcp/datalab/_sql.py
sources/lib/datalab/tests/sql_tests.py

Add support for list/tuple variables that can be used in IN expressions.

---

sources/lib/datalab/gcp/datalab/_bigquery.py

Add the ability to specify SQL inline in execute/sample/etc magics.

---

sources/lib/datalab/gcp/datalab/__init__.py
sources/lib/datalab/gcp/datalab/_bigquery.py
sources/lib/datalab/gcp/datalab/_chart.py
sources/lib/datalab/gcp/datalab/_extension.py

Don't limit the JSON encoder to ASCII when encoding chart/table data.

---

sources/web/datalab/static/extensions/charting.js

Reworked version of the code to create a PNG from a chart so that viewing notebooks on Github shows something for charts.
Issue #684

Charts now add an image/png display output to notebook.

---

sources/lib/datalab/gcp/datalab/_bigquery.py
sources/lib/datalab/gcp/datalab/_chart.py
sources/web/datalab/static/extensions/charting.css
sources/web/datalab/static/extensions/charting.js

Fix the conflict between Bootstrap and map charts.

---

sources/lib/api/gcp/bigquery/_dataset.py
sources/lib/api/gcp/bigquery/_query.py
sources/lib/api/gcp/data/_sql_module.py
sources/lib/api/gcp/storage/_bucket.py
sources/lib/api/gcp/storage/_item.py
sources/lib/api/tests/bq_query_tests.py
sources/lib/datalab/gcp/datalab/_bigquery.py
sources/lib/datalab/gcp/datalab/_storage.py
sources/lib/datalab/tests/storage_tests.py

Issue #636
This is just going through places we raise exceptions and making minor adjustments to the messages to make them a bit more clear.

Improved some error messages.

---

sources/lib/api/gcp/data/_sql_statement.py
sources/lib/api/tests/sql_tests.py

Handle $ in queries when not followed by an identifier or another $.

---

sources/lib/datalab/gcp/datalab/_bigquery.py

Fix a regression in table viewing via _repr_html_ that was caused by

---

sources/lib/api/gcp/bigquery/_schema.py
sources/lib/api/tests/bq_schema_tests.py
sources/lib/api/tests/bq_table_tests.py
sources/lib/api/tests/main.py

In particular, fixes the issue with creating nested schema.
Issue #595

Some fixes/improvements to the Schema inference code. 

---

sources/lib/datalab/gcp/datalab/_sql.py

Don't strip Python-style comments out of SQL code in %%sql cells.

---

sources/lib/datalab/gcp/datalab/_bigquery.py

I'm separating this from the pull request which has the updated samples
in the hope of having it reviewed sooner.

Fix a couple of bugs found from rerunning samples.

---

sources/lib/datalab/datalab/utils/_http.py
sources/web/datalab/static/datalab.js
sources/web/datalab/templates/nb.html

Bring back checkpoints. Currently there is just a single checkpoint at the time of last manual save.
Improved generation of error messages from HTTP requests.
(Issue https://github.com/GoogleCloudPlatform/datalab/issues/797)

Bring back checkpoints and improve HTTP error messages.

---

sources/web/datalab/auth.ts

Previously, we relied on the "referer" query parameter being passed
in (which is the case when going through the login flow in the UI,
but not when going directly to the "/signin" page).
This changes the logic to instead rely on the request's "host"
header field, which should always be set regardless of whether or
not the "referer" query parameter is set.

Improve the logic for determining the port number of the server.

---

README.md

Fix broken link to samples and documentation

---

sources/web/datalab/jupyter.ts

This change makes the Datalab NodeJS server, at startup, list
all processes for the 'jupyter-notebook' binary, and kill them.
This fixes #892, where those processes could become abandoned
if the NodeJS server gets restarted.
This should be a safe thing to do at startup, as the NodeJS
server only runs inside of a Docker container, and so it has
an isolated process space.
I.E. the only processes that should be killed are those that
were started by an earlier incarnation of the NodeJS server.

Make the Datalab server kill abandoned Jupyter servers.

---

containers/datalab/run-with-gce.sh
containers/gateway/deploy.sh

This change fixes two notable usability issues with running Datalab
against a kernel gateway in a GCE VM. Specifically, with this change we will:
1. Create a separate VM for each user.
2. Enforce that the user's SSH keys are copied to that VM before trying
to connect to it.
The first change fixes an issue where multiple users could have been
making changes to the same kernel if they were using the same kernel
gateway. This was due to the fact that the only information used to
identify a kernel in the kernel gateway was the path to and name of
the notebook. As such, if two users were running the same notebook,
they would have wound up touching the same kernel (and sharing
mutable state).
The second change fixes a first-time-use issue where the script would
not cause a user's SSH keys to be …

Usability improvements for the run-with-gce.sh script.

---

containers/datalab/build.sh
containers/gateway/build.sh

Remove the dependency on pushd/popd

---

externs/ts/node/node-http-proxy.d.ts
sources/web/datalab/auth.ts
sources/web/datalab/jupyter.ts
sources/web/datalab/reverseProxy.ts
sources/web/datalab/server.ts

Save boto file so gsutil works with Datalab's auth mechanism.

Add reverse proxy function in web.

---

containers/datalab/content/run-with-gce.sh

thinks the user has logged in and proceeds.

Fix an issue that when user is not logged in, run-with-gce.sh still

---

containers/datalab/content/run.sh

And add a message saying to open your browser.

Make Datalab silent by default.

---

sources/web/datalab/jupyter.ts

Increase the timeout used to confirm that Jupyter server has started

---

sources/web/datalab/static/datalab.css
sources/web/datalab/static/datalab.js
sources/web/datalab/static/light.css
sources/web/datalab/templates/edit.html
sources/web/datalab/templates/nb.html
sources/web/datalab/templates/sessions.html
sources/web/datalab/templates/tree.html

Added a sign out dropdown menu under a new account icon, and changed the sign in button. I had to change some CSS class names to not conflict with bootstrap.

Improving the sign-in/out experience

---

sources/web/datalab/static/dark.css
sources/web/datalab/static/datalab.css
sources/web/datalab/templates/edit.html
sources/web/datalab/templates/nb.html
sources/web/datalab/templates/sessions.html
sources/web/datalab/templates/tree.html

This change fixes a few issues with dark theme, especially inside a notebook. It also spaces out the "Signed In as" and the Sign Out button in the account dropdown, and changes the upload button to an actual button control.
Fixes issue #964

Dark theme fixes

---

containers/base/Dockerfile
containers/datalab/content/run.sh

Branch has been rebased to latest master.

Merge feature/mlbeta2 into master

---

.gitignore
sources/web/datalab/server.ts
sources/web/datalab/settings.ts

Use the settings module to save and load the last path visited by the user so it's persistent across different visits

Persist the last user path and set it as startup path

---

sources/web/datalab/static/dark.css

Fix command palette styles in dark theme

---

tools/release/publish.sh

This change extends the release script so that it runs the latest version
of the notebook tests using the new Datalab image before it will promote
that image.

Make the release script run notebook tests

---

containers/base/Dockerfile

For now we simply pin Pillow to the previous, working version.

Fix a build breakage introduced by a new version of Pillow.

---

tools/initenv.sh

Removing obsolete boot2docker references

---

sources/web/datalab/static/datalab.js

Clear complete marks from code cells when kernel is restarted

---

containers/base/Dockerfile
sources/web/datalab/config/settings.json
sources/web/datalab/templates/nb.html

Also fix Dockerfile extra endings

Add mathjax by default to all notebooks

---

containers/base/build.sh
containers/datalab/build.sh
containers/datalab/content/setup-env.sh
containers/datalab/debug.sh
containers/datalab/logs.sh
containers/datalab/run-extended.sh
containers/datalab/run.sh
containers/datalab/stage.sh
containers/gateway/build.sh
containers/gateway/content/run.sh
containers/gateway/content/setup-env.sh
containers/gateway/run.sh
tools/initenv.sh

dash doesn't have `source` defined, which was breaking the build.

Use /bin/bash for shell scripts instead of dash

---

sources/web/datalab/static/datalab.js

Fixing navigation links not triggering scroll.
Fixes #1039

Fix nav links

---

tools/gcsbackup/GCSbackup.sh

This is related to automatic directory backup using GCS.
This PR changes the backup script to skip backing up directories when no changes are made. Without this, if we set up automatic backups every one hour for the last 10 hours for example, we end up with 10 copies of the same archive if no changes were made in the last 10 hours.

Use gsutil's md5 hash to skip unnecessary backups

---

tools/gcsbackup/GCSbackup.sh

This PR fixes a few things in the gcs backup script in preparation to run inside the docker container:
- Add option to append to a log, as well as a help message
- Use the metadata server to get the project id instead of the `gcloud` command
- Move machine id to before the backup path in the resulting backup archive name
- Remove the username from the backup path, machine id + path make it redundant

Prepare gcsbackup script to run inside docker container

---

containers/base/Dockerfile

Update oauth2client to 2.2.0 to satisfy the requirements of cloudml

---

containers/base/build.sh

an ending slash is added to the rsync command.

fixes issue #1118, adds slash to rsync command

---

containers/datalab/Dockerfile.in

Fixes https://github.com/googledatalab/datalab/issues/1123.

Use ungit version 1.0.0

---

sources/web/datalab/static/datalab.css
sources/web/datalab/static/datalab.js

And minor CSS issue. Fixes https://github.com/googledatalab/datalab/issues/1063

Pop toolbar menu upward when there's not enough space

---

CONTRIBUTING.md
README.md

This was previously in the wiki repository (and linked to from
the README), but putting it in the main repository makes it easier
for potential contributors to find.

Move the 'CONTRIBUTING.md' file into the main repository.

---

containers/base/Dockerfile

The Datalab python library is now on PyPI.

Install Datalab Python library using pip

---

tools/cli/commands/connect.py
tools/cli/commands/create.py
tools/cli/commands/utils.py
tools/cli/datalab.py

Apply the --quiet flag to all CLI commands.

---

sources/web/datalab/common.d.ts
sources/web/datalab/config/settings.json
sources/web/datalab/reverseProxy.ts
sources/web/datalab/server.ts
sources/web/datalab/sockets.ts

This adds a config setting for the socket IO port so the server can be
executed in environments where only specific ports are allowed.

Allow configuring the socket.io port.

---

tools/cli/commands/create.py

Configure swap space in Datalab VMs

---

tools/cli/commands/create.py

This change alters the way that the persistent disk used for
storing notebooks is exposed to the Datalab container.
Rather than the entire disk being mounted by the container at
`/content`, we just mount the `datalab` subdirectory at
`/content/datalab`.
That change allows us to create a `tmp` subdirectory, and mount
that into the container at `/tmp`. That, in turn, prevents temp
files created in the container from filling up the VM's boot disk.
This fixes #1192

Make the volume mounts for Datalab instances more sensible

---

containers/base/Dockerfile

It seems the package on pypi does not work when serving static files such as /nbextensions/gcpdatalab/charting.js.

Change DockerFile to get pydatalab from repo instead of pypi. 

---

sources/web/datalab/static/datalab.css
sources/web/datalab/templates/nb.html

Hide the ipywidgets Widgets menu.

---

sources/web/datalab/static/appbar.html
sources/web/datalab/static/datalab.js

Fix for #1206 
This assumes a constant path for the repo location; it does not pull 'datalab' from the current location.

Always open ungit at /content/datalab/notebooks.

---

sources/web/datalab/static/dark.css
sources/web/datalab/static/datalab.css
sources/web/datalab/static/light.css

Fixes https://github.com/googledatalab/datalab/issues/1226
Also fixes output text colors in dark theme.

Css fixes for borders and dark theme colors

---

containers/base/Dockerfile

Fixes https://github.com/googledatalab/datalab/issues/1241.

Disable gcloud update notification message

---

sources/web/datalab/common.d.ts
sources/web/datalab/config/settings.json
sources/web/datalab/jupyter.ts
sources/web/datalab/templates/nb.html
tools/release/publish.sh

This also changes the list so that it is no requires updating the Docker container in order to update the list.

Automate the updating of our sample notebooks list

---

sources/web/datalab/templates/nb.html

Lost during the UI refresh. This is not urgent.

Bring back Notebook down chevron

---

containers/datalab/content/run.sh

Verify the /tmp directory is writeable at startup.

---

tools/cli/commands/utils.py

Support selecting a zone by number.

---

tools/cli/commands/create.py

Fixes #1209. Adds a two-line .gitignore and a one-line README.txt file to new notebook repos.

Add .gitignore and README.txt when creating notebook repo.

---

tools/cli/commands/create.py

1. Don't delete the directory if it already exists. Instead,
just delete the contents of the directory.
2. Make the cloud-config commands wait for the temp directory
to exist before they start the kubelet. This ensures that
the kubelet does not come up while the complex parts of the
startup script are still running (since creating that directory
is the last thing the startup script does).
This fixes #1263

Two fixes for the race condition in setting up the /tmp dir:

---

containers/base/Dockerfile

Fixes https://github.com/googledatalab/datalab/issues/1245.

Update ipywidgets to 6.0.0

---

sources/web/datalab/server.ts
sources/web/datalab/static.ts
sources/web/datalab/static/appbar.html

Only store directories as default tree locations.

---

sources/web/datalab/auth.ts
sources/web/datalab/jupyter.ts
sources/web/datalab/server.ts
sources/web/datalab/static.ts

Followup to cleanup suggestion in #1304. The only changes in this PR are changes in indentation.

Fix some indentation; no code changes.

---

sources/web/datalab/static/notebook-list.js

This PR fixes the Datalab version comparison to use the entire versions obtained from the GCS file (latest), and hard-coded in HTML doc (current). For versions that are not in semver format, they're converted to semver by prepending "0.5." to keep the current behavior.

Fix check for datalab version to use entire version from gcs file

---

containers/base/build.sh
containers/datalab/build.sh
sources/web/build.sh

This also allows running just sources/web/build.sh to compile the typescript files, which I will be using in a later PR to implement live mode.

Allow running build scripts from anywhere

---

sources/web/datalab/static/appbar.js
sources/web/datalab/static/datalab.js
sources/web/datalab/static/edit-app.js
sources/web/datalab/static/minitoolbar.js
sources/web/datalab/static/notebook-app.js
sources/web/datalab/static/notebook-list.js

This PR is mostly whitespace changes Add the query parameter w=1 to the github URL to ignore whitespace and see the actual changes.
There is one intentional functional change: in appbar.js line 6 I removed a call to this.blur() that  no longer works.

Convert most files in static to modules.

---

sources/web/datalab/static/notebook-list.js

I broke the new Terminal button in the previous commit. This fixes it.

Restore line missed when doing merge resolve in previous commit.

---

tools/cli/commands/connect.py

This change updates the `datalab` command line tool so that the
`-o` option to the `gcloud compute ssh` command is only passed
when running on Posix systems (e.g. Linux and Mac OS X).
This is necessary because some SSH clients (notably, PuTTY) do
not support that option, so passing it in can cause the SSH
client to error out.
This was not an issue prior to the 154.0.0 release of the Cloud SDK,
as earlier versions would filter out the `-o` flag when running on
Windows. However, with 154.0.0 that filtering has been removed and
the `-o` option is passed in as-is.
This fixes #1356

Do not set SSH options on Windows.

---

tools/release/publish.sh

Release script exits if any command returns non-zero, I was using a grep command to check for the existence of the `LATEST_SEMVER` string, moved that into an if statement.

Fix release script exiting with non-zero

---

sources/web/datalab/static/appbar.js
sources/web/datalab/static/datalab.js
sources/web/datalab/static/idle-timeout.js
sources/web/datalab/static/notebook-app.js
sources/web/datalab/static/notebook-list.js
sources/web/datalab/static/settings.html
sources/web/datalab/static/settings.js
sources/web/datalab/static/util.js

This moves a couple more functions into utils.js as a cleanup.
It also makes settings.js a module. Unfortunately, I couldn't figure out how to late-load settings.js as a module. If you happen to know how to do that, please let me know.

Move xhr and reportEvent functions into utils.js.

---

sources/web/datalab/app.ts
sources/web/datalab/auth.ts
sources/web/datalab/backupUtility.ts
sources/web/datalab/common.d.ts
sources/web/datalab/fileSearch.ts
sources/web/datalab/health.ts
sources/web/datalab/idleTimeout.ts
sources/web/datalab/info.ts
sources/web/datalab/jupyter.ts
sources/web/datalab/logging.ts
sources/web/datalab/noCacheContent.ts
sources/web/datalab/reverseProxy.ts
sources/web/datalab/server.ts
sources/web/datalab/settings.ts
sources/web/datalab/sockets.ts
sources/web/datalab/static.ts
sources/web/datalab/userManager.ts

I find it confusing to have "Settings" and "UserSettings" which are distinct. The name change in this PR will make that less confusing for me. If you prefer, I could change it to AppConfig instead.

Rename Settings to AppSettings to reduce confusion.

---

containers/datalab/content/run.sh

Create .foreverignore file when in live mode to prevent error message.

---

sources/web/datalab/polymer/components/datalab-app/datalab-app.html
sources/web/datalab/polymer/components/datalab-files/datalab-files.html
sources/web/datalab/polymer/components/datalab-sidebar/datalab-sidebar.html
sources/web/datalab/polymer/components/shared-styles/shared-styles.html

[Polymer UI] Add sidebar shrink animation

---

sources/web/datalab/polymer/modules/ApiManager.ts

We use the same endpoint for all our xhr requests to fetch resources from Jupyter's `/api`. Using the cache sometimes returns stale results.

[Polymer UI] Disable cache for fetching /api resources

---

sources/web/datalab/polymer/components/datalab-files/datalab-files.ts
sources/web/datalab/polymer/modules/ApiManager.ts
sources/web/datalab/server.ts

This PR makes the new UI remember the user's last visited path, like the existing UI does. It does this in a backward-compatible way, so both UIs use the same server setting.

[Polymer UI] Save last user path to startuppath

---

sources/web/datalab/polymer/components/datalab-files/datalab-files.ts

This code was moved to line 136, but I missed part of it in the conflict resolution.

Cleanup repeated code from merge

---

sources/web/datalab/polymer/components/datalab-files/datalab-files.ts
sources/web/datalab/polymer/components/datalab-sessions/datalab-sessions.html
sources/web/datalab/polymer/components/datalab-sessions/datalab-sessions.ts
sources/web/datalab/polymer/modules/ApiManager.ts

This allows (multiple) selected sessions to be shutdown in the sessions page.

[Polymer UI] Add shutdown sessions functionality

---

sources/web/datalab/polymer/components/datalab-toolbar/datalab-toolbar.html
sources/web/datalab/polymer/index.dark.css
sources/web/datalab/polymer/index.light.css

The recent commit 0698e8 caused the icon buttons in the polymer UI to become invisible. This fixes that.

Fix color of toolbar icons in experimental UI.

---

sources/web/datalab/server.ts

This was driving me crazy, the errors we got were not remotely indicative of the problem!

Fix small bug with /api/basepath

---

sources/web/datalab/polymer/components/datalab-info/datalab-info.html
sources/web/datalab/polymer/components/datalab-info/datalab-info.ts
sources/web/datalab/polymer/components/datalab-toolbar/datalab-toolbar.html
sources/web/datalab/polymer/components/datalab-toolbar/datalab-toolbar.ts
sources/web/datalab/polymer/components/shared-styles/shared-styles.html

This adds the info panel from the old UI. There are very little changes between the two UIs, but I think we might want to revisit how this information is presented, given that we also have a few help links.
I also left out the Restart Server button intentionally because there was some discussion on moving it. Feel free to comment about it here.

[Polymer UI] Info Panel

---

sources/web/datalab/polymer/components/base-dialog/base-dialog.html
sources/web/datalab/polymer/components/base-dialog/base-dialog.ts
sources/web/datalab/polymer/components/datalab-files/datalab-files.ts
sources/web/datalab/polymer/components/datalab-sessions/datalab-sessions.ts
sources/web/datalab/polymer/modules/ApiManager.ts
sources/web/datalab/polymer/modules/Utils.ts

This PR adds an error popup when a file operation fails, using the failure returned from the backend.

[Polymer UI] Add error popups for file operation failures

---

sources/web/datalab/polymer/components/datalab-editor/datalab-editor.html
sources/web/datalab/polymer/components/datalab-editor/datalab-editor.ts
sources/web/datalab/polymer/modules/ApiManager.ts

For now, this only works with files that open in the editor, not new files.

[Polymer UI] Save functionality for editor

---

containers/base/Dockerfile
containers/base/Dockerfile.py2
third_party/license.txt

- Update Scikit-learn. 
- Add LIME (used for ML feature sensitivity analysis) package.
- Update TF for PY3.

Update base image. 

---

sources/web/datalab/polymer/components/datalab-data/datalab-data.html
sources/web/datalab/polymer/components/datalab-data/datalab-data.ts

[Data First] Styling search box

---

sources/web/datalab/polymer/components/directory-picker-dialog/directory-picker-dialog.html

Fix files element taking up more than max height

---

sources/web/datalab/settings.ts

This PR directs debugging messages in settings.ts to go through the logger if that has been initialized. This reduces the noise on the output when the log level is set to less verbose than "debug".

Route settings debug messages through logger when available.

---

sources/web/datalab/polymer/components/base-dialog/base-dialog.html
sources/web/datalab/polymer/components/datalab-editor/datalab-editor.html
sources/web/datalab/polymer/components/datalab-editor/datalab-editor.ts
sources/web/datalab/polymer/editor.ts

Used async/await in more places to make the code clearer.

Editor Rename Functionality

---

sources/web/datalab/static/idle-timeout.js

Add note about saved notebooks to idle timeout message.

---

sources/web/datalab/polymer/components/datalab-editor/datalab-editor.html
sources/web/datalab/polymer/components/datalab-editor/datalab-editor.ts
sources/web/datalab/polymer/components/details-pane/details-pane.ts
sources/web/datalab/polymer/components/directory-picker-dialog/directory-picker-dialog.ts
sources/web/datalab/polymer/components/file-browser/file-browser.html
sources/web/datalab/polymer/components/file-browser/file-browser.ts
sources/web/datalab/polymer/components/table-preview/table-preview.ts
sources/web/datalab/polymer/editor.ts
sources/web/datalab/polymer/modules/Utils.ts
sources/web/datalab/polymer/modules/bigquery-file-manager/bigquery-file-manager.ts
sources/web/datalab/polymer/modules/file-manager-factory/file-manager-factory.ts
sources/web/datalab/polymer/modules/file-manager/file-manager.ts
sources/web/datalab/polymer/modules/jupyter-file-manager/jupyter-file-manager.ts
sources/web/datalab/polymer/modules/template-manager/template-manager.ts
sources/web/datalab/polymer/test/file-browser-test.ts
sources/web/datalab/polymer/test/index.html

This PR refactors a few of the classes that we have so that we can work with multiple file services.

FileManager refactor to allow for using multiple file services

---

sources/web/datalab/polymer/modules/bigquery-file-manager/bigquery-file-manager.html
sources/web/datalab/polymer/modules/bigquery-file-manager/bigquery-file-manager.ts
sources/web/datalab/polymer/modules/file-manager/file-manager.ts
sources/web/datalab/polymer/modules/session-manager/session-manager.ts
sources/web/datalab/polymer/test/file-browser-test.ts

Also a couple other minor comment cleanups.

Fix BiqQueryFileManager after refactor.

---

sources/web/datalab/polymer/components/datalab-editor/datalab-editor.html
sources/web/datalab/polymer/components/datalab-editor/datalab-editor.ts

Also some css fixes for editor to use flex.

Editor download functionality

---

sources/web/datalab/polymer/modules/base-api-manager/base-api-manager.ts
sources/web/datalab/server.ts
sources/web/datalab/settings.ts
sources/web/datalab/static/settings.js

Trying to keep all `/api` requests to the VM interface only.

/api/settings -> _appsettings, _settings -> _usersettings

---

sources/web/datalab/polymer/components/notebook-preview/notebook-preview.ts
sources/web/datalab/polymer/modules/base-api-manager/base-api-manager.ts
sources/web/datalab/polymer/modules/drive-file-manager/drive-file-manager.ts
sources/web/datalab/polymer/modules/file-manager/file-manager.ts
sources/web/datalab/polymer/modules/gapi-manager/gapi-manager.html
sources/web/datalab/polymer/modules/gapi-manager/gapi-manager.ts
third_party/externs/ts/gapi/drive.d.ts

These APIs are used by the notebook preview as well as editor.

DriveFileManager get/getcontent APIs

---

sources/web/datalab/polymer/components/file-browser/file-browser.ts

This already works with DriveFileManager after filling out its pieces.

Enable upload for DriveFileManager

---

sources/web/datalab/polymer/modules/gapi-manager/gapi-manager.ts

I'm not sure if this will cause a re-auth for BigQuery, but I'll keep it for now.

Add GCP scope to default list

---

sources/web/datalab/polymer/components/datalab-toolbar/datalab-toolbar.html

Also add border to account menu.

Fix css typo

---

sources/web/datalab/polymer/components/datalab-sessions/datalab-sessions.ts
sources/web/datalab/polymer/modules/drive-file-manager/drive-file-manager.html
sources/web/datalab/polymer/modules/drive-file-manager/drive-file-manager.ts
sources/web/datalab/polymer/modules/jupyter-file-manager/jupyter-file-manager.ts
sources/web/datalab/polymer/modules/session-manager/session-manager.ts

This adds file running status for Drive file manager, and shows which kernel each session is using on the sessions page.

Drive file running status + show kernel on sessions page

---

sources/web/datalab/polymer/notebook.ts

Wait until the upload is complete and send an ack message back so the notebook editor can wait on the upload.

Wait on uploading user creds

---

sources/web/datalab/polymer/components/file-browser/file-browser.ts

This was breaking file upload on Drive.

Upload files as text instead of base64

---

containers/datalab/content/run.sh

It will fail on the git commands.

Don't setup-env if the home directory doesn't exist.

---

sources/web/datalab/polymer/components/datalab-app/datalab-app.html

This keeps it above the selected item in the sidebar.

Fix z-index for main content

---

sources/web/datalab/polymer/modules/api-manager/api-manager.ts

We need to be able to refresh this whenever the backend changes.

Don't cache basepath result in code

---

tools/cli/commands/connect.py

Opening another pull request ,since this request :
https://github.com/googledatalab/datalab/pull/1755
got closed unexpectedly
Addressed the flake changes suggested by @chmeyers  
Also ran flake8 test , everything seems fine.

Addressed the flake changes

---

sources/web/datalab/templates/nb.html

.. to toggle line numbers.
Fixes https://github.com/googledatalab/datalab/issues/1532.

Add 'l' keyboard shortcut to help pane

---

sources/web/datalab/polymer/bower.json
sources/web/datalab/polymer/components/inline-details-pane/inline-details-pane.ts
sources/web/datalab/polymer/components/notebook-preview/notebook-preview.html
sources/web/datalab/polymer/components/notebook-preview/notebook-preview.ts
sources/web/datalab/polymer/components/preview-pane/preview-pane.ts
sources/web/datalab/static/datalab.txt

We're discussing using markdown-it instead of marked, so I sent this PR even though we're not final on this.

Use markdown-it instead of marked

---

sources/web/datalab/polymer/components/base-dialog/base-dialog.html
sources/web/datalab/polymer/components/base-dialog/base-dialog.ts
sources/web/datalab/polymer/components/delete-dialog/delete-dialog.html
sources/web/datalab/polymer/components/delete-dialog/delete-dialog.ts
sources/web/datalab/polymer/components/file-browser/file-browser.html
sources/web/datalab/polymer/components/file-browser/file-browser.ts
sources/web/datalab/polymer/components/input-dialog/input-dialog.ts
sources/web/datalab/polymer/modules/utils/utils.ts

This is to avoid using `innerHTML` to populate the list of items to delete.

Use a delete-dialog element for deleting

---

containers/base/Dockerfile

It also suppresses a TF warning due to missing python-snappy.

Add python-snappy to image. TensorFlow uses it to speed up some ops. 

---

.travis.yml
sources/web/datalab/polymer/components/auth-panel/auth-panel.ts
sources/web/datalab/polymer/components/datalab-app/datalab-app.ts
sources/web/datalab/polymer/components/datalab-editor/datalab-editor.ts
sources/web/datalab/polymer/components/datalab-settings/datalab-settings.ts
sources/web/datalab/polymer/components/file-browser/file-browser.ts
sources/web/datalab/polymer/components/notebook-preview/notebook-preview.ts
sources/web/datalab/polymer/components/project-picker-dialog/project-picker-dialog.ts
sources/web/datalab/polymer/components/table-inline-details/table-inline-details.ts
sources/web/datalab/polymer/components/table-preview/table-preview.ts
sources/web/datalab/polymer/components/text-preview/text-preview.ts
sources/web/datalab/polymer/components/timeout-panel/timeout-panel.ts

This fixes the typescript lint errors that we got with typescript 2.6.1 and comments out the travis build step that is hanging.

Fixing the build typescript and test hanging issues

---

sources/web/datalab/polymer/modules/github-file-manager/github-file-manager.ts

The content API has a 1MB limit, while the Blob API goes up to 100MB.
The Blob API urls are conveniently returned by the content API call on the parent directory.

Use the Git Blob API to download notebooks.

---

sources/web/datalab/polymer/components/file-browser/file-browser.html
sources/web/datalab/polymer/package.json
sources/web/datalab/polymer/test/file-browser-test.ts
sources/web/datalab/polymer/test/test-utils.ts

This also adds a new handy test utility that waits until a given condition evaluates to true.

CreateNewItem tests

---

sources/web/datalab/polymer/modules/drive-file-manager/drive-file-manager.ts
sources/web/datalab/polymer/modules/github-file-manager/github-file-manager.ts

Fixes a couple of comments missed in #1810.

Fix a couple of comments.

---

sources/web/datalab/polymer/components/file-browser/file-browser.ts
sources/web/datalab/polymer/modules/bigquery-file-manager/bigquery-file-manager.ts
sources/web/datalab/polymer/modules/drive-file-manager/drive-file-manager.ts
sources/web/datalab/polymer/modules/file-manager/file-manager.ts
sources/web/datalab/polymer/modules/github-file-manager/github-file-manager.ts
sources/web/datalab/polymer/modules/jupyter-file-manager/jupyter-file-manager.ts
sources/web/datalab/polymer/test/file-browser-test.ts

This PR is only a name change, changing all instances of "pathHistory" (including longer names containing that phrase) to "pathFileHierarchy" to correctly describe what that data is.
There are no functional or other changes in this PR besides that name change.

Rename pathHistory to pathFileHierarchy.

---

sources/web/datalab/polymer/components/file-browser/file-browser.ts
sources/web/datalab/polymer/modules/bigquery-file-manager/bigquery-file-manager.ts
sources/web/datalab/polymer/modules/drive-file-manager/drive-file-manager.ts
sources/web/datalab/polymer/modules/file-manager/file-manager.ts
sources/web/datalab/polymer/modules/github-file-manager/github-file-manager.ts
sources/web/datalab/polymer/modules/jupyter-file-manager/jupyter-file-manager.ts
sources/web/datalab/polymer/test/file-browser-test.ts

This PR only changes pathToHierarchy to be an async function, but does not make any functional changes. This paves the way for some bug fixes.

Make pathToFileHierarchy async.

---

sources/web/datalab/polymer/components/table-inline-details/table-inline-details.html
sources/web/datalab/polymer/components/table-inline-details/table-inline-details.ts

Don't attempt to load a preview for Views.

---

sources/web/datalab/polymer/components/file-browser/file-browser.ts
sources/web/datalab/polymer/modules/bigquery-file-manager/bigquery-file-manager.ts
sources/web/datalab/polymer/modules/file-manager/file-manager.ts
sources/web/datalab/polymer/modules/jupyter-file-manager/jupyter-file-manager.ts
sources/web/datalab/polymer/notebook.ts

The v2 editor expects a different url from v1. Also, it uses the iframe messages to save and rename notebooks.

Support opening local disk files in v2 editor

---

sources/web/datalab/polymer/components/datalab-terminal/websocket.ts

The changes are mostly whitespace. Add `w=1` to queryparams.

Add auth header to terminal socket.io requests

---

sources/web/datalab/static/datalab.css

Fixes https://github.com/googledatalab/datalab/issues/1063.

Fix mini toolbar crop css issue

---

containers/base/Dockerfile
containers/base/Dockerfile.gpu
containers/base/config/nbconvert.py
containers/base/config/py2-kernel-startup.sh
containers/base/config/py2-kernel.json
containers/base/config/py3-kernel-startup.sh
containers/base/config/py3-kernel.json
containers/datalab/content/run.sh
sources/web/datalab/config/settings.json
sources/web/datalab/static.ts
test/notebook/test_spec.js

Some packages remain installed via pip because they are either not available or not
up-to-date in the Conda repositories.
Also updates some Python packages and does a bit of cleaning in the Dockerfile.

Migrate Docker Container to Conda

---

containers/datalab/content/GCSbackup.sh

This fixes #1960
That bug appears to be caused by the zip command encountering what
looks like a socket file under the `/content/.forever` directory,
trying to add it to the archive, and then failing. Since the
zip command reported a failure, the GCSBackup.sh script then
exits without deleting the locally-created archive.
As such, there seem to be two bugs at play here:
1. The `zip` command fails when processing the `.forever` dir.
2. If the `zip` command reports an error, we do not delete the
temporary archive even if it was partially created.
This change fixes that by making two changes:
1. Excluding the `.forever` directory from the zip file
2. Setting up a `trap` command to delete the temp directory as
soon as that directory has been created.

Fix a leak in the GCS Backup utility.

---

containers/datalab/content/setup-env.sh
containers/gateway/content/run.sh

Ensures the 'jupyter kernelgateway' call is made within Conda env

---

containers/base/Dockerfile

and also updates scikit-learn (->0.19.1) and statsmodel (->0.8.0) to satisfy new dependencies

Updates numpy to 1.14

---

containers/base/Dockerfile

Also aliasing pip3 to pip for the python 3 environment.

 Use the pip version of h5py instead of the conda version

---

sources/web/datalab/polymer/notebook.ts
sources/web/datalab/polymer/test/settings-manager-test.ts

Fix Typescript errors TS2531 & TS2721

---

tools/release/cloudbuild.yaml
tools/release/version-issues.js

This change adds the 'version-issues.js' contents to the source
repository, and configures our cloud builder config to update
it in Google Cloud Storage on every push to the master branch.
The initial list of issues checked in includes the currently served
one with the addition of the issue about GPU instances not working
with the older NVIDIA driver.

Track the known version issues in the source control history.

---

containers/base/Dockerfile

This is necessary for the ML-toolbox library to work

Pin the version of dask and upgrade tornado

---

tools/cli/tests/end-to-end.py

This change modifies the CLI integration test in two ways
to try to reduce test flakiness:
1. If picking a random zone, use a different zone for each test. This
means that if a particular zone has an issue, we do not limit
ourselves to that zone that we've picked.
2. Retry the test suite up to 3 times in case it fails.

Try to make the CLI integration tests more reliable.

---

containers/base/Dockerfile
third_party/license.txt

@yebrahim @nikhilk @ojarjur 
Added Jupyter Code highlighter extension to highlight the selected word
https://github.com/jcb91/jupyter_highlight_selected_word
It highlights the current selected word.
I have added and enabled the extension in DockerFile.I also added the BSD license for the same in license.txt
I also built the image for the same and checked how its working 
Its working fine as seen in the below screenshot
Let me know if anything needs to be done :)

Added word highlighter jupyter in the DockerFile to highlight the selected word

---

sources/web/datalab/templates/edit.html

Fixes jquery-ui import for 'edit' page

---

tools/cli/commands/create.py

This creates a new flag --no-firewall-rule which disables firewall rule creation. fixes #2126

Added --no-firewall-rule
