googledatalab/datalab

- sources/web/datalab/static/datalab.js
The original save was replaced by a new version to work around an issue
with workspace sync. However, the new version does not return the wrapped
return value, so places where we chain off that future (e.g. with calls to
then()) got broken. This means, for example, that 'Convert to HTML' will
fail if the notebook has unsaved changes.
> Fix a bug in saving notebooks.

- sources/lib/api/gcp/bigquery/_api.py
Jobs should run as my current project, unless specified.
My datalab project is the one that should be used for running the queries, even if I have a destination table in a different project.
The destination table project needs to give me permissions to write into their dataset, but the query should be charged to the authenticated project.
Note that project_id is parsed a second time later in this method - there are 2 project ids, and they should be allowed to be independent.
> Jobs should run as my current project, unless specified

- sources/lib/api/tests/bq_api_tests.py
This test was broken (correctly) as we made a change recently to fix an
issue where if we were querying a table with a different project we
used that project to run the query. When the bug was fixed the test
was updated to reflect the correct behavior.
> Fix a test.

- sources/web/datalab/static/datalab.js
If the user makes a copy of a notebook, and that notebook is in the
datalab folder, make the copy in the root.
> Don't make notebook copies under datalab path.

- sources/lib/api/gcp/bigquery/_parser.py
- sources/lib/api/tests/bq_parser_tests.py
We were expecting a list of values, but we get a list of dictionaries with each containing a single value keyed on 'v'.
> Fix a bug in the parsing of records with repeated scalar fields.

- sources/lib/api/gcp/bigquery/_api.py
- sources/lib/api/gcp/bigquery/_query.py
- sources/lib/api/gcp/bigquery/_query_results_table.py
- sources/lib/api/gcp/bigquery/_udf.py
- sources/lib/api/gcp/data/__init__.py
- sources/lib/api/gcp/data/_sql_module.py
- sources/lib/api/gcp/data/_sql_statement.py
- sources/lib/api/gcp/storage/_item.py
- sources/lib/api/tests/bq_api_tests.py
- sources/lib/api/tests/bq_query_tests.py
- sources/lib/api/tests/bq_udf_tests.py
- sources/lib/api/tests/sql_tests.py
- sources/lib/datalab/gcp/datalab/_bigquery.py
- sources/lib/datalab/tests/bigquery_tests.py
- sources/web/datalab/workspaceManager.ts
Query.export calls Table.export. The latter blocks waiting for the Job
to complete and returns the Job. Query.export then calls wait() on the
Job too; this is benign but unneccessary. Simplifying the code.
> Fix a minor inefficiency.

- sources/lib/api/gcp/bigquery/__init__.py
- sources/lib/api/gcp/bigquery/_api.py
- sources/lib/api/gcp/bigquery/_csv_options.py
- sources/lib/api/gcp/bigquery/_federated_table.py
- sources/lib/api/gcp/bigquery/_query.py
- sources/lib/api/gcp/bigquery/_schema.py
- sources/lib/api/gcp/bigquery/_table.py
- sources/lib/api/gcp/data/_sql_module.py
- sources/lib/api/gcp/storage/_item.py
- sources/lib/api/tests/bq_federated_table_tests.py
- sources/lib/api/tests/bq_table_tests.py
- sources/lib/api/tests/bq_view_tests.py
- sources/lib/api/tests/main.py
We leverage the new external tables for loading data from GCS too.
You can now do ExternalTable.load(BQTable). We may want to deprecate
the old Table.load API or make it take an ExternalTable argument to
have a symmetrical Table.load(ExternalTable).
Arguably the naming should be different - ExternalTable.load should
maybe be called ExternalTable.import?
> Support for querying from external tables.

- containers/datalab/Dockerfile.in
- sources/web/datalab/workspaceManager.ts
wsync 0.4.0 changes the following:
1. Support -username and -email flags to avoid the "Rand Om Hacker" name show up in Dev console.
2. Require a workspace name appended in "wsync sync" command.
3. "-repo" needs to be replaced with "-workdir".
All the above were confirmed with wsync owner.
> workspace update --- use new version of wsync

- sources/web/datalab/static/datalab.css
Change the CSS so that if the user has a browser of insufficient width we will
expand the toolbar to multiple lines as necessary instead of the toolbar items
disappearing.
Issue #713
> Handle limited width browser experience better.

- sources/web/datalab/static/datalab.css
I didn't notice when testing this that this results in a toolbar that can be scrolled
out of view if the notebook is longer than will fit in the browser window. That is
pretty undesirable behavior, so reverting for now and will investigate a different
fix.
> Revert the CSS toolbar overflow changes.

- sources/lib/datalab/gcp/datalab/_bigquery.py
- sources/lib/datalab/gcp/datalab/_chart.py
- sources/lib/datalab/gcp/datalab/_utils.py
- sources/lib/datalab/tests/bigquery_tests.py
- sources/lib/datalab/tests/chart_tests.py
- sources/web/datalab/static/extensions/charting.css
- sources/web/datalab/static/extensions/charting.js
One of the complaints we have had from users is the lack of support for Jupyter widgets.
This change addresses some of that limitation by allowing the variables in %%sql modules
that are displayed with %%chart to include simple dynamic controls which will re-execute
the query with the new values when changed (with client-side caching of past results).
This is controlled via the YAML chart options, in a 'variables' section. There are five
types of controls supported, 'text' (textbox), 'set' (checkbox group), 'picker' (dropdown
allowing a single value), 'slider' (combined slider/textbox for numeric value with
min/max/step parameters), and 'boolean' (a checkbox for a Boolean value).
Each can have an optional 'label' property that defaults to the variable name, and a
'value' property to set …
> A simple alternative to widgets.

- sources/lib/datalab/gcp/datalab/_chart.py
- sources/web/datalab/static/extensions/charting.js
Specifically:
- controls are shown but disabled when converting to HTML
- PNG static charts are dynamically removed in converted HTML when the chart is redrawn
The code to do the latter previously relied on the IPython JS APIs being present; it
now falls back to a pure DOM approach if necessary.
Fix the static chart removal so it works when not running under IPython.
> Changes to get controls and static charts to play together nicely.

- sources/lib/api/gcp/bigquery/_api.py
- sources/lib/api/tests/bq_api_tests.py
BQ is now rejecting Table loads of non-CSV files if CSV options are
specified. We would supply these regardless of the source format, so
this change only adds these arguments to the configuration if the
sourece format is CSV.
Issue #748
> CSV load fix

- containers/datalab/content/setup-repo.sh
not, a deployment does not recreate "datalab" branch.
> Fix an issue that when "datalab" branch is deleted but "datalab_main" is

- docs/Makefile
Use 'make prepublish' first time, then 'make publish' each time there
are changes that should be published.
> Changes to docs makefile to better support publishing docs to github.

- sources/lib/datalab/datalab/bigquery/commands/_bigquery.py
- sources/lib/datalab/datalab/context/_utils.py
- sources/lib/datalab/datalab/kernel/__init__.py
- sources/lib/datalab/datalab/notebook/static/charting.ts
- sources/lib/datalab/datalab/storage/commands/_storage.py
- sources/lib/datalab/datalab/utils/_http.py
- sources/lib/datalab/datalab/utils/_job.py
- sources/lib/datalab/tests/kernel/bigquery_tests.py
- sources/lib/datalab/tests/kernel/chart_data_tests.py
- sources/lib/datalab/tests/kernel/chart_tests.py
- sources/lib/datalab/tests/kernel/commands_tests.py
- sources/lib/datalab/tests/kernel/html_tests.py
- sources/lib/datalab/tests/kernel/module_tests.py
- sources/lib/datalab/tests/kernel/sql_tests.py
- sources/lib/datalab/tests/kernel/storage_tests.py
- sources/lib/datalab/tests/kernel/utils_tests.py
- sources/lib/datalab/tests/storage/bucket_tests.py
- sources/lib/datalab/tests/storage/item_tests.py
- sources/web/datalab/auth.ts
- sources/web/datalab/jupyter.ts
- sources/web/datalab/server.ts
- sources/web/datalab/static/datalab.js
- sources/web/datalab/templates/tree.html
Added a sign in button to the tree view instead of forcing auth on first request. Users can now use Datalab without signing in to Google (but signing in is needed before any GCP stuff can be used).
We probably want to change the button/icon to make it more obvious but at least the functionality
is there.
Fixed a couple of regressions that came in the big refactoring change before.
Fixed a bunch of imports in tests.
Folded in PR https://github.com/GoogleCloudPlatform/datalab/pull/815 as it was easier to do this one liner here than try to merge it with all the other changes.
> Make signing in to Google optional.

- containers/datalab/Dockerfile-extended-example.in
- containers/datalab/custom-packages-example.txt
- containers/datalab/run-extended.sh
A first implementation to enable installation of custom python packages as part of the datalab image build script as described in #826 . 
If the file `'custompackages.txt'` exists in `'$REPO_DIR/containers/datalab'`, then install the python packages listed in the file.
Here is an example of the contents of custompackages.txt:
```
xlrd
```
We could easily modify this PR to also append a command that executes a more flexible install script (*.sh) to the Dockerfile, if the *.sh script exists.
Feedback is welcome.
> Add ability to create and run a customized image derived from the datalab image

- containers/datalab/Dockerfile.in
The command that does a wildcard copy of files into the nbconvert
directory needs to include the contents of the `codemirror`
subdirectory. Failing to include the "-R" flag was causing that
copy to fail with an error message that the subdirectory was being
ignored.
This change fixes that by adding the required "-R" flag.
> Fix a build failure that was triggered by `cp` skipping a directory.

- containers/datalab/content/run-debug.sh
- containers/datalab/content/run.sh
- containers/datalab/run-extended.sh
Change the Docker extensibility script to use datalab:local instead of
datalab:latest for now.
> Add support for a customization script in mapped-in volume.

- sources/web/datalab/static/datalab.css
The nav-bar in the datalab UI does not layout cleanly if the width of
the page is less than ~1200 pixels. It would require quite a bit of
work to make the UI scale down to smaller than that size (e.g. by
switching the nav-bar to be a drop-down menu), so as a work-around
we will set the min-width of the body to be the smallest window
size we currently support.
With this change, if a user opens datalab in a browser window that
is smaller than our min-width, then the browser will render the
page at the min width, and will show the user a scroll bar to
move the window over that page.
This fixes (or, at least, mitigates) #713
> Set the min-width of the HTML body tag to be the smallest we support.

- containers/datalab/content/run.sh
- sources/web/datalab/auth.ts
- sources/web/datalab/server.ts
The first issue was around the creation of the .config directory.
We had code in multiple places that tried to create it, and in one
of those cases it tried to create that directory repeatedly, resulting
in failure messages in the logs after the first attempt.
This change fixes that by making sure that only the EULA accepted
handler creates that directory, and only in the case that it does
not already exist.
The other issue was the OAuth callback handler, which did not make
sure the OAuth client instance existed before attempting to use it.
This change fixes that by adding that check.
> Fix two issues that prevented logging in from a local instance.

- containers/datalab/config/nbconvert.py
The issue was that when you tried to convert a notebook to python,
the server returned a cryptic error message with the name of the
default HTML template.
The root cause was that when we set the 'template_file' config
variable for exporting to HTML, we did so for *every* exporter,
and not just the HTMLExporter.
This change fixes that by only setting that config variable on
the HTMLExporter.
> Fix a bug in the 'Convert to Python' functionality.

- sources/lib/datalab/datalab/context/_context.py
- sources/lib/datalab/datalab/context/commands/_projects.py
A number of the datalab libraries require either:
1. Explicitly passing in a Context object with a project_id set
or
2. Setting the project_id in the default Context instance.
When neither of those were done, the subsequent API calls
could fail with very confusing error messages (such as "Not found").
This changes the libraries so that an error is surfaced earlier,
with an explicit explanation of what has gone wrong, and with
instructions on how to fix the issue.
Specifically, attempts to read the 'project_id' property of
a Context object will raise an error if that property has not
been set. The error message will explain that the 'project_id'
has not been set, and will suggest using the '%projects set'
cell magic to set a default project.
This change also fixes the '%projects set' cell …
> Improve the visibility around setting a default project.

- sources/web/datalab/jupyter.ts
- sources/web/datalab/templates/nb.html
There are some sample notebooks which require credentials to run
(because they call into external APIs). If you try to run those
notebooks while signed out, then they will produce an error
message helpfully suggesting that you sign.
However, the sign-in button was only being shown on the tree-view
page and not on the notebook-view page.
This meant that you had to navigate back to the tree-view page,
sign in, and then go back to the notebook to retry running the
code.
This change fixes that by adding the sign-in/sign-out buttons
to the notebook-view page in the exact same place they appear
for the tree-view page.
> Add the sign-in/sign-out buttons to the notebooks UI.

- sources/web/datalab/static/datalab.js
This change makes the sign in/out buttons save any changes to the
current notebook (if we are on a notebook page) before redirecting
the user.
This prevents users accidentally losing unsaved work if they try
to sign-in from the notebook view page.
This fixes a potential issue reported by @gramster on #877
> Make the signin/signout buttons save notebook changes.

- sources/web/datalab/jupyter.ts
- sources/web/datalab/static/datalab.css
- sources/web/datalab/static/datalab.js
- sources/web/datalab/templates/edit.html
We previously were serving the file editing page using the
built-in Jupyter UI. That meant that it looked wildly different
from the rest of Datalab, and was missing the Datalab-specific
UI elements like the sign-in and feedback buttons.
This version of the editor page is functional, but not yet
feature complete. The remaining missing features will be added
in later commits.
> Add a new template for the file editing page.

- sources/web/datalab/jupyter.ts
PR #880 introduced a bug in the template rendering for the notebook
UI where the name of the template was wrong (`notebook` instead of
`nb`).
This change fixes that.
> Fix a bug in the template serving.

- containers/datalab/Dockerfile.in
- containers/datalab/content/run.sh
- containers/datalab/content/setup-env.sh
- containers/datalab/run-extended.sh
- containers/datalab/run.sh
- sources/web/datalab/jupyter.ts
This change allows Datalab to use a [kernel gateway](https://github.com/jupyter/kernel_gateway) for running the notebook kernels.
The setting for whether or not to use a gateway is based on the `KG_URL` environment variable, which defines the URL of the gateway (if any) to use.
If that environment variable is set, then *all* kernels are run using that gateway. Otherwise, all kernels are run locally within the Datalab container.
For example:
KG_URL=http://localhost:8080 ./containers/datalab/run.sh
will run Datalab with all kernels being run by a kernel gateway running on localhost:8080.
... whereas:
./containers/datalab/run.sh
will run Datalab will all kernels running inside of the Datalab container.
Note: This uses the [nb2kg server …
> Add support for connecting to a kernel gateway.

- externs/ts/node/tcp-port-used.d.ts
- sources/web/datalab/jupyter.ts
Previously, Datalab was picking the next port that it wanted Jupyter
to run on, passing that to the launched Jupyter process using the
'--port' flag, and then assuming that the server did in fact start
listening on that port.
However, if the port selected was already in use, then Jupyter would
automatically try the next port in sequence. That could cause an issue
where the one Jupyter server (for one user) was listening on a port
that we thought was being used by the Jupyter server for a different
user.
This change fixes that bug by doing the following:
1. Verifying that the next port is free before we try to start a
Jupyter server listening on it.
2. Telling the Jupyter server to not try any additional ports if
the one specified was not available (so it will instead die in
that …
> Fix a bug in the port selection for the nested Jupyter servers.

- externs/ts/node/tcp-port-used.d.ts
- sources/web/datalab/jupyter.ts
Previously, the logic was just to increment the next port number,
and then try to launch a Jupyter server on that port if it was
free. If that failed at any step, then we would retry, but with
a counter for the max number of retries decremented.
This meant that the next port already being in use counted against
the retry count, and that should not be the case.
With this change, the search for a free port will not count against
the the retry count.
> Change the logic for picking the next Jupyter port more intelligent.

- sources/web/datalab/jupyter.ts
This change makes the Datalab NodeJS server, at startup, list
all processes for the 'jupyter-notebook' binary, and kill them.
This fixes #892, where those processes could become abandoned
if the NodeJS server gets restarted.
This should be a safe thing to do at startup, as the NodeJS
server only runs inside of a Docker container, and so it has
an isolated process space.
I.E. the only processes that should be killed are those that
were started by an earlier incarnation of the NodeJS server.
> Make the Datalab server kill abandoned Jupyter servers.

- sources/web/datalab/templates/nb.html
- sources/web/datalab/templates/tree.html
Both the notebook and tree-view HTML templates have
some attribute values specified with too many closing
quotes (e.g. `class="btn""`).
This does not seem to have affected the rendering of those
pages, but it was confusing the syntax-highlighting features
of some editors when displaying the HTML source.
This change fixes that by removing the duplicated closing quotes.
> Fix erroneous duplicated quotes in the HTML templates.

- sources/web/datalab/jupyter.ts
- sources/web/datalab/logging.ts
- sources/web/datalab/server.ts
This change should improve reliability and debugability in multiple ways:
1. Adding some important logging, including logging requests at
the time they are received rather than just at the time we
finish processing them. This enables us to distinguish
between a request that never made it to the server vs. one
that the server received but never finished processing.
2. Adding error handling (via logging) for exceptions thrown
by the main request handler.
3. Adding error handling (logging and invoking per-user callbacks)
for exceptions thrown during the setup process for the per-user
Jupyter servers.
> Improve error checking and logging.

- sources/web/datalab/jupyter.ts
- sources/web/datalab/server.ts
- sources/web/datalab/static/datalab.css
- sources/web/datalab/static/datalab.js
- sources/web/datalab/templates/edit.html
- sources/web/datalab/templates/nb.html
- sources/web/datalab/templates/sessions.html
Previously, the `tree` UI included two unrelated views; a directory
view of the file system, and a list view of running sessions.
This was confusing as it was not intuitive that you should open
the file listing in order to be able to switch to the session
list, nor was it obvious that the UI controls on that page
toggled the type of view that was presented.
This change tries to clean all of that up by splitting the
session listing into its own page, and putting a link to that
page in the button toolbar that is in the top, right-hand
corner of the UI.
> Split the `sessions` UI out into its own page.

- containers/datalab/Dockerfile.in
The repository 'googledatalab/datalab' is being renamed as
'googledatalab/pydatalab' so that this repository can be
migrated to the 'googledatalab' organization.
This change is necessary for the building of the Docker image
to pick up the library from its new location.
> Update the reference to the datalab python libraries.

- containers/datalab/run-with-gce.sh
- containers/gateway/deploy.sh
This change adds to new scripts that make it easy to run the Datalab UI
locally while connecting it to a kernel gateway running inside a GCE VM.
Specifically, the two new scripts are:
1. containers/gateway/deploy.sh - for setting up the kernel gateway.
2. containers/gateway/run-with-gce.sh - for running the Datalab UI.
The main entry point for a user wanting to run their kernels in the
cloud will be the 'run-with-gce.sh' script, which will run the
'deploy.sh' script iff there isn't already a VM running a kernel gateway.
> Add scripts for running Datalab in a split setup.

- containers/datalab/run-with-gce.sh
There was a bug in the initial checkin for the 'run-with-gce.sh' script
where, if specified on the command line, the selected project and zone
would not be passed to the nested call to the 'deploy.sh' script.
This was because the call to 'deploy.sh' always used the default values
configured with gcloud, so if those differed from the explicitly-passed
values, then the deploy script would try to use the wrong project
and/or zone.
This change fixes that bug by having the project and zone always be
explicitly passed to the call to the 'deploy.sh' script.
> Fix a bug when specifying a project and zone via command line arguments.

- containers/gateway/deploy.sh
This change makes the 'containers/gateway/deploy.sh' script set up the
gateway VM in such a way that the Docker logs for the kernel gateway
container get imported into the GCP logging service.
> Add support for writing logs to GCP logging

- containers/gcp/Dockerfile
- containers/gcp/README.md
- containers/gcp/build.sh
- containers/gcp/content/deploy.sh
- containers/gcp/content/run-with-gce.sh
- containers/gcp/run.sh
This encapsulates all of the logic for spinning up a GCE
VM running a Datalab kernel gateway, setting up an SSH
tunnel connected to that VM, and then running a local
Datalab instance pointed at that SSH tunnel.
This should make it much simpler to run Datalab with kernels in the cloud.
> Add a new Docker image for running with a backend on GCP.

- containers/gcp/content/deploy.sh
- containers/gcp/content/run-with-gce.sh
- containers/gcp/run.sh
This change is a response to feedback about the previous steps
being too complicated and/or brittle. The aim of this is to
make the end-user instructions for Datalab-on-GCP as simple as
possible.
Specifically, the following improvements are included:
1. Remove all dependencies on 'gcloud' from the setup and run.
This has the consequence of the user potentially having to
sign-in to gcloud a second time if they have already signed
in to it from the host, but that sign-in is persisted, so
they will only have to do it one more time.
2. Make the PROJECT_ID and ZONE variables optional rather than
required. If they are not provided, then the user will be
prompted to enter them at the command line. Either way, the
values selected will be persisted so they can be reused by
later runs of the tool. …
> Simplify the run step for Datalab with a kernel gateway in GCP.

- containers/gateway/content/run.sh
Fixes #924
```
>tony@tonypc:~/Git/datalab-parthea/containers/gateway$ jupyter kernelgateway --help-all
...
...
JupyterWebsocketPersonality options
-----------------------------------
--JupyterWebsocketPersonality.list_kernels=<Bool>
Default: False
Permits listing of the running kernels using API endpoints /api/kernels and
/api/sessions (KG_LIST_KERNELS env var). Note: Jupyter Notebook allows this
by default but kernel gateway does not.
```
> Update Jupyter Gateway setting to JupyterWebsocketPersonality.list_kernels

- containers/datalab/content/deploy.sh
By default, any containers in a Pod that have a port spec will
be exposed on those ports for all network interfaces. However,
for our kernel gateway VMs we only want the kernel gateway to
be accessible via localhost (and will use an SSH tunnel for
access from any other machine).
In order to make the container VM enforce that restriction we
need to add an explicit 'hostIP' line to the Pod spec specifying
that the container should only be accessible via the 127.0.0.1
IP address.
Since we were already placing the VM in a locked-down network,
this is an additional, rather than sole, defense.
This script will likely be deleted soon, but we should still
document the best practice for setting up these gateway VMs
in case anyone wants to copy the script from our git history.
> Add an additional layer of defense for deployed gateway VMs.

- containers/datalab/content/run-with-gce.sh
This was causing issues when running Datalab on Windows, as strange
issues seem to occur if you have your HOME variable set to an
externally mapped volume on Windows.
> Remove the setting of the HOME environment variable during setup.

- sources/web/datalab/jupyter.ts
This fixes a bug where the code did not properly handle the scenario
of the project being missing.
> Fix a bug in the project lookup.

- containers/datalab/content/setup-env.sh
container last time they use Datalab, then setting PROJECT_NUMBER env
var will fail and cause Datalab to not start.
> Fix an issue that when user is not signed in from inside datalab

- README.md
- sources/web/datalab/static/datalab.js
Update repository links in source code to point to https://github.com/googledatalab instead of https://github.com/GoogleCloudPlatform
> Update links to point to correct repository

- containers/datalab/content/run.sh
- sources/web/datalab/auth.ts
- sources/web/datalab/login.ts
This change allows the user to perform the OAuth flow to log in
to Datalab at startup via the web browser.
That, in turn, streamlines the user experience for running Datalab
with a backend in GCP. This is because the user may not be logged
in initially, but we need them to be logged in before we can create
an SSH tunnel connected to their VM.
Previously, we satisfied that requirement by using the 'gcloud auth
login' flow from the command line, but that is cumbersome. With this
change that flow is now performed using the browser, which makes
it less cumbersome.
> Remove the need to login from the command line

- containers/datalab/content/run.sh
- sources/web/datalab/jupyter.ts
This change turns on Jupyter's notebook notary feature using
a secret read from a file on the user's machine (which we
automatically generate if it is missing).
This has the consequence that certain types of charts saved in
cell outputs will not be displayed until the user (re)runs the
corresponding cells.
> Enable the notebook notary feature.

- containers/datalab/content/run.sh
- containers/datalab/content/setup-env.sh
The `run.sh` script, at startup, calls the `setup-env.sh` script
to setup basic environment variables.
However, the logic in those two scripts had evolved over time and
some environment variables were being reference before they were
set, causing the kernel-gateway feature to silently fail (all
operations would run on the local machine).
This change fixes that by changing the `setup-env.sh` script to
only set environment variables that can be determined at the
beginning of the container's existence without any other setup
having been performed.
> Fix ordering issues in startup environment settings

- sources/web/datalab/settings.ts
- sources/web/datalab/static.ts
- sources/web/datalab/static/dark.css
- sources/web/datalab/static/datalab.css
- sources/web/datalab/static/light.css
- sources/web/datalab/templates/edit.html
- sources/web/datalab/templates/nb.html
- sources/web/datalab/templates/sessions.html
- sources/web/datalab/templates/tree.html
This adds a new user setting called 'theme' that can be set to
one of 'light', 'dark', or 'custom'.
Both 'light' and 'dark' are canned themes with 'light' matching the
existing Datalab style, and 'dark' modifying that theme to have
dark backgrounds rather than light ones.
The 'custom' setting is for using a user-specified CSS file stored
in the 'datalab/.config' directory named 'custom.css'.
This change does not incorporate a UI for modifying the theme
setting, but the user can change it by directly modifying the
'datalab/.config/settings.json' file.
The canned dark theme still needs some work.
> Initial support for custom themes

- containers/datalab/content/run.sh
By default, everything inside of the Docker container runs as the user
'root'. Previously, we were setting up the SSH tunnel, we defaulted to
the user inside the VM matching the user inside the Docker
container. However, 'root' is special, and some VM images do not allow
SSH-ing as that user.
For example, this prevented the Datalab image from being able to connect
to a kernel gateway running inside of a Google Dataproc cluster.
This change fixes that be making the username inside of the VM match
the username of the logged-in account (e.g. "<username>@gmail.com").
> Create the SSH tunnel as the logged in user rather than root.

- containers/datalab/content/run.sh
Pull request #941 fixed a bug where our attempt to lookup the project
number would fail if the user was not signed in. However, that is just
a special case of the more general issue of not being able to look
up the project number.
We have seen reports of at least one other instance of this issue,
which is the case that a user is signed in but is not a project owner.
In that case, the check that the user is signed in will succeed, but
the attempt to lookup the project number will fail, causing the
Datalab startup to terminate.
This change fixes that by modifying the check to be more general.
Instead of checking if we believe that the lookup will succeed, we
try the lookup and gracefully handle any errors that occurred.
> Fix a bug in looking up the project number.

- containers/base/Dockerfile
The GNU project lists multiple mirrors for their source code and asks on their
site that one of the mirrors be used for downloading rather than reading
directly from their FTP server.
This change switches us from downloading directly from the GNU FTP server to
instead pulling from the first HTTP-based mirror listed in the US on this
site: https://www.gnu.org/prep/ftp.en.html
> Pull the GCC source code from a mirror instead of FTP.

- containers/datalab/Dockerfile.in
- containers/datalab/content/run.sh
Previous versions of Datalab would trigger a CLI based OAuth flow at
startup if they needed the user's credentials to set up a connection
with the backend in a GCE VM.
We recently replaced that with a web-based OAuth flow that mimiced the
sign-in button in the Datalab UI.
However, both that login flow at startup and the sign-in button in the
UI require that the UI be accessed via the hostname 'localhost'.
That is not sufficient for the case of someone wanting to run Datalab
inside of the Google Cloud Shell. In that environment the user can still
access port 8081 via the "Web preview" feature, and that access is still
secure (since only that user can access it), but the hostname will
not be 'localhost'.
This change adds support for that use case by adding a "CLI_LOGIN"
environment variable …
> Support logging in via the command line at startup.

- sources/web/datalab/static/datalab.css
This change fixes a usability issue with the display of code and data cells
where they would be displayed with a different amount of left-padding depending
on their state (unselected, selected, or edit-mode).
This fixes that issue by setting the left padding to always be 4 pixels
regardless of what state the cell is in.
> Make the left padding of cells consistent

- sources/web/datalab/jupyter.ts
- sources/web/datalab/package.json
- sources/web/datalab/server.ts
- sources/web/datalab/sockets.ts
- sources/web/datalab/static/datalab.js
- sources/web/datalab/templates/nb.html
Previously, Datalab proxied web-socket connections over HTTP, so that
it could run in App Engine Flex (which does not support websockets).
That code was removed when we transitioned to the locally-run setup,
as we did not think that it was necessary anymore.
However, even in the locally-run setup, a user may want to run in
an environment that does not support web-sockets. One such example
is users who want to run Datalab using Google's Cloud Shell Web
Preview feature (https://cloud.google.com/shell/docs/using-web-preview).
This change adds support for such environments by conditionally
proxying web sockets over HTTP based on an environment variable that
can be set by the user.
The code for this is just the old proxy code from the App Engine
Flex version of Datalab, but wrapped in checks …
> Support hosts that block websockets.

- sources/web/datalab/static/datalab.css
- sources/web/datalab/templates/nb.html
1. Remove some unnecessary and inconsistent shadows.
2. Remove space between the "Notebook" dropdown and the editing buttons.
> Cleanup the notebook view UI

- sources/web/datalab/settings.ts
This change extens the "_settings" endpoint so that it can be used
to fetch the current settings in addition to updating them.
The old behavior was:
If both 'key' and 'value' are specified, then update that
setting, otherwise return a 'bad-request' error.
The new behavior is:
If 'key' and 'value' are specified then update that setting...
Otherwise, if 'key' is specified then return the value of just
that one setting...
Otherwise, return the values of all the settings.
> Add an API for getting the current user settings.

- sources/web/datalab/static/dark.css
Fixed dark theme styling for generated chart svgs as well as some dataframe tables.
Fixes issue #964
> Fix table and chart styling on dark theme

- sources/web/datalab/static.ts
I think the issue has been there for a while. And my recent commit might have changed the js load sequence, which exposes the issue.
According to https://github.com/googledatalab/datalab/blob/master/sources/web/datalab/templates/tree.html#L170, when require(['custom'], function()..) is called, it will load '/custom.js', which will return 404. If the line is executed later, jupyter will load 'custom.js' from '/custom/custom.js', which is served correctly.
> Fix an issue that 'custom.js' cannot be loaded.

- sources/web/datalab/static.ts
- sources/web/datalab/static/appbar.html
- sources/web/datalab/static/datalab.css
- sources/web/datalab/static/datalab.js
- sources/web/datalab/templates/edit.html
- sources/web/datalab/templates/nb.html
- sources/web/datalab/templates/sessions.html
- sources/web/datalab/templates/tree.html
This change moves the appbar HTML into its own file and uses jquery to load it in each template, this lets us iterate changes on it more easily, but it also unifies the menu for all templates.
The change also moves the Samples and Tutorials button into a link under the help menu.
> Refactor appbar into a shared HTML component

- containers/base/Dockerfile
- containers/base/build.sh
- containers/datalab/build.sh
- containers/gateway/build.sh
(Sorry, I messed up the branch and then deleted it, so the comments are lost. But I think all of them are addressed).
Right now it is hard to make changes to pydatalab locally and then have datalab container picking it up, because it always git-clone pydatalab from repo. The change adds a mechanism (build.sh ) to optionally picking up pydatalab from a local directory.
> Flexible pydatalab

- sources/web/datalab/auth.ts
- sources/web/datalab/jupyter.ts
- sources/web/datalab/static/appbar.html
- sources/web/datalab/static/datalab.js
This change includes two improvements to the logic around logging in
and logging out:
1. Remove usage of the 'DATALAB_ENV' environment variable in the logic
for determining if the user is signed-in, and instead directly
query the 'gcloud' tool.
2. Remove the 'signout' button if the signed-in account is a service
account. This is for running the Datalab UI inside of a GCE VM
with a GCE service account. In that situation the service account
is tied to the VM and cannot be detatched, so the 'signout' button
did nothing in that case.
> Improve accuracy the login/logout logic

- sources/web/datalab/static/dark.css
Fixed markup cells that still kept a light background color.
> Fix dark theme for markup cells

- sources/web/datalab/static/datalab.css
Code/markup cells now only show a blue left border after they've been run.
> Removed 4px green padding on selected cells

- containers/datalab/content/run.sh
- sources/web/datalab/static/appbar.html
This change simplifies the `datalab/docs` directory in two ways:
1. Remove an unnecessary level of directory hierarchy, so that the
docs are now stored under `datalab/docs` instead of
`datalab/docs/notebooks`.
2. Perform a sparse checkout of the repo to only get the doc files
into the docs directory, rather than all of the repository
contents. The other files are still available to the user in the
cloned git history, but they are not in the working directory
by default.
> Clean up the docs directory

- sources/web/datalab/static/dark.css
- sources/web/datalab/static/datalab.js
Fixes #1001
Also corrected subtle issue in the Datalab new version message where left bracket was red and right bracket was the color of the link.
> Resolve issue where link in Datalab new version message is difficult to read

- sources/web/datalab/static/datalab.js
- sources/web/datalab/templates/edit.html
- sources/web/datalab/templates/nb.html
- sources/web/datalab/templates/sessions.html
- sources/web/datalab/templates/tree.html
The splitting out of the app bar into a single, reusable HTML file
introduced an unexpected timing issue where the Javascript code served
by the Jupyter notebook server was trying to modify DOM elements which
did not yet exist.
This change fixes that issue by ensuring that the app bar HTML is loaded
before the notebook server Javascript is loaded. Since the loading of
the app bar HTML requires JQuery, this required us to add JQuery as one
of the scripts loaded in each of the HTML templates.
This fixes #998
> Fix timing issues in the loading of the app bar

- sources/web/datalab/templates/nb.html
Closes #777 
The following keyboard shortcuts are no longer supported in [Jupyter Notebook 4.2](https://github.com/jupyter/notebook/blob/4.2.x/notebook/static/notebook/js/keyboardmanager.js):
- Ctrl+K - move cell up
- Ctrl+J - move cell down
I've confirmed that the other keyboard shortcuts documented in Datalab are still functional.
> Remove the keyboard shortcut to move cells up/down from the documentation

- sources/web/datalab/static/datalab.js
The fix is to check application/json response for kernel execution results first, and if not exist then plain/text ("plain/text" response was added for fetching project id).
> Fix issue #1005 by 

- sources/web/datalab/static/dark.css
> Resolve issue where input text is hard to read in dark theme

- run.sh
- sources/web/datalab/static/dark.css
- sources/web/datalab/static/datalab.css
- sources/web/datalab/static/datalab.js
This PR adds a small toolbar to the left of code cells that currently has only one button to collapse/uncollapse the cell. This works only with code cells. When collapsed, code cells show the first line of their input.
Fixes #1004
> Add code cell collapse/uncollapse toggle

- .gitignore
- containers/base/Dockerfile
- containers/datalab/build.sh
- sources/web/datalab/static/dark.css
- sources/web/datalab/static/datalab.css
- sources/web/datalab/static/datalab.js
- sources/web/datalab/static/light.css
- sources/web/datalab/templates/nb.html
- Use the latest version of ipywidgets (5.2.2)
- Add missing CSS and HTML elements for the widgets to work
- Some other fixes to get widgets working properly
- Hide/show widgets area when cells are collapsed
- Build datalab frontend as part of the docker build script
Fixes #843, #890, and #1012
Note: widgets are still not all styled properly for the dark theme, this isn't trivial to do since most of them are styled inline instead in stylesheets.
> Fix, update, and enable ipywidgets

- sources/web/datalab/static/datalab.css
- Added back missing padding at the top of the notebook list and session.
- Fixes this:
> Fix output line height and missing padding in appContent

- sources/web/datalab/static/datalab.css
- Remove extra top and bottom padding
- Fix height being set to greater than 100%
- Added missing line numbers in the text editor
Fixes #1024
> fix edit page height, padding, and missing line numbers

- containers/datalab/content/run.sh
> Don't fail Datalab startup if docs cloning fails

- containers/base/Dockerfile
- containers/datalab/Dockerfile.in
This change reshuffles the installation commands to make the docker image more space efficient, by doing the following:
- Merge all `apt-get install` commands into one long `RUN` statement
- Add clean up commands that remove packages not needed for the runtime, and deletes caches and unneeded man/doc/locale files
This brings down the size of the base image to about `1.5GB`, down from `2.5GB`. It's difficult to go below this and still keep all the installed libs we have.
Fixes #1025
> Reduce base docker image size

- containers/base/build.sh
- containers/datalab/build.sh
- containers/datalab/debug.sh
- containers/datalab/logs.sh
- containers/datalab/run-extended.sh
- containers/datalab/run.sh
- containers/datalab/stage.sh
- containers/gateway/build.sh
- containers/gateway/content/run.sh
- containers/gateway/content/setup-env.sh
- containers/gateway/run.sh
Use -e in all shell scripts to fail on error. Right now the build script doesn't stop on error, so running the `run.sh` command afterwards actually uses older images if any.
Fixes #989
> Fail on error in build scripts

- sources/web/datalab/static/datalab.css
- sources/web/datalab/static/datalab.js
Added more buttons to the minitoolbar and converted it to a dropdown menu with a hamburger button. The new options added are: code collapse, run, and clear cell. Hiding is done mostly in CSS, except for parts where JS code is needed (hiding ipywidgets).
> Add more buttons to cell minitoolbar: code collapse, run, and clear

- containers/base/Dockerfile
We use curl in certain scenarios to verify that the kernel gateway
is functioning and accessible, so it is required in some configurations.
It's also just a generally useful tool that most people will want
in their development environment.
This appears to have been the root cause of #1043
> Add curl back as a dependency in the base image.

- containers/datalab/Dockerfile.in
- containers/datalab/content/run.sh
- sources/web/datalab/reverseProxy.ts
- sources/web/datalab/static/appbar.html
- sources/web/datalab/static/datalab.js
- sources/web/datalab/static/datalab.txt
This PR adds [ungit](https://github.com/FredrikNoren/ungit) inside the datalab container. It runs on port 8083 inside the container, and gets its requests reverse proxied so only the one port used by datalab is open outside the container.
I added a git icon in the app bar to open ungit in the current location. It finds the current directory path and points ungit to it. Note that ungit will ignore any trailing subdirectories after the git root dir.
> Run ungit inside the datalab container

- tools/release/publish.sh
- tools/release/rollback.sh
The rollback relies on a 'previous' variable defined in the config_local.js file. This PR updates the publish script to put the current release as previous before publishing the new one. This way the rollback script can read the previous release version and copy its config_local.js to be the current one, and release its corresponding images as well.
> Added a release rollback script

- sources/web/datalab/common.d.ts
- sources/web/datalab/config/settings.json
- sources/web/datalab/jupyter.ts
This just adds a new config setting `nextJupyterPort` which is used as the
initial port used when searching for a free port, as opposed to it being
hardcoded as 9000.
PTAL @yebrahim @ojarjur @qimingj
> Make the port used by Jupyter configurable.

- sources/web/datalab/common.d.ts
- sources/web/datalab/config/settings.json
- sources/web/datalab/jupyter.ts
Add an allowOriginOverride config setting to workaround Datalab's default behavior of deleting the Access-Control-Allow-Origin that is sent back from Jupyter.  When this setting is overridden with another frontend's URL, that frontend will be able to make XHR requests to the Datalab frontend.
PTAL @yebrahim @ojarjur @qimingj
> Add an allowOriginOverride setting to override the Access-Control-Allow-Origin header

- sources/web/datalab/static/dark.css
- sources/web/datalab/static/datalab.css
- sources/web/datalab/static/datalab.js
- sources/web/datalab/templates/tree.html
This PR adds a button that appears when (exactly) one file is selected in the notebook list view, and opens a Jupyter editor for that file when clicked. Selecting no files, more than one file, or folders hides the button.
> Add 'Open as Text' Button in Toolbar

- sources/web/datalab/static/datalab.js
Ungit requires an unencoded path to open correctly.
> Fix ungit path

- sources/web/datalab/auth.ts
Provide a way to automatically close an auth window in case Datalab's /signin flow is loaded from a popup window.  Instead of referer=URL-TO-REDIRECT-TO, issue referer=popup.
PTAL @yebrahim @ojarjur @qimingj
> Automatically close auth windows loaded with "referer=popup"

- tools/gcsbackup/GCSbackup.sh
- tools/gcsbackup/README.md
Added a tool to backup a given directory on a GCloud VM to a given GCloud Storage bucket. The tool can tag the archive with a string to make grouping backups easy, and can delete backups with the same tag that are older than a given number of backups.
> Added GCS backup tool

- containers/base/Dockerfile
I've updated the package versions in `containers/base/Dockerfile` to reflect the actual package versions that exist in Datalab. The reason for this change is that several packages were being installed twice during the build process. The changes in this PR will help reduce the number of times that we see the following text in the build log:
```
Found existing installation: <package>
Uninstalling  <package>:
Successfully uninstalled  <package>
Successfully installed <package>
```
Here are the package versions that are installed in Datalab after including the changes from this PR.
```
>>>import pip
>>>for dist in pip.get_installed_distributions():
>>>   print dist
pip 9.0.1
widgetsnbextension 1.2.6
wheel 0.29.0
wcwidth 0.1.7
uritemplate 0.6
traitlets 4.3.1
tornado 4.4.2
terminado 0.6 …
```
> Some packages were installed twice during the build process

- sources/web/datalab/config/settings.json
Fixes #1073
Jupyter notebook recently made a change requiring a login token to be passed, empty to disable auth.
> Add empty login token to disable jupyter notebook auth

- containers/base/Dockerfile
.install folder needed for `gcloud components update` command.
Fixes #1081
> Don't remove .install folder from cloud sdk root

- sources/web/datalab/common.d.ts
- sources/web/datalab/config/settings.json
- sources/web/datalab/jupyter.ts
- sources/web/datalab/server.ts
- sources/web/datalab/wsHttpProxy.ts
This is used to allow creating and connecting to local kernels cross-protocol (such as from an HTTPS page).
This allows an app to host the frontend UI on an HTTPS server and still interact with local kernels. The HTTP requests are only available from whitelisted origins and may only make requests to the local server.
> Add an option for relaying HTTP requests over websockets.

- tools/cli/commands/connect.py
- tools/cli/commands/create.py
- tools/cli/commands/delete.py
- tools/cli/commands/list.py
- tools/cli/commands/stop.py
- tools/cli/datalab.py
This is meant to automate and simplify the manual steps currently documented
[here](https://cloud.google.com/datalab/docs/quickstarts/quickstart-gce-frontend).
This relies on the `gcloud` tool being installed on the same machine,
and the user already being authenticated.
> Initial command line surface for a Datalab management tool

- sources/web/datalab/login.ts
PR #1046 changed the auth module to include an 'appSettings' variable
that must be initialized before the auth flow will work. The login
server was using the auth module to perform that flow, but was not
initializing that variable. This caused the server to abruptly exit
in the middle of that flow.
This fixes #1092
> Make the login server initialze the auth module.

- containers/base/Dockerfile
In the Dockerfile, the default `--progress=dot` style used when wget has non-TTY output uses 1K per dot, 50 dots (50K) per line. This ends up being quite noisy when downloading the 86MB gcc source file, so I've added the `--progress=mega` option which uses 64K per dot instead, which is 3M per line. This allows the progress to fit onto a single screen, instead of many screens.
I also considered using `--progress=giga`, but on slower connections it might be unacceptably long before the first indication of download speed appears.
> Use dot:mega progress meter option for wget

- .travis.yml
- tools/cli/datalab.py
This does two things:
1. Ensures that the 'datalab' container can be built
2. Looks for lint errors in the CLI
This change also includes two fixes to lint errors in the CLI that
were not caught earlier (when we did not have this check).
> Add a Travis config

- tools/cli/commands/connect.py
- tools/cli/commands/create.py
- tools/cli/datalab.py
1. The name of the gcloud binary on Windows is actually 'gcloud.cmd'
rather than 'gcloud'. We detect this by trying to invoke 'gcloud',
and if it fails failling back to 'gcloud.cmd'.
2. Passing the contents of the startup script and container manifest
metadata values via the command line on Windows is not feasible
due to the complexities of escaping their values. Instead, we
write them to named temporary files, and then use the
'--metadata-from-file' arg instead of the '--metadata' one.
3. The devnull file in Windows cannot be opened in 'a' mode.
> Three fixes for running the CLI on Windows:

- sources/web/datalab/settings.ts
This allows patching specific config settings from the environment so the settings can be tweaked without modifying the docker container.
> Allow overriding individual config settings from outside docker container

- sources/web/datalab/server.ts
- sources/web/datalab/settings.ts
- sources/web/datalab/static/datalab.js
- sources/web/datalab/static/reporting.html
1. Make the '_restart' handler require a 'POST' request to do anything.
2. Make the '_setting' handler require a 'POST' request in order to
update a setting. This also meant it should support reading the
form data from either the URL query or from the request body.
Similarly, the various places where we update settings were changed
to use 'POST' requests instead of 'GET' requests.
> Cleanups for GET request handlers:

- tools/cli/commands/create.py
This fixes #1106 where the `datalab create` command only works if
the `compute/zone` gcloud config is set prior to running the command.
With this fix, either the following will work:
1. Setting the zone via the `--zone` argument to the datalab command
2. Setting the zone via the interactive prompt issued by gcloud
However, if using the second option, the user must make sure that
they select the same zone for both the instance and creating the
disk. That issue will be fixed by a subsequent change to come later.
> Support specifying the zone via the CLI when creating an instance

- tools/cli/commands/connect.py
- tools/cli/commands/create.py
- tools/cli/commands/delete.py
- tools/cli/commands/stop.py
- tools/cli/commands/utils.py
This change makes the CLI tool detect if `gcloud` needs to prompt the
user for a zone, and then takes over responsibility for doing that.
There are multiple reasons we want to do this:
1. For the `create` command, we have to do this since otherwise the
user would be prompted multiple times, and they would have to
answer the same way every time in order to avoid issues.
2. For other commands, we would like the zone prompt to look similar
to what we do for the `create` command.
3. For the `connect`, `stop`, and `delete` commands, it makes sense
to simply default to the zone the instance is in if there is only
one matching instance in the project.
> Proactively prompt the user for a zone instead of relying on gcloud to do so

- sources/web/datalab/jupyter.ts
- sources/web/datalab/server.ts
- sources/web/datalab/static/datalab.js
- sources/web/datalab/templates/nb.html
This change removes the previously used 'PROXY_WEB_SOCKETS' environment
variable, and instead detects on the client whether or not that client
needs to proxy websocket connections via socket.io.
This gives us the benefits that:
1. The user no longer needs to decide ahead of time whether or not
their instance will rely on websockets.
2. A single instance can both rely on websockets for some clients
and proxy them for others (e.g. depending on whether an SSH
tunnel is coming from a Cloud Shell instance or from something else).
For now the logic for this decision is based on whether or not the
hostname ends in '.appspot.com' (indicating that it is hosted by
App Engine which does not support websockets).
However, in the future we may want to make the logic more sophisticated
by first trying …
> Automatically detect if websockets need to be proxied.

- tools/cli/commands/create.py
This fixes a bug where turning off backups did not work because the value
was set to "false" (which is truthy) instead of false.
> Fix the enableAutoGCSBackups setting to be a boolean rather than a string

- tools/cli/commands/create.py
This change fixes a bug in the startup script used by Datalab
instances where the command to mount the persistent disk was
being duplicated.
> Remove a duplicate mount command from the startup script

- sources/web/datalab/reverseProxy.ts
- sources/web/datalab/server.ts
- sources/web/datalab/sockets.ts
This commit changes socket.io proxying so that it is done
by a separate server listening to port 8084.
That fixes a bug where the socket.io logic on the main server
was interferring with ungit's usage of socket.io.
The reason this fixes that bug is because the socket.io wrapped
server is only invoked after the reverse proxy has determined that
the request should not be proxied to ungit.
This fixes #1125
> Fix the conflict between the socket.io proxying and ungit

- containers/datalab/content/setup-env.sh
- tools/cli/commands/connect.py
- tools/cli/commands/create.py
- tools/cli/commands/delete.py
- tools/cli/commands/list.py
- tools/cli/commands/stop.py
- tools/cli/datalab.py
With this change, Datalab will configure git with an author email
address at startup. That can also be overridden via an environment
variable.
> Support configuring the author email address for git.

- tools/cli/commands/create.py
- tools/cli/datalab.py
This commit changes the CLI to automatically do two things:
1. Create the `datalab-notebooks` repository if it does not exist
2. Clone that repository into the `datalab/notebooks` directory on
the attached persistent disk when creating a new disk.
With this change (and the next Datalab release), users will be
able to use the ungit UI to manage their notebooks without having
to do any manual configuration.
> Automate integration with Google Cloud Source Repositories

- tools/cli/commands/create.py
This change switches the CLI tool from using the deprecated
container-vm image to the new container optimized OS image for
new instances.
This change should be transparent to users.
This fixes #1097
> Use the Container Optimized OS image for new instances.

- containers/datalab/content/GCSbackup.sh
- sources/web/datalab/backupUtility.ts
This PR uses the VM's zone and name instead of its numeric ID in the GCS backup path to make it easy for the user to find and restore backups. It uses the environment variables added inside the Datalab container for `VM_PROJECT`, `VM_ZONE`, and `VM_NAME`.
It also fixes a minor bug with the backup log where it was written prematurely.
> Use VM's zone and name in the GCS backup path

- containers/base/Dockerfile
This fixes a build breakage that just showed up today (builds
were working this morning, and failing now).
I was not able to isolate exactly what changed, but it seems that
our earlier builds were installing 1.10.0 as a dependency of
something else, and then the explicit install of 1.9.0 was skipped
since the existing 1.10.0 install satisified that dependency.
The failing builds seem to not have the 1.10.0 install, so the
1.9.0 install actually goes through, and later on the 'future'
library fails because it requires 1.10.0.
This change fixes that build breakage by switching our explicit
dependency to be the one that we were implicitly depending on.
> Upgrade the version of the 'six' library to 1.10.0

- containers/datalab/content/run.sh
This change adds a check against the special project ID 'no-project-id'
which is returned by the metadata server in Google Cloud Shell so that
we don't erroneously mistake a Google Cloud Shell instance for a
Google Compute Engine VM that the user can manage.
> Don't set the VM environment variables when running in Google Cloud Shell

- containers/datalab/content/run.sh
This change spins up a background process that continuously watches the SSH process to see if it is still running.
If it finds that it is not, it tries to recreate the SSH tunnel.
This change also includes a fix for an issue where Datalab would not start if it could not communicate with a metadata server (e.g. if it was running locally). That has been sent in a separate PR, and once it is merged I will rebase this PR.
> Restart the SSH tunnel if it dies

- containers/datalab/Dockerfile.in
- containers/datalab/content/run.sh
This removes the version update notification from ungit's UI.
> Upgrade to ungit 1.1.0, use the new --ungitVersionCheckOverride option

- tools/cli/commands/create.py
This change fixes two issues with disk space for Docker images and
containers.
1. Make the container used for formatting the notebooks disk clean
itself up when it exits. This wasn't actually causing any issues,
but it is good hygiene.
2. Double the size of the boot disk for instances. The default size
of 10GB turns out to be just barely too small to fit both the
Datalab image and the fluentd image. This caused issues where
only the first image pulled would be pulled successfully.
> Fix an issue where the Docker images could not fit in the boot disk

- containers/datalab/content/GCSbackup.sh
Also, try using project_id as bucket name if other options have failed.
> Cleanup backup tar after copying to GCS

- tools/release/publish.sh
This change switches the release script from specifying the test project
via the 'PROJECT_ID' environment variable to instead setting the project
via the 'CLOUDSDK_CORE_PROJECT' environment varialbe.
This is necessary because https://github.com/googledatalab/pydatalab/pull/136
changed the pydatalab library so that the gcloud config overrides the 'PROJECT_ID'
environment variable. This means that in a GCE VM, we don't use that variable,
as gcloud will pick up the project name from the metadata server.
However, gcloud itself will use the 'CLOUDSDK_CORE_PROJECT' variable, so we
use that one for setting the test project.
> Explicitly configure gcloud to use the test project in release validation.

- containers/datalab/run.sh
- sources/web/datalab/common.d.ts
- sources/web/datalab/config/settings.json
- sources/web/datalab/logging.ts
Previously, if console logging was enabled, then the log threshold
level was hard-coded to 'info'.
This change both makes that configurable, and changes the default
from 'info' (which is very noisy) to 'warn' (which should only
include things the user really needs to know).
This is part of the work to address #1157
> Add a config setting for the console log level.

- tools/cli/commands/connect.py
- tools/cli/commands/create.py
Previously, Datalab instances wrote a very small amount of
information to StackDriver logging, and then went silent.
With this change, the logs from the Datalab server that are
higher than a configurable threshold will be written to StackDriver
logging.
This change also fixes some badly-named SSH flags that are
used to configure the verbosity of the SSH output to indicate
that those flags are specific to just the SSH connection.
This fixes #1157
> Configure StackDriver logging for Datalab instances.

- sources/web/datalab/jupyter.ts
This is required to allow datalab kernels to be used cross-origin when they live
behind a credentials-requiring proxy, such as Cloud Shell's Web Preview mode.
This fixes #1169
> Add access-control-allow-credentials when access-control-allow-origin is used.

- containers/base/Dockerfile
- containers/base/build.sh
Update TensorFlow and CloudML SDK.
We can remove protobuf installation because installation of TensorFlow includes protobuf. We can remove DataFlow installation because installation of CloudML SDK includes DataFlow.
Fix a bug that when it fails to build the container, an intermediate dir is not cleaned up.
> Update TensorFlow and CloudML SDK. Fix a build bug.

- tools/cli/commands/create.py
This fixes an issue with the larger boot-disk size where gcloud would always log a noisy warning about the boot disk being smaller than 200GB.
> Silence a noisy warning from gcloud

- tools/cli/commands/connect.py
This change stops the CLI from automatically launching the browser
if the type of browser launched is one that may not work with the
Datalab UI.
In particular, this detects a large class of text-only browsers,
including the one that is provided in Google Cloud Shell.
This mitigates iessue #1139, but does not completely fix it, as
we still do not tell the user to launch the web-preview feature.
However, even though this approach still leaves room for improving
the usage under Cloud Shell, it also greatly improves the experience
when running under other environments where a text-only browser
would be opened instead of a browser with a GUI.
> Do not try to launch the browser if it may not support Datalab.

- tools/cli/commands/connect.py
- tools/cli/commands/create.py
- tools/cli/commands/utils.py
The overall goal of this change is to make it clear to users that
the Datalab instances they create should be tied to a single user.
We do this by recording for which user the Datalab instance was
created, and then checking that when a user tries to connect to
the instance.
By default, the Datalab instance is created for the user who runs
the `datalab create` command, but there is a new `--for-user` flag
that can be used to override that.
When a user tries to connect to a Datalab instance that was created
for someone else, the code prints out an error message explaining
the user mismatch.
The user still has the option of disabling that check by passing
in the new `--no-user-checking` flag, but this should prevent
users from accidentally stomping on each others' toes.
This fixes #1165
> Prevent users from accidentally sharing a Datalab instance.

- tools/cli/commands/create.py
This fixes a bug where the errors reported by gcloud when creating
a disk were sometimes discarded without being shown to the user if
the command failed the first time it is run, but will not be retried
(either because the zone has been explicitly set, or the --quiet
flag has been specified, causing us to not prompt for a zone).
> Report errors when creating a disk to the user if the error is terminal.

- tools/cli/commands/connect.py
- tools/cli/commands/create.py
- tools/cli/datalab.py
This change teaches the CLI to detect when it is running inside
of the Google Cloud Shell, and then handle successful connections
differently for that case.
The purpose of this is that the user cannot connect to the 'local'
port in Cloud Shell via the 'localhost' domain name, but rather
must use the 'Web Preview' feature of Cloud Shell to connect to
their Datalab instance. As such, the tool should tell the user
to connect using the 'Web Preview' feature.
This fixes #1139
> Detect when the CLI is run from Google Cloud Shell 

- tools/cli/commands/create.py
> Allow the user to specify the service account when creating an instance.

- sources/web/datalab/jupyter.ts
- sources/web/datalab/reverseProxy.ts
- sources/web/datalab/sockets.ts
- third_party/externs/ts/node/tcp-port-used.d.ts
When running on machines with no IPv4 interface, 127.0.0.1 is not a useful IP or
interface name.  localhost on the other hand is ~universally useful for the same
concept, and works equally well on each of IPv4-only, IPv6-only, and dual-stack
machines.
This change replaces 3 explicit usages of "127.0.0.1" and two implicit ones
(hiding behind the default or null arguments to tcp-port-used's functions.
b/35224793
> Replace 127.0.0.1's with localhost to support IPv6-only machines.

- tools/cli/commands/connect.py
- tools/cli/commands/create.py
- tools/cli/commands/utils.py
This change is in response to an interactive prompt accidentally
being hidden when connecting to a VM (asking whether or not it
should create the "~/.ssh" directory). However, rather than just
fixing that one issue, this tries to eliminate that entire class
of errors.
The way we do this is by adopting the following design:
1. If a call to gcloud needs to silence the output of gcloud, then
it calls the call_gcloud_quietly method, which always includes
the `--quiet` flag in the call to gcloud.
2. The only other time a call to gcloud has the stdout or stderr
redirected is when the tool needs to process the output of the
call, and in those cases the tool always adds the `--quiet` flag
to the call to gcloud.
3. For all remaining calls to gcloud (including the one that caused
the issue), we do …
> Fix potential issues with interactive prompts being hidden.

- tools/cli/commands/create.py
Only project owners can create a repository, so project editors who
create a Datalab instance for the first time might hit a permission
denied error when running that step.
The current error message only tells you that you don't have permission,
so this changes it to instead tell you who you need to ask to fix
the issue (i.e. a project owner).
> Improve the error message when a user does not have permission to create the repository.

- tools/cli/commands/utils.py
This change fixes calls to gcloud where the same file was being
used for both the stdout and stderr of the subprocess call.
That caused issues where we needed to parse the stdout, but text
written to stderr was being intermixed with it. It also caused
more subtle issues where gcloud would write something to stderr,
and we would report it to the user via stdout (instead of stderr).
There is only one spot left where both stdout and stderr are written
to the same file, and that is where we are simply logging both of
them.
This fixes #1197
> Don't combine stderr and stdout when calling gcloud

- sources/web/datalab/static/datalab.css
- sources/web/datalab/static/datalab.js
- Check light theme radio button by default before getting configured theme
- Make matchingbracket more visible
> Check light theme radio button by default

- tools/cli/commands/connect.py
- tools/cli/commands/create.py
- tools/cli/commands/delete.py
- tools/cli/commands/list.py
- tools/cli/commands/stop.py
- tools/cli/datalab.py
This fixes two readability issues with help output:
1. References to command invocations are now quoted so that it is easier to tell what is a reference to a command and what is text describing that command.
2. The program name is now hard-coded to `datalab`, as the argv[0] value was being set to the fully qualified path to the 'datalab.py' python file.
> Make the `datalab ... --help` output more readable

- tools/cli/commands/create.py
- tools/release/publish.sh
We were previously not using the "latest" tag because that had
been used by oure beta1 release, which ran in App Engine.
However, that has been deprecated for so long that we can now
take back the "latest" tag.
This change updates the default for the CLI and the release
script.
The release script will continue to also update the "local" tag,
so that anyone using it can still get updates.
> Switch the default image tag to be "latest" instead of "local".

- tools/cli/commands/connect.py
Previously, the `datalab connect` command was calling `gcloud compute ssh`
twice, once with output forwarded to the user, and once with output
written to a log file.
That was causing issues when a user has a passphrase on their SSH key,
because they would be prompted for the passphrase repeatedly.
This also didn't seem to save anything in terms of the actual verbosity
of the `connect` command output.
This fixes #1214 (at least as much as we can).
> Remove the ensure_sshable method.

- containers/base/config/ipython.py
This imports and readies the new magics defined under google.datalab, which was recently committed to master in pydatalab (https://github.com/googledatalab/pydatalab/pull/241).
> Add magics defined under google.datalab from pydatalab extension

- sources/web/datalab/static/datalab.css
Datalab already has css to hide the input indent. This change does a similar thing for the output indent.
> Remove output indent by disabling unused output prompt.

- containers/base/Dockerfile
- containers/datalab/content/GCSbackup.sh
For a more Windows-friendly experience.
> Use zip instead of tar for GCS backups

- sources/web/datalab/static/appbar.html
- sources/web/datalab/static/dark.css
- sources/web/datalab/static/datalab.css
- sources/web/datalab/templates/nb.html
Fixes #1223 and #889 
- Fix scrolling issues across main content area and sidebar
- Make page more responsive by collapsing toolbar button texts to show only the button icons. For that I had to also add some more icons to distinguish the Add Code and Add Markdown buttons, image below.
> responsive design, fix scrollbars

- sources/web/datalab/static/appbar.html
- sources/web/datalab/static/datalab.css
- sources/web/datalab/static/datalab.js
- sources/web/datalab/templates/edit.html
- sources/web/datalab/templates/nb.html
- sources/web/datalab/templates/tree.html
Used Google material design icons for everything, except for git, which I kept the fontawesome icon (we load fontawesome anyway as part of Jupyter).
> UI refresh - use material icons

- sources/web/datalab/static/datalab.js
It's not clear to me why this happens from time to time, it might be that the reference to `notebook` maintained by the closure gets changed somehow, and some uses don't even have a closure to keep the reference. Using the global object `Jupyter.notebook` is safe in this context, and fixes this issue.
This also fixes the keyboard shortcut for undoing cell deletion, which started getting assigned with this fix, but was calling a deprecated method.
> Fix intermittent undefined notebook error

- sources/web/datalab/static/datalab.css
This lets cell output use the entire width of the cell.
Fixes https://github.com/googledatalab/datalab/issues/1240.
> Fix console output max width

- containers/base/Dockerfile
- sources/web/datalab/static/dark.css
- sources/web/datalab/static/datalab.css
- sources/web/datalab/static/datalab.js
- sources/web/datalab/static/light.css
(This PR is functionally dependent on https://github.com/googledatalab/pydatalab/pull/272, tests will not pass until that PR is merged)
Installs `google.datalab.notebook` as a separate Jupyter extension in order to allow it to define its own CodeMirror modes. It's also good to make the separation now so it's easier to deprecate the old namespace `datalab`.
The PR also fixes CSS colors to make things more consistent between light and dark themes.
> Add syntax coloring for `%bq query`

- sources/web/datalab/static.ts
- sources/web/datalab/static/datalab.css
- sources/web/datalab/templates/edit.html
When trying to open a markdown file, console shows some errors trying to load codemirror modes `markdown` and `xml`, we just need to reroute those to the right path.
I also added a missing chevron for the File menu, and updated the minimum width to account for the missing chevron that was added to Notebook menu.
> Fix load errors, colors for markdown file

- tools/cli/commands/utils.py
With this change, every command that is meant to operate on an
existing instance (connect, stop, delete), will raise an error
if the user specifies an instance that was not created by the
datalab command line tool.
This fixes #1268
> Don't let the `datalab` tool manage non-datalab instances

- containers/datalab/run.sh
The `run.sh` script should used in local development only, make it verbose by default.
Fixes https://github.com/googledatalab/datalab/issues/1236.
> Make local build and run verbose by default

- sources/web/datalab/static.ts
- sources/web/datalab/static/appbar.html
- sources/web/datalab/static/datalab.css
- sources/web/datalab/static/datalab.js
- sources/web/datalab/static/settings.html
- sources/web/datalab/static/settings.js
As we're adding more features to the editor, and more user preferences, we need a standalone settings pane. This PR adds a simple one that shows as a modal using a new settings button.
This is becoming too many buttons on the top right toolbar, we might want to discuss rearrangement there.
Fixes #1110
> Add a settings pane

- tools/cli/commands/utils.py
- tools/cli/datalab.py
Prior to this change, running a datalab command against a non-existant
instance (e.g. `datalab connect does-not-exist`) would prompt the user
to specify a zone for that instance prior to telling them that it does
not exist.
However, at that point the code already ran a list command to find
matching instances, so it should no that there are none.
This change makes the pompt a little more intelligent so that it
can bail out early if it knows there is no valid zone a user could
provide for which the instance could be found.
This change also makes changes the entrypoint so that we only print
stack traces for user errors when the `--verbosity` flag has been
set to either `debug` or `info`.
This fixes #1224
> Don't prompt for a zone when the user specifies a non-existant instance.

- containers/base/Dockerfile
- tools/release/build.sh
Been seeing some issues due to our old version of node again, and node 4.x is about to enter [maintenance mode](https://github.com/nodejs/LTS). I think this will also help the build failures we see every now and then due to node errors.
> Upgrade to node 6.10

- containers/base/Dockerfile
- sources/web/datalab/static/codemirror/mode/bigquery.js
- sources/web/datalab/static/codemirror/mode/sql.js
I'm moving these from pydatalab to datalab for better isolation. In pydatalab, these are not executed automatically, and the user has to link them explicitly into the pydatalab installed extension (see removed lines in the base Dockerfile).
Instead, we can serve these as static files from within datalab, which has an added value of being able to build on top of them later for other editor functions (formatting, autocomplete.. etc).
> Add CodeMirror bigquery and sql modes in datalab

- containers/test/content/test.py
- containers/test/run.sh
Running them in parallel caused some flakiness locally, moving to sequential browser creation fixed it.
I also added the default entrypoint for the test script, which was missing.
> Run notebook tests in sequence instead of parallel

- containers/test/content/test.py
This was another source of flakiness. Javascript code sometimes was called before the notebook kernel was ready, so cells were not executed. This change gives the notebook about 5 seconds to initialize, waiting for kernel to not be busy.
> Wait on notebook kernel before running it

- sources/web/datalab/static/appbar.html
- sources/web/datalab/static/datalab.css
- sources/web/datalab/static/datalab.js
- sources/web/datalab/static/light.css
- sources/web/datalab/templates/nb.html
It took a few seconds to locate the help documentation in the Datalab app bar (hover the icons until I found 'Help links').
This PR changes the icon for the link titled 'Help links'  to use the 'help_outline' icon instead of 'open in new' from https://material.io/icons/.
I've included a screenshot from my local environment.
Feel free to close if the 'open in new' icon is preferred.
> Improve the user experience around accessing help information and notebook navigation

- sources/web/datalab/static/datalab.css
Fixes https://github.com/googledatalab/datalab/issues/1063.
> Fix css cut-off issue on cell mini-toolbar

- .gitignore
- containers/base/Dockerfile
- sources/web/datalab/static/datalab.js
- sources/web/datalab/templates/nb.html
(Depends on https://github.com/googledatalab/pydatalab/pull/325)
This button interrupts the kernel execution, and can be accessed in a dropdown menu under the `Reset Session` button.
The `ipykernel` update is needed because the older `ipykernel` version had the undesired behavior of continuing queued cell execution after interrupting the first running cell.
Fixes https://github.com/googledatalab/datalab/issues/1049.
> Add "Interrupt Execution" (stop cell) button

- sources/web/datalab/static/datalab.css
Fixes https://github.com/googledatalab/datalab/issues/1261.
> Fix appContent height bug that shows on Safari

- sources/web/datalab/static/codemirror/mode/bigquery.js
This PR updates the color for BigQuery logical operators to match the color for BigQuery keywords when using `%bq query` in a cell.
Proposed colors:
I've also updated the order of the keywords to match the [docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#reserved-keywords) .
> Update the color for logical operators to match BigQuery keywords

- sources/web/datalab/static/datalab.css
This reverts commit 4d6b4e0da33acbd79a4049f768bb9a5882811602, which fixed https://github.com/googledatalab/datalab/issues/1063.
The css fix causes bad side effects with code cells that have very long outputs, where switching code cells takes several seconds for some reason, it gets worse the longer the cell output is. The situation is a little better in Firefox, but I can't seem to figure out why.
I'll revert because the performance issue has more priority than fixing the css for the menu. I'll also reopen that issue.
> Revert "Fix css cut-off issue on cell mini-toolbar (#1287)"

- containers/base/build.sh
- containers/datalab/build.sh
- containers/datalab/run-extended.sh
- containers/gateway/build.sh
- containers/test/build.sh
I have a collection of cases where I'm calling into
`containers/datalab/build.sh` from another script, and I'd like to customize
the args passed to `docker build`.
In my case, I'd like to add `--no-cache` to the build args. Given that this
calls docker from several places (there and in `containers/base/build.sh`),
setting an env var seems like the cleanest way to wire this in.
PTAL @chmeyers @yebrahim @jimmc (Not sure who watches the dockerfiles)
> Add support for customizing `docker build` args.

- containers/datalab/content/run.sh
- containers/datalab/run.sh
- sources/web/datalab/jupyter.ts
- sources/web/datalab/static.ts
This change takes advantage of existing code to implement a better and simpler live-mode than in #1316.
1. When running container/datalab/run.sh during development, by default it now starts the container with a mount point for /devroot that points to the datalab root directory.
2. Inside the container, when datalab/run.sh sees that a /devroot mount point exists, it copies in the latest js files for the notebook server, and sets a couple of environment variables to point to the source directories for the static and templates folders.
3. In the code, when those environment variables are set, it pulls static and template files from those locations, and files in those directories are not cached, but are reloaded when they are changed.
Usage:
1. By default, live-mode is enabled when starting …
> Implement live mode for faster development.

- containers/datalab/content/run.sh
With this change, the developer no longer needs to restart the notebook server when making changes to typescript files. Just run sources/web/build.sh, and the notebook server will auto-restart.
> Make live mode work better for compiled typescript.

- containers/test/content/startup.sh
- containers/test/content/test.py
- containers/test/run.sh
- sources/web/datalab/static/datalab.js
- sources/web/datalab/static/edit-app.js
- sources/web/datalab/static/notebook-app.js
- sources/web/datalab/static/notebook-list.js
- sources/web/datalab/templates/sessions.html
(Replacing https://github.com/googledatalab/datalab/pull/1333)
This is fixing the previously arbitrary script load order, by waiting on events triggered by Jupyter for each of the four template pages.
The scripts we execute in any given page to customize it can have some code that must execute before the page is initialized by Jupyter (such as adding event listeners), but it also has some code that assumes elements have already been loaded (such as customizing functionality of buttons). This PR splits Datalab's customization scripts into preLoad and postLoad scripts, and calls them appropriately.
The big change in `nb.html` is just moving code around, no changes to that code were made.
The change also adds a `window.datalab.loaded` flag signaling that loading was finished. Later on I'll …
> Fix front end script load order

- sources/web/datalab/jupyter.ts
- sources/web/datalab/server.ts
- sources/web/datalab/static/dark.css
- sources/web/datalab/static/datalab.css
- sources/web/datalab/static/notebook-list.js
- sources/web/datalab/templates/sessions.html
- sources/web/datalab/templates/terminals.html
- sources/web/datalab/templates/tree.html
This adds the Jupyter terminal functionality in Datalab. We will want to customize this for the Datalab experience, but we can do that in a later PR when we decide on a good usability design for it.
This PR adds the necessary plumbing for Jupyter's terminal, which is:
- A new HTML template with just the appbar and one big div for the terminal, and some css styling. A div (`dummy-screen`) is also needed to measure height and width of the terminal element, with some dummy data inside it.
- Changes to `server.ts` and `jupyter.ts` to pass that template page when requested
- An "Add Terminal" button in the tree page
- Changes to the sessions page to list active terminals under active notebooks
> Add a terminal functionality

- containers/base/Dockerfile
We already saw one of the side effects of using the default (POSIX) encoding in the debian image [in this SO question](http://stackoverflow.com/questions/43175113/how-to-import-h5py-on-datalab/43490376#43490376).
> Switch to UTF-8 filesystem encoding

- sources/web/datalab/static/datalab.css
- sources/web/datalab/templates/nb.html
Hide the Kernel Picker menu until it's ready for the next release.  Dataflow, Cloud ML Engine, and ML Toolbox still need py3 support.
> Hide the Kernel Picker menu until it's ready.

- containers/datalab/Dockerfile.in
- containers/datalab/content/.bashrc
- sources/web/datalab/static/datalab.css
- sources/web/datalab/static/datalab.js
- sources/web/datalab/templates/terminals.html
- test/ui/test.js
This fix adds a bashrc file inside the container to set up the enviornment for the user. Currently it changes directory to `/content`, colors the prompt, and adds a message to tell the user to keep sensitive work in `/content`. The `ENV` env var is set so that file gets loaded by all shells.
The rest of the PR is UI fixes to make things look better, and fixed the order of loading the Jupyter dialog module.
> Terminal fixes: use bash, UI improvements

- containers/datalab/run.sh
This fixes a small dependency on `realpath`, which isn't available on MacOS without coreutils.
> Fix realpath dependency for MacOS

- tools/cli/commands/connect.py
This fixes #1111. If the instance is no longer RUNNING when it is time to attempt to reconnect, it just prints a message and exits.
> Don't attempt to reconnect if the instance is no longer RUNNING.

- tools/cli/commands/list.py
- tools/cli/datalab.py
The `datalab` command line tool adds a `datalab` tag to every
instance that it creates. As such, the `datalab list` command
should only show the instances that have that tag.
Previously, `gcloud compute instances list` did not support
filtering on nested fields (such as the 'items' field of the
'tags' object), so we could not directly filter on that tag.
However, the beta labels feature (at that time) created a top
level label for every tag on an instance. This meant that we
could filter out non-datalab instances by filtering on that label.
The label feature has since been changed so that tags no longer
get copied into labels. That change results in the `datalab list`
command being too aggressive in its filtering, and the output
always being empty.
Coincidentally, the limitation on …
> Fix bug in the list command that filtered new instances.

- containers/datalab/build.sh
- containers/gateway/build.sh
- tools/release/config_local_template.js
- tools/release/publish.sh
- tools/release/version.sh
This change adds a template file for the config_local.js that gets uploaded to GCS on release. This template has placeholders for fields that are changed by the release process.
The release script is also changed to be backwards-compatible with this new format and the old one.
In addition, I added a `version.sh` file that contains the source of truth for the Datalab version that is used by the Datalab/Gateway build scripts as well as release script. *I also bumped the version to the next semver value `1.2.DATE`*, ideally this should be a standalone change before each release.
> Move to version file backwards-compatible release.sh

- tools/cli/commands/create.py
- tools/cli/datalab.py
As of version 156.0.0 of the Cloud SDK, the `gcloud source repos`
command group has been moved to the GA release track, so we no
longer need to rely on the `alpha` commands.
> Switch to the GA version of the `gcloud source repos` commands.

- sources/web/datalab/static/websocket.js
*hint: use querystring param `w=1` to view this PR*
This fixes a bug with the initialization path of the websocket patch code, which caused the recent failure on Cloud Shell and rollback.
I'm still looking for a good way to mock cloud shell and add a test for this, but we need to get this fix in as it's blocking the release.
> Fix websocket initialization bug

- sources/build.sh
- tools/release/build.sh
- tools/release/cloudbuild.yaml
This commit is a first-pass at using
[Container Builder](https://cloud.google.com/container-builder/)
to build our Docker images.
For now, this is not very useful, as it only builds our base images,
which are only ever used as prerequisites for later image builds.
However, this does let us make progress towards a more complete build
by ensuring that our base images build successfully in Container Builder.
This is part of the work towards fixing https://github.com/googledatalab/datalab/issues/1400
> Initial pass at using Container Builder.

- sources/web/datalab/templates/terminals.html
Terminals use websocket, which is disabled on cloud shell, we need to load socket.io there too.
> Use socket.io for terminals page

- containers/base/build.sh
- containers/datalab/build.gpu.sh
- containers/datalab/cleanup.sh
- containers/datalab/prepare.sh
- containers/gateway/build.sh
- containers/gateway/cleanup.sh
- containers/gateway/prepare.sh
- sources/build.sh
- tools/release/build.sh
- tools/release/cloudbuild.yaml
This also involves some restructuring of the existing build scripts to
make logic more reusable, and updates to use consistent idioms throughout.
This is part of addressing #1400, but that issue will not be completely
fixed until we also build the CLI tarball via container builder.
> Build the `datalab` and `datalab-gpu` images via Container Builder

- containers/gateway/prepare.sh
- tools/release/cloudbuild.yaml
- tools/release/generate_config_local.sh
- tools/release/publish.sh
This change adds two more components to our Container Builder builds:
1. The building of the kernel-gateway image
2. The generation of a `config_local.js` file for the build
> Flush out the Container Builder config

- tools/release/cloudbuild.yaml
This change adds the bundling of the CLI tarball to our Container Build.
This was the last step covered by `tools/release/build.sh` that was
not covered by our Container Build, so this that conversion is complete
(although we are still using the daily build and will continue to do
so until our release process is updated).
This fixes #1400
> Finish flushing out the Container Builder config.

- containers/datalab/run.sh
We get a performance hit when starting the server on OSX if the home directory contains a lot of files, because of a limitation on the package we're using to index the file system (see https://github.com/paulmillr/chokidar/issues/597).
Since this script is used for the dev workflow, we can use a new directory `$HOME/datalab_home` that will only contain datalab files, just like the case on a VM.
> Map $HOME/datalab as /content/datalab

- tools/release/cloudbuild.yaml
This makes it much easier to pull it down as a default.
> Give the last successful master branch build a static tag.

- sources/build.sh
- sources/web/build.sh
1. Make the node setup consistent with its use. We are using npm
to install other dependencies globally, so placing the node
installation under the current working directory caused issues.
2. Make the bower invocation work when we run it inside of a Docker
container (such as when run in Container Builder). Specifically,
the default setup in a container is that there is only one user;
root. As such, we should disable bower's defensive check against
running as root.
> Fix the `sources/build.sh` dependency setup:

- containers/datalab/Dockerfile-preview
- tools/release/cloudbuild.yaml
This change also fixed some hard-coded bucket names so that it is possible to test the Container Builder config by pushing to a test project.
Similarly, this also changed the bucket name from where we pull the production `config_local.js` file so that it *is* hard-coded. The difference is that one is independent of the project ID, whereas the others are not.
> Add preview images that are built on every push to master

- test/run.sh
With the PR, it is no longer necessary to manually delete ~/datalab_tests before running the ui integration tests locally.
> Clean up old test data before running ui integration tests.

- sources/web/datalab/sockets.ts
- sources/web/datalab/static/websocket.js
The confusion here was around the differences between "namespace" and "path" for socket.io
> Fix web sockets when using a base dir.

- containers/datalab/run-extended.sh
In `containers/datalab/run-extended.sh` by default `CONTENT=$HOME` is more than enough to be mounted. `$CONTENT/datalab` should be more sensible, the same way it's done in `containers/datalab/run.sh`.
Actually, on my Mac, without this modification `run-extended.sh` takes very long to start, and then only a buggy navigation bar would appear in the browser.
> docker mount $CONTENT/datalab (not $HOME)

- sources/web/datalab/static.ts
From my experimenting with it, adding the `Cache-Control` header to responses for static files cuts ~ 1/2 second off of the total time required for each directory page load.
We add that header for every static resource except for `custom.css`, since that one changes every time a user updates their theme setting.
> Tell the client that it can cache static content

- sources/web/datalab/polymer/components/base-dialog/base-dialog.html
- sources/web/datalab/polymer/components/base-dialog/base-dialog.ts
- sources/web/datalab/polymer/components/datalab-files/datalab-files.html
- sources/web/datalab/polymer/components/datalab-files/datalab-files.ts
- sources/web/datalab/polymer/components/input-dialog/input-dialog.html
- sources/web/datalab/polymer/components/input-dialog/input-dialog.ts
- sources/web/datalab/polymer/modules/Utils.ts
- third_party/externs/ts/polymer/polymer.d.ts
As we're adding more types of dialogs, using inheritance is a cleaner and easier approach.
In order to use inheritance with Polymer, this change adds a template stamp mechanism, which takes the subclass and baseclass, and stamps the former into an element inside the latter. This way we can reuse the Javascript across the elements, and we can extend the template at the same time.
This change adds a BaseDialog type that shows a dialog with room for a title, messag, and ok/cancel buttons. The InputDialog then extends this to add an input element with some more input behavior.
> [Polymer UI] Implement input dialog as a subclass of base dialog

- sources/web/datalab/auth.ts
- sources/web/datalab/jupyter.ts
This change fixes two server-side performance issues that affected every page load:
1. Loading a user setting that was removed prior to the GA release (this was
effectively dead code, but still slowed things down).
2. Calling `gcloud auth list` twice; once to determine if the user was signed
in and a second time to find out the email address of their account. Even
calling `gcloud auth list` once on every page load is overkill, but at least
this cuts the number of calls in half. A TODO has been added to get this down
even further.
> Reduce page load latency

- sources/web/datalab/auth.ts
This change adds a cache of the gcloud account that is stored on the server
side so that it no longer needs to invoke `gcloud auth list` on every page load.
With this change, navigating the file directory is much faster. In my
testing, each page load of a `tree/...` URL takes less than 1 second.
> Don't invoke `gcloud auth list` for every page load.

- sources/web/datalab/polymer/components/datalab-app/datalab-app.html
Polymer overlay behaviors require no parent elements with higher z-index stacking context. Since we currently don't have any issue with z-index (this was just added for safety), I'm removing this. When we need, we'll have to specify z-index for all our layers.
See the limitation section here: https://www.webcomponents.org/element/PolymerElements/iron-overlay-behavior, and read on stacking contexts here: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context
> [Polymer UI] Remove explicit z-index from toolbar

- sources/build.sh
- sources/web/datalab/backupUtility.ts
- sources/web/datalab/polymer/modules/ApiManager.ts
- sources/web/datalab/polymer/tsconfig.json
- sources/web/datalab/server.ts
I recently changed the `startuppath` format to not contain the `/tree` prefix, but the old UI still expects the prefix. This broke clients that already have the setting saved in the old format, and were not using the experimental UI. This change makes the old UI work with or without it so it can talk to either format.
This change also lets the `sources/build.sh` output to stdout directly, and fixes a few things that broke with the new `tsc`.
> Make old ui backward compatible with the new startuppath format

- containers/datalab/run.sh
This lets me run "containers/datalab/run.sh -e DATALAB_EXPERIMENTAL_UI=true" to bring up the experimental UI without having to edit the run.sh script.
> Add -e option to run command.

- sources/web/datalab/settings.ts
If a user settings or app settings file is found but empty, the `JSON.parse` will fail, since empty string isn't valid JSON.
> Avoid failing if empty settings file found

- sources/web/datalab/static.ts
This change allows me to more easily compare details of the old and new UIs. I can run without the experiment flag to view and use the old UI, then open another tab at localhost:80801/exp/ to view and use the new UI at the same time.
> Allow alternate access to experimental UI via /exp/ path.

- sources/web/datalab/polymer/components/auth-panel/auth-panel.html
- sources/web/datalab/polymer/components/auth-panel/auth-panel.ts
- sources/web/datalab/polymer/components/datalab-files/datalab-files.html
- sources/web/datalab/polymer/components/datalab-toolbar/datalab-toolbar.html
- sources/web/datalab/polymer/components/datalab-toolbar/datalab-toolbar.ts
- sources/web/datalab/polymer/components/shared-styles/shared-styles.html
This PR adds sign-in and sign-out buttons to the account menu in the Polymer UI. At the moment, they do nothing except toggle the signed-in state, they don't actually sign in.
When signed out, the sign-in button is visible:
When signed in, some info about user and project appears along with the sign-out button:
> Add polymer UI elements for sign-in and sign-out.

- containers/base/Dockerfile
- containers/base/Dockerfile.py2
Changes needed to work with Dataflow 2.0 in MLToolbox is submitted to pydatalab repo.
> Upgrade DataFlow from 0.6 to 2.0.

- sources/web/datalab/polymer/bower.json
- sources/web/datalab/polymer/components/datalab-files/datalab-files.html
- sources/web/datalab/polymer/components/datalab-sessions/datalab-sessions.html
- sources/web/datalab/polymer/components/datalab-settings/datalab-settings.html
- sources/web/datalab/polymer/components/datalab-settings/datalab-settings.ts
- sources/web/datalab/polymer/components/datalab-toolbar/datalab-toolbar.html
- sources/web/datalab/polymer/components/shared-styles/shared-styles.html
- sources/web/datalab/polymer/index.html
- sources/web/datalab/polymer/modules/ApiManager.ts
This change adds a settings panel element, and adds the first setting to it for switching themes.
Note that settings are now loaded twice from the backend, so next we'll need a centralized cache for user and app settings. I'll do that as a separate change.
> [Polymer UI] Add theme switcher setting

- sources/web/datalab/polymer/components/datalab-app/datalab-app.html
- sources/web/datalab/polymer/components/datalab-files/datalab-files.ts
- sources/web/datalab/polymer/components/datalab-settings/datalab-settings.ts
- sources/web/datalab/polymer/modules/ApiManager.ts
- sources/web/datalab/polymer/modules/GapiManager.ts
- sources/web/datalab/polymer/modules/SettingsManager.ts
This PR adds a `SettingsManager` class that caches app and user settings so that duplicate API requests can be avoided.
> [Polymer UI] Add a settings cache

- sources/web/datalab/polymer/bower.json
- sources/web/datalab/polymer/components/datalab-settings/datalab-settings.html
- sources/web/datalab/polymer/components/datalab-settings/datalab-settings.ts
- sources/web/datalab/polymer/components/datalab-toolbar/datalab-toolbar.html
- sources/web/datalab/polymer/components/datalab-toolbar/datalab-toolbar.ts
- sources/web/datalab/polymer/components/shared-styles/shared-styles.html
- sources/web/datalab/polymer/modules/ApiManager.ts
This change adds the timeout interval setting to the settings element, with a tooltip that explains its usage. (The tooltip shows on mouseover, the screen shot is a little misleading)
It also triggers loading settings every time the dialog is opened instead of only once.
> [Polymer UI] Add timeout interval setting

- containers/base/Dockerfile
- containers/base/Dockerfile.py2
- containers/datalab/run.sh
pydatalab changes will come.
protobuf is now whatever TF wants.
This PR almost fixes #1479. When pydatalab is updated, then that issue can be closed.
> use tf 1.2.0 in the container. 

- sources/web/datalab/polymer/components/datalab-app/datalab-app.html
- sources/web/datalab/polymer/components/datalab-app/datalab-app.ts
- sources/web/datalab/polymer/components/datalab-files/datalab-files.html
- sources/web/datalab/polymer/components/datalab-files/datalab-files.ts
- sources/web/datalab/polymer/components/datalab-sidebar/datalab-sidebar.html
- sources/web/datalab/polymer/components/datalab-terminal/datalab-terminal.ts
- sources/web/datalab/polymer/modules/Utils.ts
This change adds some responsiveness to the `datalab-files` element, by splitting the toolbar into two sets of buttons: Add buttons, and File Operations buttons. Each set collapses separately into a dropdown to save space when the screen is too narrow.
To do this, the parent `datalab-app` element now listens for window size changes, and calls resize handlers on the currently active page. Currently `datalab-files` and `datalab-terminal` have handlers that make use of this event.
The actual collapsing is done in javascript because it moves the buttons dynamically to an alternative dropdown element. I could not get a similar effect just using CSS, let me know if you have any ideas here.
This is what it looks like with the Add toolbar collapsed:
This is when both toolbars are collapsed:
> [Polymer UI] Make design more responsive with screen width

- sources/web/datalab/polymer/components/datalab-app/datalab-app.html
- sources/web/datalab/polymer/components/datalab-app/datalab-app.ts
- sources/web/datalab/polymer/components/datalab-files/datalab-files.html
- sources/web/datalab/polymer/components/datalab-terminal/datalab-terminal.ts
- sources/web/datalab/polymer/polymer.json
Datalab pages were not lazy loaded up till now, they were immediately imported in the `datalab-app` element. This PR changes that to make sure heavy elements aren't loaded unnecessarily.
This also fixes the terminal issue where size was being calculated too early, which was related to the element not being lazy loaded.
> [Polymer UI] Actually lazy load datalab page elements

- sources/web/datalab/polymer/components/datalab-files/datalab-files.ts
- sources/web/datalab/polymer/components/datalab-sessions/datalab-sessions.ts
- sources/web/datalab/polymer/components/item-list/item-list.html
- sources/web/datalab/polymer/components/item-list/item-list.ts
This PR adds the ability to select multiple items in the `item-list` element by clicking a select/unselect all button, or by using modifier keys: shift+click remembers the last selected item and selects all between that item and current selection, ctrl+click toggles selection of the current item, adding or removing it to the selected group.
The change also cleans up the code for `item-list` to move more things to Polymer's automatic event bindings, and avoid manual tracking of selected indices by using array mutation syntax.
Note that multi-selection is not currently useful yet, since toolbar buttons are activated on single-item selection, so this will be added next.
> [Polymer UI] Enable multi-selection with modifier keys, (Un)Select All

- sources/web/datalab/polymer/components/datalab-app/datalab-app.html
- sources/web/datalab/polymer/components/datalab-data/datalab-data.html
- sources/web/datalab/polymer/components/datalab-data/datalab-data.ts
- sources/web/datalab/polymer/components/datalab-sidebar/datalab-sidebar.html
- sources/web/datalab/polymer/components/datalab-sidebar/datalab-sidebar.ts
- sources/web/datalab/polymer/polymer.json
- sources/web/datalab/static.ts
This PR implements an initial Data pane. The intent of this pane is to provide easy browsing of BigQuery tables and eventually other data. At the moment, this data pane includes only dummy data.
Clicking the Search button populates the Collections list. Clicking on a Collection populates the Datasets list. Clicking on a Dataset populates the Details pane on the right.
For now, the Data button in the left nav bar only appears when showing the Data pane, so for now you must enter the URL to get to that pane.
> [Polymer UI] Add skeleton Data pane with dummy data.

- tools/cli/commands/create.py
This change updates the filter used by the `datalab create` command
when calling `gcloud source repos list` so that the filter matches
the behavior documented by the `gcloud topics filters` command.
More specifically, a filter of the form `<KEY>:<PATTERN>` is documented
to match if the value associated with the key completely matches the
given pattern (meaning that the entire string is consumed by the pattern
match). However, prior to Cloud SDK version 162.0.0, the filter would
allow resources through if there was a *partial* match rather than
a total match.
The `datalab create` command was unintentionally dependent on this
behavior (which did not match the documented behavior), as the
filter passed to the `gcloud source repos list` command only matched
the repository name, and not the …
> Fix for the filter used to list source repositories

- tools/cli/commands/create.py
The --idle-timeout command line option got broken after some recent code changes. This PR disables this command line option for now until we figure out how we want to fix it.
> Comment out broken --idle-timeout command line option.

- tools/cli/commands/utils.py
This change extends the `call_gcloud_quietly` method so that it
checks if gcloud reported any warnings, and if so cascades them
up to the user.
This prevents us from accidentally obscuring warnings about things
like calling gcloud in a way that is deprecated.
> Report warnings from gcloud

- containers/datalab/run.sh
This makes it a bit easier to turn down the log level noise while developing.
> Add --log-level to dev run command.

- sources/web/datalab/reverseProxy.ts
- sources/web/datalab/server.ts
Fixes #1507.
Note this also moves handling the reverse proxy requests separately from other requests.
> Skip reverse proxy requests from static handler

- sources/web/datalab/idleTimeout.ts
- sources/web/datalab/settings.ts
- test/server-unit/settings_spec.js
- tools/cli/commands/create.py
This PR re-implements the --idle-timeout command line option in the "datalab create" command that was recently removed (before being released), as it was broken due to a change in the implementation of how the idle timeout initial value was handled.
The implementation in this PR includes code that allows for specifying initial values for any user setting, which are applied when the user settings file is created during initialization to override the default user settings values. At present, the --idle-timeout command line option is the only user setting that is managed this way, but it would be easy to allow other initial user settings to be done using the same mechanism in the future by adding additional command line options.
The --idle-timeout command line option implemented in this PR …
> Re-implement --idle-timeout CLI option, clean up settings update.

- sources/web/datalab/polymer/bower.json
- sources/web/datalab/polymer/components/datalab-app/datalab-app.html
- sources/web/datalab/polymer/components/datalab-app/datalab-app.ts
- sources/web/datalab/polymer/components/datalab-files/datalab-files.html
- sources/web/datalab/polymer/components/datalab-files/datalab-files.ts
- sources/web/datalab/polymer/components/datalab-sessions/datalab-sessions.html
- sources/web/datalab/polymer/components/datalab-sessions/datalab-sessions.ts
- sources/web/datalab/polymer/components/shared-styles/shared-styles.html
- sources/web/datalab/polymer/modules/ApiManager.ts
- sources/web/datalab/polymer/modules/Utils.ts
This PR adds a paper-toast element that shows a connection error message whenever an XHR request fails with an unexpected code. The notification is dismissed whenever requests succeed.
A new custom even `NotificationEvent` can be fired on any child element, and is handled by the shell element `datalab-app` to show/hide the notification toast. Note this is currently not used anywhere, but it's part of this PR to open the discussion about the design of notifications.
> [Polymer UI] Show an error toast on connection errors

- sources/web/datalab/static.ts
Fixes https://github.com/googledatalab/datalab/issues/1442.
With this change, `/files` and `/files/path/to/file` are entirely different APIs. The first is just a view on the datalab shell entry point, the second is a file content service that's needed by Jupyter to download files. We might want to replace this for other backends than Jupyter.
> [Polymer UI] Fix broken /files/path for download

- sources/web/datalab/polymer/components/datalab-app/datalab-app.ts
- sources/web/datalab/polymer/components/datalab-files/datalab-files.ts
We should avoid using the global `WebComponentsReady` event for these things. It's enough to use the element's `ready` callback.
> [Polymer UI] Call resize handler on datalab-files ready

- sources/build.sh
- sources/web/build.sh
- sources/web/datalab/polymer/modules/ApiManager.ts
- sources/web/datalab/polymer/tslint.json
This adds `tslint` as a build step, the build will fail on errors from the linter.
Note you'll see a few warnings about using `console.log`, we should work on removing those shortly, then convert the `tslint` rule to error severity.
> [Polymer UI] Add tslint to the build

- sources/web/datalab/polymer/components/datalab-data/datalab-data.ts
- sources/web/datalab/polymer/modules/GapiManager.ts
- third_party/externs/ts/gapi/bigquery.d.ts
- third_party/externs/ts/gapi/gapi.d.ts
This PR implements some basic API calls to BigQuery. At the moment, these are only used from a sample debugging call that gets executed when the Search button is pressed, and which just logs to the console. The next step is to figure out how the user can supply the values that are passed to these functions, and how to display the results.
> Add initial BigQuery API access.

- sources/web/datalab/polymer/components/base-dialog/base-dialog.html
- sources/web/datalab/polymer/components/directory-picker-dialog/directory-picker-dialog.html
- sources/web/datalab/polymer/components/directory-picker-dialog/directory-picker-dialog.ts
I'll use this for the editor's new file save functionality. We could also choose to use it for copying/moving files with a new name.
Note the screenshot is only to show how it looks like with the feature enabled, but the default directory picker for copying/moving files does not have it on by default.
> [Polymer UI] Add optional input box to directory picker

- sources/web/datalab/polymer/components/datalab-app/datalab-app.html
- sources/web/datalab/polymer/components/datalab-app/datalab-app.ts
- sources/web/datalab/polymer/components/datalab-editor/datalab-editor.html
- sources/web/datalab/polymer/components/datalab-editor/datalab-editor.ts
- sources/web/datalab/polymer/components/datalab-files/datalab-files.ts
- sources/web/datalab/polymer/components/datalab-notification/datalab-notification.html
- sources/web/datalab/polymer/components/datalab-notification/datalab-notification.ts
- sources/web/datalab/polymer/modules/Utils.ts
This PR moves the markup and logic for the notification toast into a reusable element, and drops it in datalab-editor too, and uses it for the save functionality.
> [Polymer UI] Notification element, reuse in Editor

- sources/web/datalab/polymer/components/base-dialog/base-dialog.ts
- sources/web/datalab/polymer/components/datalab-editor/datalab-editor.html
- sources/web/datalab/polymer/components/datalab-editor/datalab-editor.ts
- sources/web/datalab/polymer/components/datalab-files/datalab-files.ts
- sources/web/datalab/polymer/components/directory-picker-dialog/directory-picker-dialog.ts
- sources/web/datalab/polymer/components/input-dialog/input-dialog.ts
- sources/web/datalab/polymer/modules/Utils.ts
This PR adds a directory picker to the editor when the user saves a new file.
The rest of this PR splits the dialog options per dialog type to enforce better type checking.
> [Polymer UI] New file save dialog for editor

- sources/web/build.sh
- sources/web/datalab/polymer/components/auth-panel/auth-panel.html
- sources/web/datalab/polymer/components/item-list/item-list.html
- sources/web/datalab/polymer/package.json
- sources/web/datalab/polymer/test/item-list-test.html
- sources/web/datalab/polymer/test/item-list-test.ts
- sources/web/datalab/polymer/test/toolbar-test.html
- sources/web/datalab/polymer/wct.conf.json
- third_party/externs/ts/polymer/polymer.d.ts
This PR adds tests for the item-list element. It also adds a `package.json` file at the root of the experimental UI directory for npm dependencies. Later on, we can download TS types automatically. For now, this manifest is used for the current build process, and to start tests. To build the front-end, you can navigate to sources/web/datalab/polymer and run `npm run build`. To start tests, you can do `npm test` from the same directory.
Testing the item-list is done in isolation, by feeding rows and columns arrays, and checking various interactions.
One gotcha here is for webcomponent tester to play nice with the Chrome devtools page, the sauce plugin needs to be disabled, otherwise it keeps refreshing the page, which is very annoying for debugging tests. See …
> [Polymer UI] <item-list> element tests

- tools/cli/commands/create.py
This commit changes the VMs created by the `datalab` tool
to use systemd services for running their containers rather
than using a kubelet.
This removes one rather large runtime dependency and in my
testing this cuts the VM startup time down by more than one
minute.
This fixes #1373
> Start the Datalab container using a systemd service

- sources/web/datalab/polymer/bower.json
- sources/web/datalab/polymer/components/datalab-data/datalab-data.html
- sources/web/datalab/polymer/components/datalab-data/datalab-data.ts
- sources/web/datalab/polymer/modules/GapiManager.ts
- third_party/externs/ts/gapi/bigquery.d.ts
This PR replaces the previous two-column layout with a single-column layout that has one text box for search terms and one list for heterogenous search results. It also wires in the BigQuery API so that the text in the search box is actually used to search for projects, datasets, and tables, which appear in the single results list with different icons. The details area on the right now has a Visibility icon that shows or hides that panel, same as the preview pane in the Files tab.
Turns out the BQ API is not really well suited for this approach, so it might take a while to make it work smoothly. Alternatively, I may try to figure out how to call Datauhb instead and see how far I can get with that.
> [Polymer] Data tab: single-column mixed-data format, BQ data

- sources/web/datalab/polymer/bower.json
- sources/web/datalab/polymer/components/datalab-data/datalab-data.html
- sources/web/datalab/polymer/components/datalab-data/datalab-data.ts
- sources/web/datalab/polymer/components/table-details/table-details.html
- sources/web/datalab/polymer/components/table-details/table-details.ts
- sources/web/datalab/polymer/modules/GapiManager.ts
- third_party/externs/ts/gapi/bigquery.d.ts
This PR adds a details pane to the Data First page that shows the selected table's details. One caveat is the schema only shows the columns in the first level, as I haven't yet added flattening (or some other solution) to the schema. This will be coming next.
> [Data First] Add Table Details Pane

- sources/web/datalab/polymer/components/datalab-editor/datalab-editor.ts
- sources/web/datalab/polymer/package.json
This PR adds some editor improvements:
- Error messages for load and save errors.
- Using DefinitelyTyped for TS typings instead of hard-coding.
> [Polymer UI] Editor improvements: errors, @types

- sources/web/datalab/polymer/components/auth-panel/auth-panel.ts
- sources/web/datalab/polymer/components/datalab-data/datalab-data.ts
- sources/web/datalab/polymer/modules/GapiManager.ts
- third_party/externs/ts/gapi/bigquery.d.ts
This PR changes `GapiManager` to add a dependency on `gapi.load` for all its operations. This way any of its public methods can be called at any point, and it would first make sure the module has loaded. The actual loading happens only once, then its resulting promise is returned every time it's called.
> Make sure gapi is loaded before making GapiManager operations

- sources/web/datalab/polymer/components/table-preview/table-preview.ts
- sources/web/datalab/polymer/test/table-preview-test.ts
To reduce the confusion if the data was created in a different time zone than the client.
> [Data First] Use UTC to convert date

- sources/web/datalab/polymer/components/datalab-data/datalab-data.ts
- sources/web/datalab/polymer/components/table-preview/table-preview.html
- sources/web/datalab/polymer/components/table-preview/table-preview.ts
- sources/web/datalab/polymer/modules/ApiManager.ts
- sources/web/datalab/polymer/modules/TemplateManager.ts
- sources/web/datalab/polymer/modules/Utils.ts
This is a POC for opening the selected BigQuery table in a template notebook. This adds a `TemplateManager` module that can be used to define new templates and can populate their properties and create a new notebook with the substituted content.
Note that for this to work, it needs the actual template notebook to exist on disk, currently fixed at the path `datalab/templates/<templateName>`. We can look into how to make this smoother in the future if we think this is a useful feature.
> [Data First] Notebook Templates + Open in Notebook

- .travis.yml
- sources/web/datalab/polymer/components/datalab-sessions/datalab-sessions.html
- sources/web/datalab/polymer/test/toolbar-test.html
- sources/web/datalab/polymer/test/toolbar-test.ts
This PR does the following:
- Fix <datalab-toolbar> tests, which were spitting out long messages because of the `ApiManager.getBasePath()` call, which was returning an HTML file because there is no server to handle it.
- Separate out these tests into their own file, and rewrite them to use events instead of timeouts so they're more reliable.
- Run the Polymer UI element tests on Travis.
> [Polymer UI] Fix <datalab-toolbar> tests, run on Travis

- sources/web/datalab/polymer/components/datalab-app/datalab-app.html
- sources/web/datalab/polymer/components/datalab-data/datalab-data.html
- sources/web/datalab/polymer/components/datalab-toolbar/datalab-toolbar.html
- sources/web/datalab/polymer/components/resizable-divider/resizable-divider.html
- sources/web/datalab/polymer/components/resizable-divider/resizable-divider.ts
- sources/web/datalab/polymer/test/index.html
- sources/web/datalab/polymer/test/resizable-divider-test.html
- sources/web/datalab/polymer/test/resizable-divider-test.ts
This adds a vertical divider element with two panes. This element can be dropped in the document with two child divs with slots "left" and "right", and is customizable to provide the initial split percentage, and the minimum pane size.
The element is not visible by default, but the mouse pointer will change to a resize cursor when the user hovers on it, so it's up to the elements using the divider to distinguish the two panes somehow to make the divider visible if needed, for example by adding a right border to the left pane, or a box-shadow to either pane. While it's being dragged, its background color changes slightly.
Future work for this element could be making the divider customizable.
> [Polymer UI] Divider element, use in Data First page

- sources/web/datalab/polymer/components/datalab-settings/datalab-settings.html
- sources/web/datalab/polymer/components/datalab-settings/datalab-settings.ts
- sources/web/datalab/polymer/index.dark.css
- sources/web/datalab/polymer/index.light.css
This PR implements a TODO to display a success message or an error message when the user presses the Update button in the Settings dialog to update the idle timeout.
Success:
Error, light theme:
Error, dark theme:
> [Polymer UI] Display idle-timeout-update status and errors in settings dialog

- sources/web/datalab/common.d.ts
- sources/web/datalab/polymer/components/datalab-toolbar/datalab-toolbar.html
- sources/web/datalab/polymer/components/datalab-toolbar/datalab-toolbar.ts
- sources/web/datalab/polymer/components/timeout-panel/timeout-panel.html
- sources/web/datalab/polymer/components/timeout-panel/timeout-panel.ts
- sources/web/datalab/polymer/modules/ApiManager.ts
- sources/web/datalab/polymer/modules/TimeoutManager.ts
- sources/web/datalab/polymer/test/TimeoutManager-test.html
- sources/web/datalab/polymer/test/TimeoutManager-test.ts
- sources/web/datalab/polymer/test/timeout-panel-test.html
- sources/web/datalab/polymer/test/timeout-panel-test.ts
- third_party/externs/ts/polymer/polymer.d.ts
This PR adds the timeout info display to the account menu in the Polymer UI. As in the old UI, clicking on the timer icon toggles whether the idle timeout is enabled. The timeout line is not displayed if the timeout has been disabled by setting the value to 0.
The value displayed in the timeout line counts down as the time until shutdown runs out, but the Polymer code currently is pretty aggressive about requesting info, such as asking for the list of sessions every minute, so in practice the timer will not count down until we fix that issue and make our code not ask for that kind of information when the corresponding tab is not visible.
Display when enabled:
Display when disabled by clicking on the timer icon:
> [Polymer UI] Add timeout panel to Account menu

- sources/web/datalab/polymer/components/item-list/item-list.ts
This generates a TSLint warning when compiling with recent version of tslint, because they are enforcing the 'no-inferrable-types' check specfied in
https://github.com/googledatalab/datalab/blob/master/sources/web/datalab/polymer/tslint.json#L36.
If this is intentional then the lint check should probably be changed to be a warning.
It would also be good if a local version of tslint was used to avoid these version differences.
> Drop trivially inferred type annotation.

- sources/web/datalab/polymer/components/datalab-app/datalab-app.ts
- sources/web/datalab/polymer/components/datalab-files/datalab-files.ts
- sources/web/datalab/polymer/components/datalab-sessions/datalab-sessions.ts
- sources/web/datalab/polymer/components/timeout-panel/timeout-panel.ts
This is a workaround to prevent unnecessary file/session refresh calls, since I couldn't get a `blur` event listener to work.
> Only refresh files/sessions if document has focus

- sources/web/datalab/polymer/components/datalab-sidebar/datalab-sidebar.html
- sources/web/datalab/polymer/components/datalab-sidebar/datalab-sidebar.ts
This PR adds a change such that once the user has visited the Data page by entering the URL for it, the Data tab shows up in the sidebar. It also fixes navigation for sidebar buttons when using the "/exp" mechanism to access the experimental UI pages.
> [Polymer UI] Display Data tab in sidebar once user has visited the Data page.

- sources/web/datalab/polymer/components/data-browser/data-browser.html
- sources/web/datalab/polymer/components/data-browser/data-browser.ts
- sources/web/datalab/polymer/components/datalab-app/datalab-app.html
- sources/web/datalab/polymer/components/datalab-sidebar/datalab-sidebar.html
- sources/web/datalab/polymer/components/datalab-sidebar/datalab-sidebar.ts
- sources/web/datalab/polymer/components/file-browser/file-browser.html
- sources/web/datalab/polymer/components/file-browser/file-browser.ts
- sources/web/datalab/polymer/modules/bigquery-file-manager/bigquery-file-manager.html
- sources/web/datalab/polymer/modules/bigquery-file-manager/bigquery-file-manager.ts
- sources/web/datalab/polymer/modules/file-manager-factory/file-manager-factory.ts
- sources/web/datalab/polymer/modules/gapi-manager/gapi-manager.ts
- sources/web/datalab/polymer/modules/jupyter-file-manager/jupyter-file-manager.html
- sources/web/datalab/polymer/polymer.json
- sources/web/datalab/polymer/test/file-browser-test.ts
- sources/web/datalab/static.ts
This PR starts the implementation of a new data browser to replace the current Data tab. This implementation uses the file-browser element along with the new BigQueryFileManager.
Since this does not yet implement the preview capability of the current Data tab, I am not yet replacing the current Data tab, but rather adding a new "/data2" path that links to this new data browser. Once it has the preview capability of the current Data tab, we can move it to /data and remove the old Data tab implementation.
Still TODO: remove the Status column, implement preview for tables, add a filter input field, display appropriate icons.
This example shows a project (jimmc-datalab) and a BigQuery dataset (test) with the two BigQuery tables in that dataset.
> Begin implementation of new Data browser, also BigQueryFileManager.

- sources/web/datalab/polymer/components/bread-crumbs/bread-crumbs.html
- sources/web/datalab/polymer/components/bread-crumbs/bread-crumbs.ts
- sources/web/datalab/polymer/components/file-browser/file-browser.html
- sources/web/datalab/polymer/components/file-browser/file-browser.ts
- sources/web/datalab/polymer/modules/jupyter-file-manager/jupyter-file-manager.ts
Breadcrumbs were getting too complex to keep inside the file browser element. Moving them into a separate element allows for more logic, such as hiding overflowing links to the left.
> Breadcrumbs as an element

- sources/web/datalab/idleTimeout.ts
- sources/web/datalab/static/idle-timeout.js
This is how the dialog now appears after the client detects that the server has shut down:
> Improve idle shutdown message, change minimum to 5m.

- sources/web/datalab/static/appbar.js
- sources/web/datalab/static/idle-timeout.js
- sources/web/datalab/static/notebook-list.js
This fixes the problem where some keys, such as 0, would not work in dialogs, such as the idle timeout field in the settings dialog, when used in a notebook tab.
> Disable Jupyter keyboard bindings in dialogs.

- sources/web/datalab/static/notebook-app.js
- sources/web/datalab/templates/nb.html
This PR adds a caret to the right of the kernel name in the notebook tool bar to indicate that there is a drop-down choicelist:
When the user selects an item from that choicelist to switch kernels, the kernel name is replaced by "..." until the new kernel connects.
> Add down-arrow by Kernel choice, show ellipsis when it is changing.

- sources/web/datalab/polymer/components/datalab-icons/datalab-icons.html
This can contain any SVG icons we want to add for upcoming work.
For now it only has one icon as an example, for BigQuery project.
> Add datalab-icons element for SVGs

- sources/web/datalab/polymer/modules/api-manager-factory/api-manager-factory.ts
Fixes https://github.com/googledatalab/datalab/issues/1581.
So far, we haven't needed the lazy loading optimization of ApiManager elements, removing it for now.
> Remove dynamic loading for ApiManager elements

- sources/web/datalab/polymer/components/datalab-data/datalab-data.ts
- sources/web/datalab/polymer/components/datalab-editor/datalab-editor.ts
- sources/web/datalab/polymer/components/datalab-settings/datalab-settings.ts
- sources/web/datalab/polymer/components/details-pane/details-pane.ts
- sources/web/datalab/polymer/components/file-browser/file-browser.ts
- sources/web/datalab/polymer/components/table-preview/table-preview.ts
- sources/web/datalab/polymer/modules/Utils.ts
- sources/web/datalab/polymer/modules/bigquery-file-manager/bigquery-file-manager.ts
- sources/web/datalab/polymer/modules/gapi-manager/gapi-manager.ts
- sources/web/datalab/polymer/modules/jupyter-api-manager/jupyter-api-manager.ts
This helps keep all logs in one place so we can later disable or redirect logs if necessary.
> Add Util.log class

- sources/web/datalab/polymer/components/data-browser/data-browser.html
- sources/web/datalab/polymer/components/datalab-data/datalab-data.html
- sources/web/datalab/polymer/components/shared-styles/shared-styles.html
Elements are display: inline'd by default, they need to be block or flex to fit our styles. The changes in `datalab-data` are just removing the wrapper `<data-container>` div.
Also, progressbar was getting a portion of its height because of flexbox.
> Layout fixes for data page and progressbar

- sources/web/datalab/polymer/components/bread-crumbs/bread-crumbs.ts
- sources/web/datalab/polymer/components/data-browser/data-browser.ts
- sources/web/datalab/polymer/components/datalab-app/datalab-app.html
- sources/web/datalab/polymer/components/datalab-app/datalab-app.ts
- sources/web/datalab/polymer/components/datalab-data/datalab-data.html
- sources/web/datalab/polymer/components/datalab-data/datalab-data.ts
- sources/web/datalab/polymer/components/datalab-page/datalab-page.html
- sources/web/datalab/polymer/components/datalab-page/datalab-page.ts
- sources/web/datalab/polymer/components/datalab-sessions/datalab-sessions.html
- sources/web/datalab/polymer/components/datalab-sessions/datalab-sessions.ts
- sources/web/datalab/polymer/components/datalab-terminal/datalab-terminal.html
- sources/web/datalab/polymer/components/datalab-terminal/datalab-terminal.ts
- sources/web/datalab/polymer/components/file-browser/file-browser.html
- sources/web/datalab/polymer/components/file-browser/file-browser.ts
This PR fixes the following:
- The `file-browser` element was being loaded automatically, even if has never been switched to. This was caused by the fallback attributes and logic.
- Page elements (e.g. files, sessions, terminal.. etc) now implement an interface that defines event handlers for resize, focus, and blur. This way they are more consistent, and don't need to add their own event listeners on document/window. There's unfortunately no way to enforce this within the HTML, so I put a comment there.
> Fix lazy loading of page elements

- sources/web/datalab/polymer/components/details-pane/details-pane.ts
- sources/web/datalab/polymer/components/file-browser/file-browser.html
- sources/web/datalab/polymer/components/file-browser/file-browser.ts
- sources/web/datalab/polymer/components/notebook-preview/notebook-preview.html
- sources/web/datalab/polymer/components/notebook-preview/notebook-preview.ts
- sources/web/datalab/polymer/components/preview-pane/preview-pane.html
- sources/web/datalab/polymer/components/preview-pane/preview-pane.ts
- sources/web/datalab/polymer/components/table-preview/table-preview.ts
- sources/web/datalab/polymer/components/text-preview/text-preview.html
- sources/web/datalab/polymer/components/text-preview/text-preview.ts
- sources/web/datalab/polymer/modules/bigquery-file-manager/bigquery-file-manager.ts
- sources/web/datalab/polymer/modules/drive-file-manager/drive-file-manager.ts
- sources/web/datalab/polymer/modules/file-manager/file-manager.ts
- sources/web/datalab/polymer/modules/jupyter-file-manager/jupyter-file-manager.ts
- sources/web/datalab/polymer/polymer.json
- sources/web/datalab/polymer/test/file-browser-test.ts
This PR refactors the details pane to generalize it so that it can display additional types, then adds in the existing table-preview pane so that we can show a preview of BigQuery tables in the file browser.
> Make table-preview work in file-browser details-pane.

- sources/web/datalab/polymer/components/file-browser/file-browser.ts
The last refactor brought about this bug, since we're now loading the root file by default in the breadcrumb array, indices should be shifted by one when clicked.
> Fix clicking breadcrumbs

- sources/web/datalab/polymer/modules/drive-file-manager/drive-file-manager.ts
- sources/web/datalab/polymer/modules/file-manager-factory/file-manager-factory.ts
- sources/web/datalab/polymer/modules/gapi-manager/gapi-manager.html
Double clicking an item from a drive file browser now executes the right action.
There's still some cleanup to do here; obtaining the editor/notebook urls can be extracted outside of the individual file managers, since most of it is repeated logic.
Note this won't work on the Jupyter-based notebook editor as of now, since it uses the new notebook fileId path, which needs to be supported by the notebook editor.
> Drive double click actions

- sources/web/datalab/polymer/modules/base-api-manager/base-api-manager.ts
- sources/web/datalab/polymer/modules/daas-api-manager/daas-api-manager.ts
- sources/web/datalab/polymer/modules/jupyter-api-manager/jupyter-api-manager.ts
- sources/web/datalab/polymer/modules/settings-manager/settings-manager.ts
Until we have a need to branch these off, all types of ApiManagers should use the same service urls. This way if we do need to change one or more we can just extend the base class.
> Use the same service urls for all ApiManagers

- containers/datalab/content/run.sh
- sources/web/datalab/metadata.ts
- sources/web/datalab/server.ts
To use the new metadata server, first create the docker network on which it will run:
```sh
docker network create -d bridge --internal --subnet=169.254.169.254/16 metadata
```
Then run the container:
```sh
docker run -it --rm --name=datalab \
--add-host="metadata.google.internal:169.254.169.254" \
-p 127.0.0.1:8081:8080 \
--env DATALAB_FAKE_METADATA_SERVER=true \
--env PROJECT_NUMBER=$(gcloud projects describe $(gcloud config get-value core/project) --format "value(projectNumber)") \
--env PROJECT_ID=$(gcloud config get-value core/project) \
datalab
```
And attach it to that network:
```sh
docker network connect --ip 169.254.169.254 metadata datalab
```
You can then push your local credentials to the container with:
```sh
curl -X POST \
-d "{\"account\": \"$(gcloud auth list --format …
```
> Add a fake metadata server that can be used to inject credentials

- sources/web/datalab/polymer/components/datalab-icons/datalab-icons.html
- sources/web/datalab/polymer/modules/bigquery-file-manager/bigquery-file-manager.ts
BQ Dataset in data browser:
BQ Table in data browser:
> Add icons for BigQuery datasets and tables.

- sources/web/datalab/polymer/modules/base-api-manager/base-api-manager.ts
- sources/web/datalab/polymer/modules/settings-manager/settings-manager.ts
Settings manager shouldn't care about basepath. For now the frontend server will serve those immediately, and this might change later.
> Skip basepath for settings requests

- sources/web/datalab/static/notebook-app.js
The codecell custom configurations were incorrectly placed in the notebook app's postload section, which was causing existing cells to load without line numbers (and other customizations), but new cells to load with them. The fix is to just move that block to preload.
Fixes #1604.
> Fix showing line numbers on notebook init

- test/notebook/test_spec.js
This should help with the notebook test flakiness. Reusing the same browser object meant navigating away from notebooks after running them, which often failed because of the confirmation popup, which in turn wasn't getting dismissed properly because of timing issues.
This PR creates a new browser for each notebook.
> Create a new browser instance for each test

- test/ui/test_spec.js
Minor render changes sometimes caused this. Raising to 1 until we find a better way to stabilize the ui tests, this will still catch big changes.
> Raise threshold for image diff

- sources/web/datalab/common.d.ts
- sources/web/datalab/config/settings.json
- sources/web/datalab/polymer/components/file-browser/file-browser.ts
- sources/web/datalab/polymer/test/file-browser-test.html
This PR makes drive the default file manager type if one is not specified in the app settings.
> Load file manager type from settings, default to drive if no setting provided

- sources/web/datalab/polymer/modules/drive-file-manager/drive-file-manager.ts
- sources/web/datalab/polymer/modules/jupyter-file-manager/jupyter-file-manager.ts
When we can load notebooks/files from a hosted Datalab instance using its Jupyter interface, we'll need to add these again appropriately.
> Remove basepath from notebook and editor urls

- sources/web/datalab/polymer/modules/drive-file-manager/drive-file-manager.ts
This filters the files displayed by the DriveFileManager to be just .ipynb and .txt files for now, and directories.
> Add file name filters in drive list

- sources/web/datalab/polymer/components/datalab-editor/datalab-editor.ts
This fixes a bug where loading files can take long enough that the initialization of the element misses it. Now the new file will be loaded on any change to the file id.
> Editor: Move loading file to observer

- sources/web/datalab/polymer/components/datalab-editor/datalab-editor.html
- sources/web/datalab/polymer/components/datalab-editor/datalab-editor.ts
- CodeMirror wouldn't render full height inside a flex container.
- Focus the editor after each button click and after content reload.
- Move progress bar under toolbar for clarity.
> Editor fixes

- sources/web/datalab/polymer/modules/gapi-manager/gapi-manager.ts
Popups aren't good web citizens.
Note that we'll need to whitelist our possible origins and redirect urls in order for this to work. If you're developing locally using your own oauth client ID, make sure `localhost:8081` (or whatever port you're using) is in the authorized origins, and `localhost:8081/*` is in the authorized redirect URIs.
> Use redirect instead of popup for gapi auth

- sources/web/datalab/polymer/bower.json
See https://github.com/PolymerElements/app-route/issues/192
and https://github.com/PolymerElements/app-route/pull/211/files
Polymer bug #192 is that query parameters specified in the URL get stripped off by app-location.
> Update app-route version to get fix for disappearing query parameters.

- sources/web/datalab/polymer/modules/file-manager/file-manager.ts
- sources/web/datalab/polymer/modules/gapi-manager/gapi-manager.ts
Empty template was missing a few arguments required by the parser.
> Fix empty notebook template

- sources/web/datalab/polymer/components/datalab-data/datalab-data.html
- sources/web/datalab/polymer/components/file-browser/file-browser.html
- sources/web/datalab/polymer/components/file-browser/file-browser.ts
- sources/web/datalab/polymer/components/resizable-divider/resizable-divider.html
- sources/web/datalab/polymer/components/resizable-divider/resizable-divider.ts
- sources/web/datalab/polymer/test/resizable-divider-test.html
- sources/web/datalab/polymer/test/resizable-divider-test.ts
* Use resizable divider in file-browser element
* Make divider always visible to give the user an affordance
* Update file-browser visibility button to work with resizable divider
* Allow right pane in file browser to be opened and closed either using the visibility icon or by sliding the divider
This is what the divider now looks like in the file browser. It changes to a slightly different shade when active. We can improve the visuals later.
> Use resizable divider on preview pane in file browser.

- sources/web/datalab/polymer/modules/drive-file-manager/drive-file-manager.ts
This switches to using the same querystring parameter `file` for the notebook editor that we use elsewhere.
> Use ?file querystring for file id

- .travis.yml
Travis isn't happy about the fact that we declare `node_js` to be the repo's language, then try to do `pip install`s. One fix is to change the language to `python`, but I found that using the `--user` option also fixes it, and I feel like this is a little cleaner.
For reference: https://github.com/travis-ci/travis-ci/issues/1705.
> Fix `pip install` errors on Travis

- sources/web/datalab/polymer/components/file-browser/file-browser.html
This makes the divider container in the file-browser full height.
Before:
After:
> Fix height problem for divider in file-browser.

- sources/web/datalab/polymer/components/auth-panel/auth-panel.html
- sources/web/datalab/polymer/modules/gapi-manager/gapi-manager.html
- sources/web/datalab/polymer/notebook.html
- sources/web/datalab/polymer/notebook.ts
- sources/web/datalab/polymer/polymer.json
This PR adds a notebook editor wrapper as an entry point, and a simple one-directional communication layer to listen for commands coming from the notebook editor. For now the only command it listens for is to upload user credentials.
> Add notebook app<->datalab app communication shim

- sources/web/datalab/polymer/components/file-browser/file-browser.html
Preview pane closed (uses the same icon as before):
Preview page open (uses the other icon to close the preview pane):
> Use visibility-off icon when preview pane is open.

- sources/web/datalab/polymer/components/file-browser/file-browser.html
- sources/web/datalab/polymer/components/file-browser/file-browser.ts
This PR changes the color of the file-browser visibility icon, which only shows when the preview pane is hidden, to the highlight color when a single item is selected in the list and that item is of a type that should show a preview when the pane is open. It does not actually generate the preview.
Nothing selected, showing visible icon without highlight (this is the same as previously):
One item selected (a notebook, for which we know how to do preview), showing highlighted visibility icon:
> Highlight the visibliity icon when preview is available.

- sources/web/datalab/polymer/components/datalab-terminal/datalab-terminal.html
- sources/web/datalab/polymer/components/datalab-terminal/datalab-terminal.ts
- sources/web/datalab/polymer/components/datalab-terminal/websocket.ts
Base path is needed to make the websocket connection to the backend vm.
This also renames the `WebSocketShim` class and clarifies its function in comments.
> Add basepath to websocket connection

- sources/web/datalab/polymer/notebook.html
- sources/web/datalab/polymer/notebook.ts
This change enables the notebook editor to send a message to the main app to ask for a notebook to be loaded. The notebook is loaded using the regular code path, using `FileManagerFactory`, and its contents and metadata are sent back over the iframe communication channel to the editor.
> Support loading notebooks for the editor using iframe postmessage

- sources/web/datalab/polymer/components/datalab-sessions/datalab-sessions.ts
- sources/web/datalab/polymer/components/file-browser/file-browser.html
- sources/web/datalab/polymer/components/file-browser/file-browser.ts
- sources/web/datalab/polymer/components/inline-details-pane/inline-details-pane.html
- sources/web/datalab/polymer/components/inline-details-pane/inline-details-pane.ts
- sources/web/datalab/polymer/components/item-list/item-list.html
- sources/web/datalab/polymer/components/item-list/item-list.ts
- sources/web/datalab/polymer/components/shared-styles/shared-styles.html
- sources/web/datalab/polymer/components/table-inline-details/table-inline-details.html
- sources/web/datalab/polymer/components/table-inline-details/table-inline-details.ts
- sources/web/datalab/polymer/components/table-preview/table-preview.html
- sources/web/datalab/polymer/components/table-preview/table-preview.ts
- sources/web/datalab/polymer/modules/bigquery-file-manager/bigquery-file-manager.ts
- sources/web/datalab/polymer/modules/file-manager/file-manager.ts
- sources/web/datalab/polymer/modules/gapi-manager/gapi-manager.ts
- sources/web/datalab/polymer/modules/utils/utils.ts
- sources/web/datalab/polymer/polymer.json
- sources/web/datalab/polymer/test/file-browser-test.ts
- sources/web/datalab/polymer/test/item-list-test.ts
- sources/web/datalab/polymer/test/table-inline-details-test.html
- sources/web/datalab/polymer/test/table-inline-details-test.ts
- third_party/externs/ts/gapi/bigquery.d.ts
This PR implements a generic inline-details mechanism in the file browser, and a specific implementation that shows a small number of data rows when the file is a BigQuery file. This currently shows 5 rows of data. If the table is too wide, it will include a horizontal scrollbar.
At the moment, the display of the inline details is using the same algorithm as the sidebar preview, which is that it shows up if the row is the only selected row. It should be pretty easy to change this later once we figure out what UX we want to use.
> Implement inline details showing BigQuery sample data in file browser

- sources/web/datalab/polymer/modules/file-manager-factory/file-manager-factory.ts
- sources/web/datalab/polymer/modules/github-file-manager/github-file-manager.html
- sources/web/datalab/polymer/modules/github-file-manager/github-file-manager.ts
This just implements the happy path for browsing github projects and reading files. It doesn't check for errors and it doesn't attempt to deal with paging. The default page size is 30 items, which can be bumped up to 100 with a query parameter. But as is, it can be used with the file browser to browse github projects and repositories and to open text files and notebooks.
> Implement github file manager.

- containers/datalab/run.sh
- sources/web/datalab/polymer/components/datalab-app/datalab-app.html
- sources/web/datalab/polymer/components/datalab-docs/datalab-docs.html
- sources/web/datalab/polymer/components/datalab-docs/datalab-docs.ts
- sources/web/datalab/polymer/components/datalab-sidebar/datalab-sidebar.html
- sources/web/datalab/polymer/polymer.json
- sources/web/datalab/static.ts
The Docs page appears in the sidebar and loads the docs from Github.
> Add a Docs page

- sources/web/datalab/polymer/modules/drive-file-manager/drive-file-manager.ts
If the backend isn't returning any sessions or breaking for some reason, file loading should still work.
> Swallow sessions errors when fetching files

- sources/web/datalab/polymer/components/resizable-divider/resizable-divider.html
This fixes a bug where the file list overlaps with the filename field when the dialog is not very tall.
Before:
After:
> Fix height problem on file picker dialog.

- sources/web/datalab/polymer/modules/drive-file-manager/drive-file-manager.ts
Directories will still get their icon from drive to keep using the shared icon, but all files now show with the default file icon.
> Show drive files with the default file icon

- sources/web/datalab/common.d.ts
- sources/web/datalab/config/settings.json
- sources/web/datalab/polymer/components/datalab-app/datalab-app.html
- sources/web/datalab/polymer/components/datalab-app/datalab-app.ts
- sources/web/datalab/polymer/components/datalab-icons/datalab-icons.html
- sources/web/datalab/polymer/components/file-browser/file-browser.html
- sources/web/datalab/polymer/components/file-browser/file-browser.ts
- sources/web/datalab/polymer/components/shared-styles/shared-styles.html
- sources/web/datalab/polymer/modules/drive-file-manager/drive-file-manager.ts
- sources/web/datalab/polymer/modules/file-manager-factory/file-manager-factory.ts
- sources/web/datalab/polymer/test/file-browser-test.ts
This PR adds the ability to switch the file browser's source using a dropdown. In order to achieve this, it does the following:
- Adds an app setting for the list of supported file sources, which gets read on startup.
- Adds icons for: local disk (jupyter), drive, bigquery, and github.
- Adds a dropdown, similar to the file browser's toolbar dropdowns that appear when the window is too narrow. In this it also fixes an issue where the dropdown doesn't dismiss after clicking a button, by listening on the blur event.
- Adds a `SharedDriveFileManager` that extends `DriveFileManager` and changes the gapi query appropriately.
- Cleans up the `FileManagerFactory`'s methods for getting and converting file manager types.
The dropdown appears as a single unselectable div when there's only one …
> Add file source dropdown to file browser

- sources/web/datalab/polymer/notebook.ts
An error object will break `postMessage`.
> Send stringified errors using postMessage

- sources/web/datalab/polymer/components/datalab-sessions/datalab-sessions.html
- sources/web/datalab/polymer/components/datalab-sessions/datalab-sessions.ts
This change tries to get the file manager from the session path if it's a valid DatalabFileId, and get the file's name and icon from that, otherwise defaults to the old behavior.
> Get session file names from their file managers

- containers/base/Dockerfile
- containers/base/Dockerfile.py2
- sources/web/datalab/package.json
https://github.com/websockets/ws/issues/778 can cause ws to raise, terminating the python runtime.  Upgrading ws avoids this.
b/66429362
> Update to using ws@1.1.4 to avoid websockets/ws:778

- sources/web/datalab/polymer/components/file-browser/file-browser.ts
In commit d59029c I removed some code in file-browser _getFileIdFromProperty, which caused the fileId from the Data tab to be copied to the Files tab and vice-versa. This PR fixes that problem.
> Fix recent bug causing cross-talk between Data and Files locations.

- sources/web/datalab/polymer/components/file-browser/file-browser.ts
- sources/web/datalab/polymer/modules/drive-file-manager/drive-file-manager.ts
- sources/web/datalab/polymer/modules/jupyter-file-manager/jupyter-file-manager.ts
- sources/web/datalab/polymer/test/file-browser-test.ts
This PR solves the following:
- Listing files used to block on listing sessions, so that file status can be populated. This PR separates these too, loading files first, then adding their status.
- Removes code duplication around listing files/sessions.
- Fixes a bug where Drive files status weren't showing because the session ids changed to include the full `DatalabFileId` strings.
> Do not block on listing sessions when listing files

- sources/web/datalab/polymer/components/notebook-preview/notebook-preview.ts
Depending on the notebook editor, cell source might be a string or an array of strings.
> Proper array -> string conversation for cell source

- sources/web/datalab/polymer/components/item-list/item-list.html
These stopped working after adding an extra div for each row, making all actual `.row` elements even.
> Fix alternating row colors

- sources/web/datalab/idleTimeout.ts
This allows Datalab to start up successfully without requiring that
user settings already exist, allowing the user content directory
to be specified lazily.
> Allow idle timeout process to be permanently disabled by env variable.

- containers/datalab/run.sh
- sources/web/datalab/jupyter.ts
- sources/web/datalab/settings.ts
This will support attaching a home directory on another disk after
start.
> Allow datalab and jupyter to start up when missing a home dir.

- tools/cli/commands/creategpu.py
GPU instances use an Ubuntu based host OS, and so include a lot
of installed packages that we neither need nor use. This commit
extends the startup script for GPU instances to remove (some)
of those unused packages.
This issue does not apply to non-GPU instances, as those use
Container Optimized OS for their host image, and it has already
been pruned down to only include the software needed to run
Docker containers.
To start with, this cleanup step just removes dnsmasq.
> Remove unused packages as part of the startup script.

- sources/web/datalab/polymer/modules/gapi-manager/gapi-manager.ts
Until we have a paging mechanism, use the maximum page size for the Drive file listing, 1000.
> Increase Drive list page size from 30 to 1000

- sources/web/datalab/polymer/editor.html
- sources/web/datalab/polymer/notebook.html
After bundling resources, datalab-app is the only shell, and all its dependencies get inlined into it. In order to get the shared dependencies, other entrypoints, e.g. editor and notebook, need to take datalab-app as a dependency.
> Take datalab-app as a dependency for all entrypoints

- sources/web/datalab/polymer/components/bread-crumbs/bread-crumbs.html
This only shows on the copy/move dialog, since it uses default z-index.
> Fix breadcrumbs height css issue

- sources/web/datalab/polymer/components/file-browser/file-browser.ts
This PR checks and sets the fetching busy status of the file browser on all async operations.
It also removes loading sessions when in the small mode for the copy/move dialog.
> File browser busy loading fixes

- sources/web/datalab/metadata.ts
Before this change, google-auth-library-python can refresh a GCE metadata
token against the fake at most once:
* on the first attempt, it uses the name `default`
* once that response is received, it updates its service account name in the
credentials object
* a second attempt uses the updated name in the URL.
The fix is trivial (just check for the second path).
PTAL @ojarjur
> Add another path to the metadata fake.

- sources/web/datalab/common.d.ts
- sources/web/datalab/config/settings.json
- sources/web/datalab/metadata.ts
This makes it possible to configure the GCE metadata fake to serve on a
different host/port combination; the primary goal is to make it possible to
use the metadata service locally without the related Docker network
configs. (Without this, server startup will fail attempting to bind to
`metadata.google.internal`.)
PTAL @ojarjur
> Make the fake metadata address configurable.

- sources/web/datalab/polymer/modules/api-manager/api-manager.ts
This request should not be cached because it could change at any point during a client's session.
> Use no-cache when getting the basepath

- sources/web/datalab/polymer/components/datalab-app/datalab-app.html
- sources/web/datalab/polymer/components/datalab-app/datalab-app.ts
- sources/web/datalab/polymer/components/datalab-docs/datalab-docs.html
- sources/web/datalab/polymer/components/datalab-sessions/datalab-sessions.ts
- sources/web/datalab/polymer/components/datalab-sidebar/datalab-sidebar.html
- sources/web/datalab/polymer/components/datalab-sidebar/datalab-sidebar.ts
- sources/web/datalab/polymer/components/file-browser/file-browser.ts
- sources/web/datalab/polymer/editor.html
- sources/web/datalab/polymer/editor.ts
- sources/web/datalab/polymer/index.html
- sources/web/datalab/polymer/modules/drive-file-manager/drive-file-manager.ts
- sources/web/datalab/polymer/modules/file-manager/file-manager.ts
- sources/web/datalab/polymer/modules/github-file-manager/github-file-manager.ts
- sources/web/datalab/polymer/modules/jupyter-file-manager/jupyter-file-manager.ts
- sources/web/datalab/polymer/modules/template-manager/template-manager.ts
- sources/web/datalab/polymer/modules/utils/utils.ts
- sources/web/datalab/polymer/notebook.html
- sources/web/datalab/polymer/notebook.ts
- sources/web/datalab/static.ts
This PR changes the way the new UI handles file paths in navigation and in the notebook editor, by making the file path part of the page URL, which allows relative links to work resolve properly.
> Use URL paths for file id, enable relative file paths

- containers/base/Dockerfile
Without this change ./build.sh errors out late in the game with the error below, presumably because a new transitive dependency requires compilation but the clean-up stanza has already removed gcc.
```
Running setup.py install for setproctitle: started
Running setup.py install for setproctitle: finished with status 'error'
Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-E4jhlY/setproctitle/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-dXyR7P-record/install-record.txt --single-version-externally-managed --compile:
running install
running build
running build_ext
building 'setproctitle' extension
creating build …
```
> Move clean-up to the bottom of base/Dockerfile

- containers/base/Dockerfile
This makes `!apt update` from within a notebook (in a datalab VM) exit 0 instead of non-0 with a GPG signature verification failure warning.
> Install keyrings for signature verifications

- containers/base/Dockerfile
The cleanup step needs to be performed in the same Docker `RUN` command in order to actually remove the files from the Docker image (otherwise, they just wind up hidden in a subsequent layer).
We'll move the cleanup code back to where it was, and then take out the offending line which was causing the build issues.
> Revert "Move clean-up to the bottom of base/Dockerfile"

- sources/web/datalab/polymer/components/data-browser/data-browser.html
- sources/web/datalab/polymer/components/datalab-docs/datalab-docs.html
- sources/web/datalab/polymer/components/file-browser/file-browser.html
- sources/web/datalab/polymer/components/file-browser/file-browser.ts
- sources/web/datalab/polymer/components/inline-details-pane/inline-details-pane.html
- sources/web/datalab/polymer/components/inline-details-pane/inline-details-pane.ts
- sources/web/datalab/polymer/components/item-list/item-list.ts
- sources/web/datalab/polymer/components/preview-pane/preview-pane.html
- sources/web/datalab/polymer/components/table-inline-details/table-inline-details.ts
- sources/web/datalab/polymer/components/table-preview/table-preview.html
- sources/web/datalab/polymer/components/table-preview/table-preview.ts
The button in the toolbar is only enabled when there is exactly one selected item displayed, and it is a BigQuery table.
Before:
After:
> Move open-in-notebook button to new Data toolbar.

- sources/build.sh
- sources/web/datalab/package.json
- sources/web/datalab/polymer/package.json
This reduces the number of global dependencies that build environments need to have, also unifying the build errors contributors will get.
We can't yet take out `typescript` since it's needed for the node.js app, but we should at some point.
> Use locally installed tsc/tslint to avoid build environment differences

- containers/datalab/content/setup-env.sh
This change modifies the container startup process to reuse the "CLOUDSDK_CONFIG" environment variable if it has already been set.
This allows the user launching the container to change that value to something else, and we will then honor that specified value.
> Allow setting the CLOUDSDK_CONFIG variable

- sources/web/datalab/polymer/components/file-browser/file-browser.ts
This PR changes the default starting location of the Data tab to be the bigquery-public-data project. This is what it will display when the user first clicks the Data tab (or enters the /data URL).
> Set default Data tab start location to bigquery-public-data project.

- sources/web/datalab/polymer/components/resizable-divider/resizable-divider.html
- sources/web/datalab/polymer/components/resizable-divider/resizable-divider.ts
This PR styles the divider to have no background color, and show a three-dot indicator for the resize. The right pane now has a shaded background color and an inset box-shadow.
> Resizable divider styling

- sources/web/datalab/polymer/components/data-browser/data-browser.html
- sources/web/datalab/polymer/components/data-browser/data-browser.ts
- sources/web/datalab/polymer/components/file-browser/file-browser.ts
- sources/web/datalab/polymer/modules/bigquery-file-manager/bigquery-file-manager.ts
- sources/web/datalab/polymer/modules/file-manager-factory/file-manager-factory.ts
... and use it in the Data browser to allow seeing public dataset projects separately from the user's projects.
As in the Files browser, the file manager, which used to display only BigQuery, is now a dropdown list that includes BigQuery and Public Datasets.
> Add BigQueryPublicFileManager.

- sources/web/datalab/polymer/modules/gapi-manager/gapi-manager.ts
This is needed because the URL requiring the redirect can be any arbitrary path, now that file paths are part of the URL.
> Use host root for redirect URL

- sources/web/datalab/polymer/components/datalab-sidebar/datalab-sidebar.html
- sources/web/datalab/polymer/components/datalab-sidebar/datalab-sidebar.ts
Previously, the Data tab would only appear after the user manually visited the /data page. With this change, the Data tab is always visible.
> Make Data tab no longer be hidden.

- sources/web/datalab/polymer/templates/BigQueryTableOverview.ipynb
Use one instead of two cells to execute the query in table overview template.
> Use one cell for bq query in table overview template

- sources/web/datalab/polymer/components/datalab-app/datalab-app.ts
Datalab app was using an outdated name, so focus wasn't triggered when the user switches to the page.
> Fix focus handler name

- sources/web/datalab/polymer/components/shared-styles/shared-styles.html
`center` doesn't work for all cases on `paper-button`, especially with long inner text, such as the "Open in Notebook" button.
> Fix toolbar-button style

- sources/web/datalab/polymer/components/datalab-app/datalab-app.html
- sources/web/datalab/polymer/components/table-inline-details/table-inline-details.ts
- sources/web/datalab/polymer/modules/gapi-manager/gapi-manager.ts
- sources/web/datalab/polymer/modules/template-manager/template-manager.ts
- sources/web/datalab/polymer/modules/utils/utils.ts
- sources/web/datalab/polymer/notebook.html
- sources/web/datalab/polymer/notebook.ts
- third_party/externs/ts/polymer/polymer.d.ts
This PR makes populating template-based notebooks take place in a new tab as soon as the user picks a location for the notebook. The template name and parameters are sent as querystring parameters, and the notebook is populated and saved in the newly created tab, while showing a toast that says "Creating notebook.." This toast then disappears and the page is redirected to open the new notebook.
This does not get blocked by popup blockers, while also keeping the focus on the newly created notebook.
The PR takes the opportunity to refactor the way templating works around resource path resolution. Now the resolution is a simple `Utils` call, instead of keeping around a reference of some Polymer element.
> Populate template notebooks in a new tab

- sources/web/datalab/polymer/components/file-browser/file-browser.ts
- sources/web/datalab/polymer/modules/bigquery-file-manager/bigquery-file-manager.ts
- sources/web/datalab/polymer/modules/drive-file-manager/drive-file-manager.ts
- sources/web/datalab/polymer/modules/file-manager/file-manager.ts
- sources/web/datalab/polymer/modules/github-file-manager/github-file-manager.ts
- sources/web/datalab/polymer/modules/jupyter-file-manager/jupyter-file-manager.ts
- sources/web/datalab/polymer/modules/utils/utils.ts
- sources/web/datalab/polymer/test/file-browser-test.ts
- sources/web/datalab/polymer/test/table-inline-details-test.ts
With this change, the file browser does not need to look up backends to get the files' running status. The session status can now only be viewed in the Sessions page.
> Remove file status

- .gitignore
.DS_Store for macOS development, package-lock.json for users with node >= 5.0.0.
> More ignored patterns

- sources/web/datalab/common.d.ts
- sources/web/datalab/config/settings.json
- sources/web/datalab/polymer/components/datalab-toolbar/datalab-toolbar.html
- sources/web/datalab/polymer/components/datalab-toolbar/datalab-toolbar.ts
- sources/web/datalab/polymer/modules/settings-manager/settings-manager.ts
- sources/web/datalab/polymer/modules/utils/utils.ts
This PR disables the timeout by default. With this change, there are no more `/api/basepath` requests until a backend is actually needed, such as when browsing the list of sessions, terminals, or opening a notebook.
> Add gated features, disable timeout

- sources/web/datalab/polymer/components/datalab-app/datalab-app.html
It looks to me like there is a problem related to either the ordering or the number of file loads for included files. The symptom is that Chrome hangs with a status line such as "waiting for <some host>". This change seems to reduce the frequency of that problem for me - and it puts the link lines in the correct alphabetical order anyway.
> Move template-manager line to the end to fix hang problem.

- sources/web/datalab/wsHttpProxy.ts
- third_party/externs/ts/node/node.d.ts
This adds the ability to transfer binary data over the HTTP over WebSocket proxy. It also adds a few more fields to allow generating complete browser Response objects with the result.
Binary transfer is enabled by the requester for backwards compat.
> Enable binary transfer over wsHttpProxy.

- tools/cli/commands/connect.py
- tools/cli/commands/create.py
- tools/cli/commands/creategpu.py
- tools/cli/commands/utils.py
- tools/cli/datalab.py
Some time between flake8 version 3.3 and 3.5 it became an error to have a bare except statement, which caused our builds to break. This change silences those errors.
> Silence flake8 complaints about bare except.

- sources/build.sh
- sources/web/build.sh
- sources/web/datalab/package.json
- sources/web/datalab/polymer/package.json
This PR follows up on https://github.com/googledatalab/datalab/pull/1731 to move more build dependencies to `package.json` instead of requiring them to have been installed globally.
> Move build dependencies to be installed by npm instead of requiring global binaries

- sources/web/datalab/polymer/components/auth-panel/auth-panel.html
- sources/web/datalab/polymer/components/auth-panel/auth-panel.ts
We're currently not using this, and we don't yet have a way of storing/getting the user's preferred project.
> Remove project status from auth panel

- sources/web/datalab/static/datalab.css
Fixes https://github.com/googledatalab/datalab/issues/1443.
> Use mono-space font in help pane

- sources/web/datalab/common.d.ts
- sources/web/datalab/config/settings.json
- sources/web/datalab/polymer/components/datalab-editor/datalab-editor.ts
- sources/web/datalab/polymer/components/datalab-toolbar/datalab-toolbar.html
- sources/web/datalab/polymer/components/datalab-toolbar/datalab-toolbar.ts
- sources/web/datalab/polymer/components/file-browser/file-browser.ts
- sources/web/datalab/polymer/modules/gapi-manager/gapi-manager.ts
- sources/web/datalab/polymer/modules/utils/utils.ts
- sources/web/datalab/polymer/test/datalab-toolbar-test.ts
- sources/web/datalab/polymer/test/file-browser-test.ts
Until we have a good user settings story, this disables the option, unless it's explicitly enabled in the app settings. This change explicitly enables it to keep the current behavior.
This required the optional oauth2 client id to move from user settings to app settings in order not to break the local development story.
> Disable user settings by default

- sources/web/datalab/polymer/editor.html
- sources/web/datalab/polymer/notebook.html
Editor script load was failing because of the missing base_url placeholder.
> Fix editor script load issue

- sources/web/datalab/metadata.ts
This fixes a race condition that can occur if the process.env.DATALAB_GIT_AUTHOR environment variable is not set.
> Initialize the fake metadata account to be empty

- tools/cli/commands/connect.py
This builds on the change from #1759 and extends it so that the printed command
can be directly copied and pasted in order to reconnect.
This introduces the potential to give the user a command to run that won't actually
work (e.g. if their connection failed due to the specified port being unavailable).
To prevent that risk, I've changed the reconnection message so that we only print
it if the initial connection succeeded.
This closes #1519
> Extend the reconnection message with more details.

- sources/web/datalab/polymer/components/auth-panel/auth-panel.html
- sources/web/datalab/polymer/components/auth-panel/auth-panel.ts
- sources/web/datalab/polymer/modules/gapi-manager/gapi-manager.ts
This rolls back a piece of #1777. The key issue is that we need to use a 'then' on the return from api.auth2.init before we grab the currentUser to avoid sometimes getting a null result.
The user-visible symptom of this problem is an error dialog saying 'Cannot read property getEmail of undefined.'
I also added code to catch and display an auth error from this updated code. Here is what that looks like for a bad client ID:
> Fix race condition in gapi code.

- .travis.yml
- sources/web/datalab/polymer/bower.json
- sources/web/datalab/polymer/package.json
Yesterday, a new version of web-component-tester (6.4.0) was released,
and after that release our selenium tests (which run inside of
web-component-tester) started hanging forever.
Pinning to the older version seems to fix this issue.
There is one subtle issue where polymer_cli was installing the latest
version of web-component-tester, so the tests still failed even if we
later installed the older version. We avoid that issue by installing
the older version of web-component-tester before polymer_cli.
> Pin web-component-tester to version 6.3.x

- sources/web/datalab/polymer/modules/gapi-manager/gapi-manager.ts
Otherwise this will endlessly refresh loop if no consent is given.
> Require a consent prompt when asking for extra scopes.

- sources/web/datalab/polymer/modules/template-manager/template-manager.ts
I'm taking a deliberatly aggressive approach here since we don't
currently have a use case where any special characters should be
needed in these strings.
> Sanitize param values sent to the template creator.

- sources/web/datalab/polymer/modules/github-file-manager/github-file-manager.ts
These fields are not set by the github blob API.
Before (since the blob API change):
After this fix (restored to how it used to be):
> Restore name and path in github DatalabFile fields.

- sources/web/datalab/polymer/components/file-browser/file-browser.ts
- sources/web/datalab/polymer/test/file-browser-test.ts
Looks like we dropped displaying the Name column in the header at some point.
> Add missing Name column, + regression test

- .travis.yml
- sources/web/datalab/polymer/test/file-browser-test.ts
Looks like an outstanding issue on web component tester: https://github.com/Polymer/web-component-tester/issues/189. The fix for now is to wait for web components to load before running the test, no other changes are made.
Disable white space diffing for this PR.
> Fix file-browser tests for firefox, enable firefox

- sources/web/datalab/polymer/components/file-browser/file-browser.html
- sources/web/datalab/polymer/components/file-browser/file-browser.ts
- sources/web/datalab/polymer/test/file-browser-test.ts
The Delete operation already supports multiple files, this PR just enables it in the UI when more than one file is selected.
> Enable Delete when multiple files selected

- sources/web/datalab/polymer/components/item-list/item-list.html
This helps with rendering very large lists of items (see [docs](https://www.polymer-project.org/1.0/docs/devguide/templates#large-list-perf)).
A better fix is to use iron-list to do virtual scrolling, but this removes some flexibility from the design of the item-list component, which right now is capable of displaying preview data inlined with the list item.
> Enable chunked mode for item-list by default

- sources/web/datalab/polymer/bower.json
- sources/web/datalab/polymer/components/file-browser/file-browser.ts
- sources/web/datalab/polymer/components/item-list/item-list.html
- sources/web/datalab/polymer/components/item-list/item-list.ts
- sources/web/datalab/polymer/test/item-list-test.ts
This PR adds filtering capability to item list. The filter only works on the first column of the item list for now, which covers the common cases. We can expand on this later as needed.
In order to do this, I switched the way we get the selection index to use the clicked item's true order in the original list, as opposed to its order in the rendered (filtered) list.
This design isn't final, it's just a rough way to get filter functionality into the UI. It's a toggle that shows up next to the first column in the header, which on click shows an input box underneath the header. Items will change as the user types in that box, without needing to hit Enter. Filtering is case-insensitive for now to simplify the implementation and the UI.
[_Tooltip when hovering over filter icon_]
[_Clicking …
> Add filter to item-list

- sources/web/datalab/polymer/components/file-browser/file-browser.ts
- sources/web/datalab/polymer/components/item-list/item-list.html
- sources/web/datalab/polymer/components/shared-styles/shared-styles.html
- sources/web/datalab/polymer/modules/bigquery-file-manager/bigquery-file-manager.ts
- sources/web/datalab/polymer/modules/drive-file-manager/drive-file-manager.ts
- sources/web/datalab/polymer/modules/file-manager/file-manager.ts
- sources/web/datalab/polymer/modules/github-file-manager/github-file-manager.ts
- sources/web/datalab/polymer/modules/jupyter-file-manager/jupyter-file-manager.ts
- sources/web/datalab/polymer/modules/utils/utils.ts
- sources/web/datalab/polymer/test/file-browser-test.ts
- sources/web/datalab/polymer/test/table-inline-details-test.ts
- third_party/externs/ts/gapi/drive.d.ts
This PR allows each file manager to define its own set of columns to be displayed by a file-browser element. This enables the file browser to then display different columns per source, as a precursor to implementing sort over columns.
A significant portion of this PR is cleanup to the different DatalabFile extended class constructors to make things consistent and easy to extend.
Examples:
[_Drive view now shows last modified and owner columns_]
[_BigQuery view now changes the column name based on the browser level_]
> Expose columns in file browser from file manager

- sources/web/datalab/polymer/components/delete-dialog/delete-dialog.html
- sources/web/datalab/polymer/components/delete-dialog/delete-dialog.ts
- sources/web/datalab/polymer/components/file-browser/file-browser.ts
The delete dialog previously when deleting a single item:
After this fix:
> Fix pluralization for single items in delete dialog.

- sources/web/datalab/polymer/components/file-browser/file-browser.ts
- sources/web/datalab/polymer/modules/drive-file-manager/drive-file-manager.ts
- sources/web/datalab/polymer/modules/file-manager/file-manager.ts
- sources/web/datalab/polymer/modules/github-file-manager/github-file-manager.ts
If you try to create a file with name ending in .ipynb you will see this:
If you try to create a file that does not include .txt in the name, you will see this:
> Only allow valid names for new files.

- sources/web/datalab/polymer/components/resizable-divider/resizable-divider.html
Since we're using a css trick to show the three vertical dots, font size must be fixed.
> Fix font-size for divider

- sources/web/datalab/static/codemirror/mode/sql.js
This PR adds a lineComment value to the %%sql cell mode.  The effect of this is to allow for toggling comments with the Ctrl+/ keyboard shortcut via the CodeMirror comment.js addon.
> (Issue #1020) Support toggling comments for %%sql cells.

- sources/web/datalab/polymer/modules/gapi-manager/gapi-manager.ts
drive.file and drive.readonly.metadata are subsumed by drive so are not needed.
> Request fewer Drive scopes.

- sources/web/datalab/polymer/modules/drive-file-manager/drive-file-manager.ts
Previous to this bug fix, if you use browser reload on the main page of Drive files, it would show the root folder's Drive ID in the breadcrumbs. This reverts it to the previous correct behavior of only showing "/" in the breadcrumbs when viewing the root Drive folder, even if you explicitly Drive root folder by id in the URL.
> Fix bug where root id appeared in breadcrumbs.

- sources/web/datalab/server.ts
Prior to this change, if you set a base path to `/foo/bar/`, then
requests to `/foo/bar/` would resolve to requests to the root path,
but requests to `/foo/bar` would result in a 404 error.
This would happen even if you set the base path to `/foo/bar`, as
the server normalizes the base path to include leading and trailing
slashes (to avoid accidental collisions with things like
`/foo/barbutnotreally`).
This change fixes that issue by explicitly checking for the case
that the request path matches the base path without the trailing slash.
> Support base paths without the trailing slash.

- containers/datalab/run.sh
This change is required in order to be able to run this script in the background.
> Don't use -it when starting container without a terminal.

- sources/web/datalab/static/datalab.css
- sources/web/datalab/templates/tree.html
Fixes https://github.com/googledatalab/datalab/issues/1815.
Interactive elements aren't allowed inside of `button`s, this is why this fails on Firefox. This PR switches the container to `label`.
> Fix upload button on Firefox

- containers/base/Dockerfile
Removing these files prevents installation of other packages (e.g r-base).
> Don't delete /var/lib/dpkg/info/*

- containers/base/Dockerfile
> pip: remove temporary file used during installation

- tools/cli/commands/list.py
This change updates the `datalab list` command to incorporate the
`--zones` argument into the generated filter that is passed in to
the `gcloud compute instances list` command instead of forwarding
the `--zones` argument directly.
This is being changed because gcloud recently deprecated the `--zones`
flag in their tool, so users are now getting confusing deprecation
warnings from gcloud when they run `datalab list` with a `--zones`
argument.
> Switch from using the --zones flag to the "zone:(...)" filter

- tools/cli/commands/create.py
Configure docker with GCR credentials to access private repositories inside.
Useful for using customized images.
Tested with both public and private repositories.
Resolves #1822
Contributed under the @tapad CLA.
> Support pulling from private gcr repositories

- sources/web/datalab/polymer/test/test-utils.ts
The declaration is redundant after including `chai`. It's inconsistent with the chai declaration, which allows the `message` parameter to be undefined.
Fixes #1835.
> Remove unneeded assert typescript declaration

- sources/web/datalab/static/datalab.css
Only the element's functionality is needed, the label is the click target.
> Hide the input element for file upload

- sources/web/datalab/reverseProxy.ts
This change fixes a bug in the reverse proxy where the base path
(if set) was not being passed to other local servers to which
we proxied.
In particular, this meant the ungit UI could not be loaded if the
base path was set.
> Fix a bug in passing the base path to proxied servers.

- sources/web/datalab/polymer/components/auth-panel/auth-panel.ts
.. in order to send the user back to the oauth login page.
We still need some more work here to detect user sign in status and redirect to oauth page before any HTML is rendered.
> Reload the window after signing out

- tools/cli/commands/create.py
This change adds a check to the Datalab instance startup script where
the swapfile creation/usage is prevented if the free disk space is not at
least 10x the size of memory.
This is the first step towards addressing #1839, but the full issue
won't be fixed until we also provide a way to turn off swap entirely
for users who do not want it.
> Don't create a swapfile if there is not enough disk space.

- sources/web/datalab/polymer/components/datalab-toolbar/datalab-toolbar.html
In some cases the toolbar buttons would have pointer-events set to none by the Polymer template. This makes sure they're clickable.
> Make sure pointer-events are enabled on toolbar

- tools/cli/commands/create.py
- tools/cli/commands/creategpu.py
This change adds an optional `--no-swap` flag that can be added to
either the `create` or `beta create-gpu` commands to disable swap
on the created VM.
This fixes #1839
> Add a flag to the create command to disable swap.

- .travis.yml
If Polymer tests fail within the timeout (2m), the exit code that is actually returned is that of "tee", which is always zero, so the failure is never reported. This fixes that by reporting the first exit status in the pipe, which is that of the test command.
> Report actual test exit code instead of "tee"

- sources/web/datalab/polymer/notebook.ts
- sources/web/datalab/server.ts
- sources/web/datalab/static.ts
This PR fixes a few things with the experimental UI:
- When creating a new notebook, we now redirect to a new page, serving notebook.js, that does the creation, but this page wasn't served correctly.
- No need to load gapi on the notebook page unless it's actually needed (DriveFileManager).
- Downloading the notebook was broken because of the '/files' handler.
> Fix loading newly created notebooks

- sources/web/datalab/polymer/components/delete-dialog/delete-dialog.html
The column name is needed in order to show the items.
> Fix delete dialog not showing item names

- tools/cli/commands/create.py
- tools/cli/commands/creategpu.py
- tools/cli/datalab.py
This change modifies the `datalab create` and `datalab beta create-gpu`
commands to improve the way they prompt for a zone in two ways:
1. Get the configured value for the zone setting from gcloud instead
of first trying to create the disk and then prompting for the
zone if that fails.
2. Because of #1, they know right away whether or not to prompt for
a zone, so they do that before doing anything else.
This fixes #1393
> Prompt for zone immediately

- sources/web/datalab/polymer/components/item-list/item-list.ts
- sources/web/datalab/polymer/test/file-browser-test.ts
- sources/web/datalab/polymer/test/item-list-test.ts
When sorting/filtering, the selected items' real indices should be distinguished from their render index. This PR fixes a bug where this wasn't the element's behavior, and the element returned the render indices of the items selected.
Additionally, this PR also fixes the behavior of Select/Unselect All to only work on the currently visible (filtered) items.
Fixes https://github.com/googledatalab/datalab/issues/1857.
> Fix item-list index issues while sorting/filtering

- tools/cli/commands/create.py
The `datalab create` command is using a regex format for listing
the cloud source repositories that will be unsupported by a future
version of gcloud.
That causes gcloud to print a warning message (that does not get
presented to the user) about the format changing.
This commit fixes that by switching to the new format.
> Silence a deprecation warning from gcloud.

- tools/cli/commands/connect.py
- tools/cli/commands/utils.py
- tools/cli/datalab.py
The previous default verbosity level was 'error'. This produces more
concise output, but it caused a good deal of user confusion when
the tool needed to perform a lot of setup steps (like creating a
network), and the user had no indication of what was going on.
The effect of that previous behavior was that the `datalab create`
command would seemingly hang for several minutes without giving
the user any indication whether or not it was making progress.
To avoid that issue, this change modifies the default verbosity
level to provide the user a notification every time the tool
starts to perform a potentially long-running operation.
More specifically, under the new behavior, the tool will print
(by default) a message before it:
1. Creates the network
2. Creates the firewall rule
3. Creates …
> Improve the default verbosity.

- sources/web/datalab/polymer/components/file-browser/file-browser.ts
- sources/web/datalab/polymer/modules/utils/utils.ts
This fixes an issue where dialogs can be opened multiple times if the toolbar buttons are clicked too quickly.
Currently, we have no use case for opening multiple dialogs on top of each other, but this could change. This PR prevents multiple dialogs *of the same type* from opening, allowing an error dialog for example to appear on top of a new notebook dialog if we need.
> Check existing dialogs before opening new ones

- tools/cli/commands/creategpu.py
- tools/cli/commands/delete.py
- tools/cli/commands/utils.py
This change prevents an issue where gcloud would issue a misleading
prompt when we ran `datalab delete`.
The issue was that gcloud would unconditionally issue a prompt
telling the user about its `--keep-disks` flag, which does not
appear directly in the `datalab delete` command (we instead have
a `--keep-disk` flag).
This change silences that prompt from gcloud and replaces it with
a custom prompt that we issue.
Since this is the second instance of the tool issuing a confirmation
prompt, I've moved the logic for issuing those into the utils package.
I've also made a modification to the `maybe_prompt_for_zone` method
so that the check for the `quiet` flag is nested deeper inside of
it. That allows the `--quiet` flag to work with instances that have
a single, obvious zone even if the …
> Silence a misleading prompt from gcloud.

- sources/web/datalab/static/datalab.js
- sources/web/datalab/static/notebook-app.js
This race condition showed up in long notebooks that had a lot of front-end resources to load, where by the time the `notebook-app.postLoad` executes, the `main.min.js` script had already tried to call the original `add_kernel_help_links`, which hasn't been overridden yet. This caused the UI to freeze completely.
> Fix notebook-app race condition

- sources/web/datalab/config/settings.json
- sources/web/datalab/fileSearch.ts
We've seen a few users hit slowdown issues with a MacOS bug with the Chokidar package we're using for indexing, so we're disabling indexing by default unless the host is a GCP VM, which don't have the slowdown issue.
> Disable file search by default, except on GCP VMs

- sources/web/datalab/reverseProxy.ts
- sources/web/datalab/server.ts
This change adds support for receiving requests to "${PORT}-dot-$(hostname)",
and forwarding those requests to another server in the container running
on that port.
This is similar to the existing support for proxying requests to
"/_port/${PORT}/", but with one important difference; since the port
number is taken from the host instead of the path, the requests do
not need to be modified and the other server does not need to know
about our proxying logic.
With this change, if I start Datalab locally with the following
command:
docker run --rm -it \
--hostname "$(hostname)" \
-p 127.0.0.1:8082:8080 datalab
then I can send requests to the ungit server at port 8083 by running:
curl -v 8083-dot-$(hostname):8082
(Assuming I have an /etc/hosts entry for "8083-dot-$(hostname)")
> Proxy requests by hostname in addition to URL path.

- sources/web/datalab/polymer/components/item-list/item-list.ts
- sources/web/datalab/polymer/test/item-list-test.ts
This avoids an n^2 problem in data browser on unselect-all.
> Only propagate list item changes when selection state actually changes.

- sources/web/datalab/polymer/components/datalab-icons/datalab-icons.html
- sources/web/datalab/polymer/modules/bigquery-file-manager/bigquery-file-manager.ts
We probably should revisit the BQ icons we are using. For now, this icon provides a bit of visual distinction between BQ tables and views.
> Add icon for BQ views.

- sources/web/datalab/polymer/modules/api-manager/api-manager.ts
`getAccessTokenInfo` recently replaced `getCurrentUser`, which used to be async, but that PR missed the `await`.
> Wait for access token

- containers/base/Dockerfile
- containers/base/Dockerfile.gpu
- containers/base/build.gpu.sh
- tools/release/cloudbuild.yaml
Switching to Tensorflow 1.4
Updating to cuDNN v6 for GPU images as that version is required by TF
1.4, this has the additional benefit of adding support for P100 GPUs.
Fixes https://github.com/googledatalab/datalab/issues/1879 and https://github.com/googledatalab/datalab/issues/1803
> Switching to Tensorflow 1.4

- tools/cli/commands/create.py
- tools/cli/commands/creategpu.py
This fixes an issue that appears to have only occurred with the
COS-based GPU instances, where the instance would fail to clone
the 'datalab-notebooks' repository.
The root cause was that the instance would reboot while the startup
script was running. That would interrupt it after the disk was
formatted, but before the repository was cloned. This, in turn
caused the repo to never be cloned, as subsequent startups would
see that the disk was already formatted.
This change tries to mitigate the likelihood of that happening
by moving the long running operation (downloading the Datalab
image to run the 'git clone' command) to before the disk is
formatted.
> Fix a bug where the repo cloning was being interrupted.

- tools/cli/commands/create.py
- tools/cli/commands/creategpu.py
This tries to make the startup logic for mounting (and, if necessary,
formatting) the persistent disk more reliable. It does that by
making two changes:
1. Verify that the disk has not already been formatted before
proceeding with the format command.
2. Configure the Datalab systemd service to not start until after
we have verified that the startup script has finished creating
the directories that Datalab needs.
The goal of this change is to prevent the sporadic failures reported
in #1898
> Improvements to startup reliability.

- sources/web/datalab/polymer/bower.json
- sources/web/datalab/polymer/components/item-list/item-list.html
- sources/web/datalab/polymer/components/item-list/item-list.ts
- sources/web/datalab/polymer/tsconfig.json
This is an exploratory PR to try out Polymer's Typescript decorators, which are now at a state that I feel supports all of our scenarios. It simplifies the syntax and removes some of the boilerplate, with the caveat of an extra include and having to pay attention to some details, such as on declaring an observer using [one of two ways](https://github.com/polymer/polymer-decorators#observetargets-string).
I'm trying them out on a fairly well test component: `item-list`, and it looks like the behavior is unchanged. Let me know what you think, if this looks cleaner I can go ahead and proceed with the rest of the components.
> Try Polymer's Typescript decorators on item-list

- sources/web/datalab/reverseProxy.ts
The regex used to parse a port number out of a hostname (e.g.
'<PORT>-dot-myhost.com'), was meant to support an actual port
number being in the hostname (e.g. '<PORT1>-dot-myhost.com:<PORT2>').
That was how I tested the previous change; by adding a local host
entry for "8083-dot-localhost" and then connecting to
"8083-dot-localhost:8081" to view the ungit UI of a Datalab instance.
However, the previous version of that regex inadvertantly required
the ":<PORT>" suffix in the host header. This meant that the
feature did not work when tried against a real hostname.
This change fixes that by making the ":<PORT>" suffix optional.
> Fix a bug where the port-in-hostname regex was too strict.

- sources/web/datalab/polymer/modules/api-manager/api-manager.ts
We need the Authorization header on all requests going to the backend, not just requests to get the basepath.
> Add the Authorization header to basepath requests

- tools/cli/commands/create.py
When trying to deploy a custom gcr.io based Docker image, like:
```
$ datalab create --image-name=gcr.io/<PROJECT_ID>/datalab:test datalab-01
```
We get this error:
```
$ sudo journalctl -f -u datalab
systemd[1]: [/etc/systemd/system/datalab.service:8] Executable path is not absolute, ignoring: docker-credential-gcr configure-docker
```
This is fixed by this pull request.
> SystemCtl complains if commands aren’t fully path’d.

- containers/base/Dockerfile
Otherwise tensorflow.keras throws an error "ImportError: `save_model` requires h5py." and even prototyping is not possible.
> h5py added for non-gpu image

- tools/cli/commands/create.py
- tools/cli/commands/creategpu.py
The new [os-login feature](https://cloud.google.com/compute/docs/instances/managing-instance-access)
is not compatible with the `datalab connect` command.
This means that if a user enables os-login for their entire project
(as opposed to enabling it for individual instances), then
`datalab connect` will stop working (this includes for existing
instances).
This change works around that issue by explicitly disabling os-login
at the instance level at creation time.
This fixes #1929
> Disable os-login on newly created instances.

- sources/web/datalab/package.json
- sources/web/datalab/polymer/components/datalab-notification/datalab-notification.ts
- sources/web/datalab/polymer/components/item-list/item-list.ts
- sources/web/datalab/polymer/modules/api-manager/api-manager.ts
- sources/web/datalab/polymer/modules/terminal-manager/terminal-manager.ts
- sources/web/datalab/polymer/package.json
- sources/web/datalab/static.ts
Fixes related to latest tsc 2.7.1, and pining typescript to this version to prevent further breaks.
The main break is related to https://github.com/Microsoft/TypeScript/issues/21549.
> Pin typescript to 2.7.1

- .gitignore
- sources/web/datalab/polymer/package-lock.json
- sources/web/datalab/polymer/package.json
For some reason, npm decided it didn't want to install one of the nested dependencies: @types/assert. This is a direct dependency of polyserve, which is a dependency of polymer-cli, which in turn is a dependency of Datalab. This reproduces locally and on travis, and I'm not sure why this only happens with the latest polymer-cli (1.6.0).
I've also updated a few other dependencies, and put back the good old `package-lock.json` into git so it can help make these investigations easier in the future. (There's no need to review this file.)
> Fix build break

- containers/base/Dockerfile
- containers/base/Dockerfile.gpu
- containers/base/build.gpu.sh
- sources/web/datalab/polymer/package.json
- tools/release/cloudbuild.yaml
Switching to Tensorflow 1.5
Updating to CUDA 9 and cuDNN v7 for GPU images as that version is
required by TF 1.5, this has the additional benefit of adding support
for V100 (Volta) GPUs.
> Switching to Tensorflow 1.5

- containers/datalab/content/run.sh
The datalab-base Dockerfile runs: `jupyter nbextention enable --py widgetsnbextension`
This creates a `/content/.jupyter/nbconfig/notebook.json` file so the widgets are available when Jupyter boots.
When the datalab.service runs, it mounts the persistent disk at `/content`, blowing away that `/content/.jupyter` folder.
This PR enables the widgets extension in run.sh, since that runs AFTER the docker volume is mounted.
Original Error:
Before this fix:
```
user@datalab-test ~ $ ls -al /mnt/disks/datalab-pd/content/.jupyter
total 12
drwxr-xr-x  2 root root 4096 Jan 30 18:22 .
drwxr-xr-x 11 root root 4096 Jan 30 18:30 ..
-rw-r--r--  1 root root   26 Jan 30 18:22 migrated
```
After this fix:
```
user@datalab-test ~ $ ls -al /mnt/disks/datalab-pd/content/.jupyter
total 16
drwxr-xr-x  3 root …
```
> Re-enable the jupyter widgets nb extension

- .gitignore
- sources/web/datalab/static/appbar.html
- sources/web/datalab/static/datalab.css
The root cause is similar to https://github.com/googledatalab/datalab/issues/1815. So is the fix.
Also adding datalab's `package-lock.json` to gitignore.
> Fix firefox rename button

- sources/web/datalab/static/datalab.css
Codemirror needs an explicit height setting.
> Fix codemirror scrollbar on editor page

- tools/cli/datalab.py
The `datalab` command is meant to support a set of flags (such
as "project" and "zone") at two different levels. The first level
is right after the `datalab` command itself. The second level is
after one of the subcommands (e.g. `create`, or `stop`).
However, the flags defined at each level used the same destination
field in the returned argparse namespace. That seems to have caused
an issue where the default of the nested flag would override any
specified value for the top-level flag. That resulted in the top
level flags being no-ops; an value provided to them was ignored.
This fixes that issue by having two separate destinations for a
flag defined at both the top-level and in a subcommand. The tool
then resolves any provided values manually, favoring the nested
flag value if both are …
> Fix a bug in the parsing of top-level flags.

- tools/cli/datalab.py
This can be used to help diagnose user issues. If a user has a command
that is failing, then they can add the `--diagnose-me` flag, and report
the output (after they manually scrub any sensitive information out of it).
> Add a `--diagnose-me` flag.

- tools/cli/tests/end-to-end.py
- tools/release/cloudbuild.yaml
This test runs in Google Cloud Builder and verifies that basic
usage of the CLI (create, list, delete, stop, and connect) works
prior to the CLI tarball being generated and pushed to GCS.
> Add a validation test for the CLI bundle.

- tools/cli/datalab.py
This way users will always have at least something to look at when we report that a gcloud command fails.
> Always print out the nested command on failure.

- tools/cli/tests/end-to-end.py
1. Print each command that will be run before it is run (to aid in debugging)
2. Use a new, distinct network for each instance. This prevents issues
caused by incompatible firewall rules on the `datalab-network` network.
> Improvements to the CLI tarball validation tests:

- tools/release/cloudbuild.yaml
With the new CLI validation tests, the cloud builder is doing a lot more work.
This change increases the corresponding timeout to account for the additional work it is now doing
> Increase the cloud build timeout

- tools/cli/commands/connect.py
- tools/cli/commands/create.py
- tools/cli/commands/creategpu.py
- tools/cli/datalab.py
1. Add the version of the Cloud SDK and datalab component used to
create an instance to that instance's metadata.
2. When connecting to an instance using the `--diagnose-me` flag,
report the version info from that instance's metadata entries.
> Add some basic version information reporting:

- tools/cli/commands/utils.py
- tools/cli/datalab.py
This change was prompted by the recent issue we had with version
20180105, where an issue was discovered, but we did not have a
good means of notifying users about the issue.
With this change, the CLI will download a versions info file from
https://storage.googleapis.com/cloud-datalab/version-issues.js
that contains a JSON object reporting known issues for any
affected versions of the CLI. It will then check the current
version against that object and report any matching warnings.
> Add a facility to warn users of versions with known issues.

- containers/base/Dockerfile
h5py references it's tests directory during import, so removing it will make it fail to import.
Moving back to using the conda version of the package instead of pip since conda wasn't the issue.
> Don't delete the h5py tests directory.

- tools/cli/commands/__init__.py
- tools/cli/commands/connect.py
- tools/cli/commands/create.py
- tools/cli/commands/creategpu.py
- tools/cli/commands/delete.py
- tools/cli/commands/stop.py
- tools/cli/commands/utils.py
- tools/cli/datalab.py
- tools/cli/tests/end-to-end.py
- tools/release/cloudbuild.yaml
This change fixes all of the incompatibilities in the command
line tool with regard to running in Python 3.
This also extends the build to run the end-to-end tests in
both Python 2 and Python 3.
> Make the command-line tool work in Python 3.

- containers/base/Dockerfile
The current installation of conda uses --add to add the conda-forge channel which results in the demotion of packages from the defaults channel. Since conda-forge packages use open_blas (non-mkl) versions of packages such as numpy are installed affecting performance. 
By first updating conda to a version post 4.1 we can use --append to add the conda-forge channel so that default packages still take precedence. Then mkl versions of packages will be installed by default. This should result in a nice performance boost for many users.
> Use packages from conda defaults channel first

- tools/cli/commands/creategpu.py
Hi, I have tried to create instance of gpu-based datalab, but unfortunately instance start is failed, because link for NVIDIA drivers no longer works. But, there is 390.46 version available, so if change it, instance is working fine.
> Update nvidia driver version

- containers/base/Dockerfile
- containers/base/build.gpu.sh
- tools/release/cloudbuild.yaml
PR #1994 upgraded GPU instances to use version 390.46 of the
NVIDIA drivers, but that version is meant to be used against
version 9.1 of the CUDA toolkit and we were using version
9.0 of the toolkit.
This change fixes this by upgrading to the base image that
includes the newer version of the CUDA toolkit.
> Upgrade the GPU images to use version 9.1 of the CUDA toolkit.

- containers/base/Dockerfile
Previously, we were picking the version of protobuf implicitly,
and the version in the Python 2 env (3.2.0) was different from
the version in the Python 3 env (3.5.2).
With the upgrade of the tensorflow library to 1.8.0, it is no longer
compatible with version 3.2.0 of the protobuf library, so this
is required for the new version of tensorflow to work in the
python 2 environment.
> Pin the version of the protobuf library installed.

- tools/cli/tests/end-to-end.py
This change extends the end-to-end test for the CLI so that instead
of always using port 8081 (the default), it picks a port that was
free at the time the connection was being created.
This is meant to fix a recent regression in the tests where it would
fail in our Cloud Builder runs due to the port not being available.
There is still a race condition where the port could be grabbed by
another process between the time that it is picked and the time that
the connection is created, but that is not worth worrying about.
> Make the end-to-end CLI test use a free port for connections.

- tools/cli/tests/end-to-end.py
This changes the CLI end-to-end test so that it defaults to
picking a random zone in the region 'us-west' instead of being
hard-coded to 'us-west1-a'.
The test will still honor the 'zone' config setting in gcloud if
it is set; this only changes the behavior when that is not set.
> Pick a random zone for CLI tests.

- sources/build.sh
This updates the portion of the build script that installs
NodeJS if it is not already installed on the build machine.
This mainly affects our Cloud Build config, as the build takes
place inside of a container that does not already have NodeJS
installed.
The reason for this change is that Polymer CLI recently updated,
and the new version fails if the version of NodeJS is older than
7.0. This change has broken our Cloud Build config, and is
blocking the Datalab release.
> Update the version of Node JS installed when building.

- sources/web/datalab/config/settings.json
I don't see a need for this. Comment if you think otherwise.
> Disable CORS for the notebook server

- tools/cli/tests/end-to-end.py
Our automated Container-Builder test runs have been failing a lot
recenty with errors saying that the selected port for a Datalab
connection was already in use.
Since we pick a free port for the connection, and nothing else
is running in the container, the only explanation I can think of
is that the port has not yet been freed from when we initially
connected to it (in order to find a free port).
To fix this, we add a sleep of 10 seconds between picking the
port and trying to use it.
> Fix a potential source of CI test flakiness.

- containers/base/build.gpu.sh
- containers/base/build.sh
The Datalab Jenkins build still uses an old Docker version with incompatible flags; this causes confusing output during local builds. E.g.
```bash
$ cd containers/datalab && ./build.sh
...
unknown shorthand flag: 'f' in -f
See 'docker tag --help'.
....
```
I've updated both build scripts to redirect these errors to `/dev/null`.
> redirect stderr to /dev/null for local "docker tag -f" failures

- tools/cli/tests/end-to-end.py
The previous version of this logic retried a test if any of its
`self.assert...` calls failed.
However, that does not handle the case where a nested call to
`datalab` fails. In those cases a `CalledProcessError` would be
raised.
To retry on those scenarios as well, we extend the retry logic
to retry on any instance of the `Exception` class.
> Retry integration tests on any exception.

- tools/cli/commands/create.py
- tools/cli/commands/creategpu.py
The configuration of our logger container has apparently bit-rotted
with the result being that logs from the Datalab docker container
were no longer being sent to StackDriver logging.
There are three types of changes included here:
1. Adding a fluentd config to write Docker container logs to
StackDriver.
2. Add another volume mount from the host to the logger container so
that it can pick up the new fluentd config.
3. Update to a newer version of the fluentd logger image.
> Fix a bug where Docker logs were no longer being sent to StackDriver

- containers/mock/Dockerfile
- containers/mock/README.md
- tools/release/cloudbuild.yaml
This is meant to greatly reduce the turn-around time for debugging changes to the creation/connection logic of the CLI.
By having a much smaller mock image we should be able to get a much lower latency between making a change and seeing whether or not the connection still works.
> Create a mock Datalab image that can be used when testing changes to the CLI

- containers/base/Dockerfile
- containers/datalab/content/run.sh
This change fixes some inconsistencies and potential issues around
assorted notebook extensions.
1. Make sure that every installed extension package has a pinned
verison.
2. Update the pinned versions of ipywidgets and widgetsnbextension to
be compatible.
3. Install the jupyter_highlight_selected_widget extension prior to
enabling it.
4. Enable all of the extensions system wide. Previously, the widgets
extension was enabled for the user, and then re-enabled at startup
after the user's home directory was changed.
> Make the installed nbextensions more consistent.

- containers/base/Dockerfile
The latest version of `apache-beam` is incompatible with the latest
version of `dill` (both released within the past two weeks).
We were not previously pinning the versions of those packages, so the
result is that in newly built images you cannot import `apache_beam`.
That shows up in our ML Toolbox sample notebooks, as they indirectly
import apache_beam.
This change fixes that by pinning the versions of both `apache-beam`
and `dill`.
> Fix an incompatibility introduced by new PyPI releases.

- sources/web/datalab/config/settings.json
Fixes #2022
I verified that the previous issues seen with connections via Cloud Shell when using the `allow_origin` flag are not present, and that localhost works as well.
> Uses allow_origin_pat to fix Cloud Shell connections

- containers/base/Dockerfile
This was conflicting with the (older) `google-cloud-dataflow` library
which is what the `mltoolbox` modules in the `pydatalab` library are
written against.
We could alternatively update the mltoolbox modules to work with the
newer apache-beam library, but that is a more involved process.
The `apache-beam` installation was just added this week (when I was
trying to fix a regression caused by an update to `dill`), so no one
should be depending on this yet, as it was never included in a
released image.
> Remove the `apache-beam` library.

- tools/cli/commands/connect.py
- tools/cli/datalab.py
This change adds a timeout to the health check, after which the
SSH tunnel will be killed (triggering it to be recreated), if
the health check never succeeds before that timeout.
This adds an important check to catch issues where the SSH tunnel
itself is unhealthy as opposed to the connecting instance being
unhealthy.
This fixes #2051
> Timeout Datalab connections if they never become healthy

- tools/cli/commands/create.py
Added required --region flag to the ensure_subnet_exists procedure.
Region is calculated based on the zone selected by the user when issuing the datalab create command, either by argument or by interactive selection
> Added --region flag to ensure_subnet_exists

- containers/base/Dockerfile
This missing dependency was causing the pydatalab extension to silently fail when loaded.
Note that there are breaking changes in `google-cloud-monitoring` versions `0.29.0` and above, meaning we cannot upgrade past `0.28.0` without also updating pydatalab.
> Fix broken pydatalab ipython extension loading

- tools/release/cloudbuild.yaml
Our automated Cloud Builds run multiple long-running integration tests in both Python 2 and Python 3 environments.
As such, they've started taking longer than the previous timeout of 2 hours.
> Increase our automated build timeout to 3 hours

- tools/cli/commands/create.py
Apparently, Container Optimized OS stores the users database in a temp
filesystem, causing it to get lost and recreated every time an
instance is restarted.
Among the many important things recorded in that database is the
mapping from user names (e.g. `datalab`) to user numeric
IDs (e.g. `2000`). By recreating the users database on every restart,
that mapping can change seemingly randomly.
For instance, the `datalab` user can have an ID of `2000` on one boot,
with the `logger` user having an ID of `2001`, and after rebooting the
instance those numbers could be reversed: `datalab` having a user ID
of `2001` and `logger` having a user ID of `2000`.
Since file ownership is defined in terms of user ID, this means that
the owner of files under each home directory can change randomly every
time …
> Ensure that home directories have the right owner at startup.

- sources/web/datalab/common.d.ts
- sources/web/datalab/config/settings.json
- sources/web/datalab/server.ts
In this mode, Datalab will refuse all websocket requests, and any
HTTP requests other than 'HEAD' or 'GET' requests.
> Enable Datalab to run in a read-only mode.

- sources/web/datalab/static/datalab.css
- sources/web/datalab/static/notebook-list.js
- sources/web/datalab/templates/tree.html
- test/client-unit/notebook-list_spec.js
The file search auto-complete functionality depends on the jquery-ui library, but its reference and import were removed in the migration to notebook==5.0.0.
Fixes #2073.
> Add back jquery-ui dependency

- sources/web/datalab/polymer/modules/gapi-manager/gapi-manager.ts
Apparently, "drive.appfolder" has been renamed "drive.appdata"
> Update the Drive scopes used by the polymer UI

- containers/base/Dockerfile
We are replacing the `google-cloud-dataflow` package with `apache-beam` as, according to the Google Cloud Dataflow project's release notes, "The Cloud Dataflow SDK 2.5.0 is the last Cloud Dataflow SDK release that is separate from the Apache Beam SDK releases."
https://cloud.google.com/dataflow/release-notes/release-notes-python
> Update pytz and replace google-cloud-dataflow lib with apache-beam[gcp]

- containers/base/Dockerfile
I have to move PY3 package installation to a different command group to work around a build problem.
For some reasons, if we merge them, local docker build works but cloud build fails mysteriously with error:
Step #13 - "buildBase": /bin/bash: /usr/local/envs/py3env/bin/pip: /usr/local/envs/py3env/bin/python: bad interpreter: Invalid argument
ERROR: (gcloud.builds.submit) build 8b66a0db-d857-4dff-b31c-bd2442ce1d1e completed with status "FAILURE"
Step #13 - "buildBase": The command '/bin/bash -c ...
The change may increase the docker image size a bit.
> Separate Py3 package installations in Conda

- containers/base/third_party_licenses.csv
- tools/cli/datalab.py
Two issues are fixed here:
- The most recent flake8 version breaks on a cli string comparison.
- One of our third party license locations has changed, so updating accordingly. This was originally discovered and fixed by @bnajlis in #2121.
Fixes https://github.com/googledatalab/datalab/issues/2120.
> Fix build at HEAD

- containers/base/Dockerfile
Resolves Issue #2128  . The version of pyyaml supplied by default from conda is not compatible with google-cloud-dataflow, specified a compatible version in the conda create command.
> Resolves issue with build related to pyyaml

- containers/base/Dockerfile
This should fix the travis tests that have been failing, or at least make them progress past the build stage.
> Installs pandas-profiling early to avoid issue installing as part of pydatalab

- tools/cli/commands/create.py
This fixes the firewall rule name creation, and firewall project to enable support for shared vpcs. fixes #2125
> Added Shared VPC Support

- tools/cli/commands/create.py
Created warning message when using --no-firewall rule to better explain functionality
> Added warning message to --no-firewall-rule

- containers/base/Dockerfile
- containers/base/license.sh
- containers/base/third_party_licenses.csv
- sources/web/datalab/config/settings.json
- sources/web/datalab/server.ts
Adapted from rctay's comment on #2169, also bumps some dependencies that are unavailable in conda and updates license URLs.
> Update Jupyter config to new Cloud Shell domain.

- containers/base/Dockerfile
Avoids https://github.com/google/apitools/issues/175, matches six version in
current container (sha256:d8826f5df792ddde9e152da08309edefc79b5ef30bf9232ef98c6772dffe6f7b).
> Pin six==1.11.0 -> six==1.10.0
